# Explore the macroalgal microbiome use case

This notebook analyzes MAGs for the macroalgal microbiome use case.

**Inputs**: data in `../data/marine-use-case/data/`:
- `drep.csv`: dRep clustering output
- `checkm2.tsv`: CheckM2 quality assessment
- `gtdb.tsv`: GTDB taxonomy classification
- `quast.tsv`: QUAST assembly statistics
- `bakta.tsv`: BAKTA genome annotation

**Outputs**
- Plots: `../results/marine-use-case/`

In [1]:
from pathlib import Path
import sys

import pandas as pd
import numpy as np

sys.path.insert(0, str((Path.cwd() / "bin").resolve()))
sys.path.insert(0, str(Path.cwd().resolve()))

from helpers import (
    load_dfs,
    compute_print_stats,
    explore_species_level_clusters_all,
    compute_taxo_classification_summary,
    get_all_taxo_levels,
    get_bakta_annot_df,
    get_kegg_path_df,
    get_relative_abund_taxo_levels,
    print_stats,
)

In [2]:
uc_name = "macroalgal-epiphytic"

metadata_df, reps_df, coverage_df = load_dfs(uc_name)

# Quality

In [3]:
print(f"Total number of MAGs: {reps_df['Cluster members'].sum()}")
print(f"Total number of species-level clusters: {reps_df.shape[0]}")

Total number of MAGs: 897
Total number of species-level clusters: 832

In [4]:
explore_species_level_clusters_all(reps_df)

Species-level clusters with no contamination threshold
Total number: 832.0
Cluster members: 1.08 ± 0.30, Median: 1.00, IQR: 1.00-1.00, Range: 1.00-3.00
Contamination: 1.42 ± 1.95, Median: 0.62, IQR: 0.06-1.91, Range: 0.00-10.18
Completeness: 44.39 ± 36.55, Median: 30.80, IQR: 9.70-88.40, Range: 0.00-100.00
Total length: 1.82 ± 1.61, Median: 1.28, IQR: 0.40-2.96, Range: 0.05-7.59

In [5]:
mapped = coverage_df.query("Genome != 'unmapped'").drop(columns="Genome").sum(axis=0)
unmapped = 100 - mapped
print_stats(unmapped.describe().to_frame("Unmapped reads"))
print_stats(mapped.describe().to_frame("Mapped reads (sum over all genomes, stats over samples)"))

Unmapped reads: 54.92 ± 16.42, Median: 50.71, IQR: 45.86-61.87, Range: 41.01-73.04
Mapped reads (sum over all genomes, stats over samples): 45.08 ± 16.42, Median: 49.29, IQR: 38.13-54.14, Range: 26.96-58.99

# Clusters given Bowers et al / MIMAG classification

## HQ: High-quality species-level clusters (contamination < 5% and completeness > 90%)

In [6]:
hq_df = reps_df.query("Contamination < 5 and Completeness > 90")
hq_df

,MAG,Domain,Phylum,Class,Order,Family,Genus,Species,Domain (GTDB),Phylum (GTDB),...,kegg_dTDP-D-angolosamine biosynthesis,kegg_dTDP-D-desosamine biosynthesis,kegg_dTDP-D-forosamine biosynthesis,kegg_dTDP-D-mycaminose biosynthesis,kegg_dTDP-L-megosamine biosynthesis,kegg_dTDP-L-mycarose biosynthesis,kegg_dTDP-L-oleandrose biosynthesis,kegg_dTDP-L-olivose biosynthesis,kegg_dTDP-L-rhamnose biosynthesis,kegg_dTDP-beta-L-noviose biosynthesis
0,SRR22878281_binette_bin2,Bacteria,Pseudomonadota,Alphaproteobacteria,Rhizobiales,Hyphomicrobiaceae,CAJQQK01,unclassified,Bacteria,Pseudomonadota,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100.0,NaN
1,SRR22878283_binette_bin9,Bacteria,Bdellovibrionota,Bacteriovoracia,Bacteriovoracales,Bacteriovoracaceae,CAKZJW01,unclassified,Bacteria,Bdellovibrionota,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,50.0,NaN
2,SRR22878281_binette_bin11,Bacteria,Pseudomonadota,Gammaproteobacteria,Arenicellales,Arenicellaceae,Arenicella,unclassified,Bacteria,Pseudomonadota,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100.0,NaN
3,SRR22878281_binette_bin11,Bacteria,Pseudomonadota,Gammaproteobacteria,Arenicellales,Arenicellaceae,Arenicella,unclassified,Bacteria,Pseudomonadota,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100.0,NaN
4,SRR22878281_binette_bin12,Bacteria,Pseudomonadota,Gammaproteobacteria,Granulosicoccales,Granulosicoccaceae,Granulosicoccus,unclassified,Bacteria,Pseudomonadota,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
185,SRR22878281_binette_bin45,Bacteria,Pseudomonadota,Alphaproteobacteria,Caulobacterales,Maricaulaceae,JACOMS01,unclassified,Bacteria,Pseudomonadota,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100.0,NaN
186,SRR22878281_binette_bin45,Bacteria,Pseudomonadota,Alphaproteobacteria,Caulobacterales,Maricaulaceae,JACOMS01,unclassified,Bacteria,Pseudomonadota,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100.0,NaN
187,SRR22878283_binette_bin36,Bacteria,Bacteroidota,Bacteroidia,Flavobacteriales,Flavobacteriaceae,Croceitalea,Croceitalea vernalis,Bacteria,Bacteroidota,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100.0,NaN
188,SRR22878282_binette_bin21,Bacteria,Bacteroidota,Bacteroidia,Flavobacteriales,Flavobacteriaceae,Postechiella,unclassified,Bacteria,Bacteroidota,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,50.0,NaN
189,SRR22878282_binette_bin21,Bacteria,Bacteroidota,Bacteroidia,Flavobacteriales,Flavobacteriaceae,Postechiella,unclassified,Bacteria,Bacteroidota,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,50.0,NaN

In [7]:
compute_print_stats(hq_df) 
print(f"Total number: {len(hq_df)} ({len(hq_df) / len(reps_df) * 100:.2f}%)")

Total number: 182.0
Cluster members: 1.18 ± 0.46, Median: 1.00, IQR: 1.00-1.00, Range: 1.00-3.00
Contamination: 1.19 ± 1.05, Median: 1.02, IQR: 0.27-1.72, Range: 0.00-4.65
Completeness: 96.31 ± 3.25, Median: 96.90, IQR: 93.28-99.60, Range: 90.10-100.00
Total length: 3.76 ± 1.17, Median: 3.55, IQR: 2.96-4.43, Range: 1.03-7.12
Total number: 182 (21.88%)

### Taxonomy

In [8]:
compute_taxo_classification_summary(hq_df)

,Unclassified clusters,Classified clusters,Unclassified clusters %,Classified clusters %
Domain,0,182,0.0,100.0
Phylum,0,182,0.0,100.0
Class,0,182,0.0,100.0
Order,0,182,0.0,100.0
Family,6,176,3.3,96.7
Genus,24,158,13.19,86.81
Species,168,14,92.31,7.69

In [9]:
hq_taxo_levels = get_all_taxo_levels(hq_df)

Level: Domain

          Cluster  Cluster %  Total MAG count
Domain
Bacteria    182.0      100.0            215.0
TOTAL       182.0      100.0            215.0

Level: Phylum

                    Cluster   Cluster %  Total MAG count
Phylum
Pseudomonadota        104.0   57.142857            112.0
Bacteroidota           40.0   21.978022             61.0
Cyanobacteriota        10.0    5.494505             10.0
Actinomycetota          6.0    3.296703              6.0
Myxococcota_A           6.0    3.296703              6.0
Bdellovibrionota        4.0    2.197802              6.0
Patescibacteriota       4.0    2.197802              6.0
Acidobacteriota         2.0    1.098901              2.0
Bdellovibrionota_B      2.0    1.098901              2.0
Myxococcota             2.0    1.098901              2.0
Verrucomicrobiota       2.0    1.098901              2.0
TOTAL                 182.0  100.000000            215.0

Level: Class

                     Cluster   Cluster %  Total MAG count
Class
Bacteroidia             40.0   21.978022             61.0
Gammaproteobacteria     50.0   27.472527             58.0
Alphaproteobacteria     54.0   29.670330             54.0
Cyanobacteriia          10.0    5.494505             10.0
Acidimicrobiia           6.0    3.296703              6.0
UBA9160                  6.0    3.296703              6.0
Bacteriovoracia          4.0    2.197802              6.0
JAEDAM01                 2.0    1.098901              4.0
Blastocatellia           2.0    1.098901              2.0
Polyangia                2.0    1.098901              2.0
Saccharimonadia          2.0    1.098901              2.0
UBA2361                  2.0    1.098901              2.0
Verrucomicrobiia         2.0    1.098901              2.0
TOTAL                  182.0  100.000000            215.0

Level: Order

                    Cluster   Cluster %  Total MAG count
Order
Flavobacteriales       34.0   18.681319             55.0
Pseudomonadales        21.0   11.538462             22.0
Caulobacterales        20.0   10.989011             20.0
Enterobacterales        8.0    4.395604             13.0
Granulosicoccales      12.0    6.593407             12.0
Sphingomonadales       11.0    6.043956             11.0
Rhizobiales            11.0    6.043956             11.0
Cyanobacteriales       10.0    5.494505             10.0
Arenicellales           7.0    3.846154              7.0
Bacteriovoracales       4.0    2.197802              6.0
Geminicoccales          6.0    3.296703              6.0
Acidimicrobiales        6.0    3.296703              6.0
Rhodobacterales         6.0    3.296703              6.0
UBA9160                 6.0    3.296703              6.0
Chitinophagales         4.0    2.197802              4.0
UBA4575                 2.0    1.098901              4.0
BD1-5                   2.0    1.098901              4.0
Polyangiales            2.0    1.098901              2.0
Pyrinomonadales         2.0    1.098901              2.0
Cytophagales            2.0    1.098901              2.0
Saccharimonadales       2.0    1.098901              2.0
UBA2361                 2.0    1.098901              2.0
Verrucomicrobiales      2.0    1.098901              2.0
TOTAL                 182.0  100.000000            215.0

Level: Family

                    Cluster   Cluster %  Total MAG count
Family
Flavobacteriaceae      34.0   18.681319             55.0
Maricaulaceae          14.0    7.692308             14.0
Cellvibrionaceae       12.0    6.593407             13.0
Alteromonadaceae        8.0    4.395604             13.0
Granulosicoccaceae     12.0    6.593407             12.0
Sphingomonadaceae      11.0    6.043956             11.0
Xenococcaceae           8.0    4.395604              8.0
Arenicellaceae          7.0    3.846154              7.0
Geminicoccaceae         6.0    3.296703              6.0
Rhodobacteraceae        6.0    3.296703              6.0
unclassified            6.0    3.296703              6.0
Bacteriovoracaceae      4.0    2.197802              6.0
Rhizobiaceae            5.0    2.747253              5.0
Hyphomonadaceae         4.0    2.197802              4.0
UBA4575                 2.0    1.098901              4.0
UBA6164                 2.0    1.098901              4.0
Azotimanducaceae        4.0    2.197802              4.0
CALHAX01                4.0    2.197802              4.0
SMWR01                  4.0    2.197802              4.0
Pyrinomonadaceae        2.0    1.098901              2.0
Hyphomicrobiaceae       2.0    1.098901              2.0
JAHQVX01                2.0    1.098901              2.0
DEV007                  2.0    1.098901              2.0
Cyclobacteriaceae       2.0    1.098901              2.0
Parvularculaceae        2.0    1.098901              2.0
Polyangiaceae           2.0    1.098901              2.0
DSM-21967               2.0    1.098901              2.0
SHLQ01                  2.0    1.098901              2.0
GM7GCV1                 2.0    1.098901              2.0
SZUA-35                 2.0    1.098901              2.0
Saprospiraceae          2.0    1.098901              2.0
UBA10347                2.0    1.098901              2.0
UBA4427                 2.0    1.098901              2.0
Moraxellaceae           1.0    0.549451              1.0
TOTAL                 182.0  100.000000            215.0

Level: Genus

                   Cluster   Cluster %  Total MAG count
Genus
unclassified          24.0   13.186813             26.0
Aquimarina            10.0    5.494505             12.0
Postechiella           4.0    2.197802             10.0
Arenicella             7.0    3.846154              7.0
Maribacter_C           4.0    2.197802              6.0
...                    ...         ...              ...
Agarilytica            2.0    1.098901              2.0
Lacinutrix             1.0    0.549451              2.0
Psychrobacter          1.0    0.549451              1.0
Lentilitoribacter      1.0    0.549451              1.0
TOTAL                182.0  100.000000            215.0

[63 rows x 3 columns]

Level: Species

                                Cluster   Cluster %  Total MAG count
Species
unclassified                      168.0   92.307692            188.0
Cellulophaga lytica                 1.0    0.549451              3.0
Dokdonia sp947496725                1.0    0.549451              3.0
Olleya sediminilitoris              1.0    0.549451              3.0
Pseudoalteromonas marina            1.0    0.549451              3.0
Croceitalea vernalis                1.0    0.549451              2.0
Lacinutrix sp000211855              1.0    0.549451              2.0
Maribacter litoralis                1.0    0.549451              2.0
Marinagarivorans sp947494095        1.0    0.549451              2.0
Pseudoalteromonas atlantica         1.0    0.549451              2.0
Arenicella sp040366405              1.0    0.549451              1.0
Lentilitoribacter sp020628775       1.0    0.549451              1.0
Marinagarivorans algicola           1.0    0.549451              1.0
Parasphingorhabdus sp039982415      1.0    0.549451              1.0
Psychrobacter sp002377945           1.0    0.549451              1.0
TOTAL                             182.0  100.000000            215.0

### Relative abundance

In [10]:
hq_relative_abund_df = get_relative_abund_taxo_levels(hq_df, coverage_df)

Unmapped reads: 80.68 ± 7.93, Median: 77.16, IQR: 76.14-83.46, Range: 75.12-89.76
Mapped reads: 19.32 ± 7.93, Median: 22.84, IQR: 16.54-23.86, Range: 10.24-24.88

Level: Family

,count,mean,std,min,25%,50%,75%,max
Family,,,,,,,,
Flavobacteriaceae,3.0,45.917115,11.086574,36.242300,39.868309,43.494317,50.754522,58.014728
Cellvibrionaceae,3.0,12.370510,17.156165,0.326603,2.548839,4.771075,18.392464,32.013853
Sphingomonadaceae,3.0,5.286303,4.406424,0.234318,3.761265,7.288212,7.812295,8.336379
Alteromonadaceae,3.0,4.995996,3.357696,2.053601,3.167139,4.280677,6.467194,8.653711
Maricaulaceae,3.0,3.494973,2.878067,0.404811,2.192941,3.981072,5.040054,6.099036
Xenococcaceae,3.0,2.928851,3.484666,0.039074,0.993993,1.948913,4.373740,6.798567
Granulosicoccaceae,3.0,2.833944,2.185364,0.374142,1.975146,3.576150,4.063845,4.551540
Arenicellaceae,3.0,2.217070,2.607447,0.128755,0.755844,1.382933,3.261227,5.139521
Hyphomonadaceae,3.0,1.969531,2.629104,0.083174,0.467962,0.852750,2.912709,4.972668
unclassified,3.0,1.946138,1.717955,0.025678,1.250822,2.475967,2.906368,3.336770
GM7GCV1,3.0,1.614585,2.790646,0.000000,0.003406,0.006813,2.421878,4.836943
Rhodobacteraceae,3.0,1.252937,1.741105,0.123802,0.250369,0.376936,1.817504,3.258072
Polyangiaceae,3.0,1.213671,2.102139,0.000000,0.000000,0.000000,1.820506,3.641012
Bacteriovoracaceae,3.0,1.188034,0.979786,0.056747,0.899669,1.742590,1.753677,1.764764
JAHQVX01,3.0,1.166075,2.019700,0.000000,0.000000,0.000000,1.749112,3.498224
Geminicoccaceae,3.0,1.099053,0.978849,0.110095,0.614846,1.119597,1.593533,2.067469
Rhizobiaceae,3.0,0.896277,1.070558,0.157192,0.282434,0.407676,1.265819,2.123962
DSM-21967,3.0,0.801761,1.275578,0.027793,0.065629,0.103466,1.188745,2.274024
Azotimanducaceae,3.0,0.792787,0.429926,0.496087,0.546266,0.596445,0.941138,1.285830
UBA4575,3.0,0.784107,0.785932,0.044011,0.371661,0.699311,1.154155,1.608999
UBA6164,3.0,0.728197,0.151547,0.599311,0.644722,0.690132,0.792640,0.895147
CALHAX01,3.0,0.673808,1.113113,0.000000,0.031408,0.062816,1.010712,1.958608
SMWR01,3.0,0.574539,0.995130,0.000000,0.000000,0.000000,0.861808,1.723616
UBA10347,3.0,0.528004,0.914530,0.000000,0.000000,0.000000,0.792006,1.584012
Cyclobacteriaceae,3.0,0.469551,0.813286,0.000000,0.000000,0.000000,0.704326,1.408652
Pyrinomonadaceae,3.0,0.396193,0.686227,0.000000,0.000000,0.000000,0.594290,1.188579
SZUA-35,3.0,0.350149,0.606476,0.000000,0.000000,0.000000,0.525224,1.050447
Hyphomicrobiaceae,3.0,0.319568,0.553509,0.000000,0.000000,0.000000,0.479353,0.958705
SHLQ01,3.0,0.289099,0.500734,0.000000,0.000000,0.000000,0.433649,0.867298
Saprospiraceae,3.0,0.235491,0.380783,0.000000,0.015836,0.031671,0.353236,0.674801
UBA4427,3.0,0.197726,0.342472,0.000000,0.000000,0.000000,0.296590,0.593179
Parvularculaceae,3.0,0.176396,0.282656,0.000000,0.013387,0.026774,0.264593,0.502413
DEV007,3.0,0.169676,0.293887,0.000000,0.000000,0.000000,0.254514,0.509027
Moraxellaceae,3.0,0.121886,0.211113,0.000000,0.000000,0.000000,0.182829,0.365658

Level: Genus

,count,mean,std,min,25%,50%,75%,max
Genus,,,,,,,,
unclassified,3.0,16.864858,20.957848,4.155741,4.770038,5.384335,23.219417,41.054499
Aquimarina,3.0,15.481835,23.306296,0.200958,2.069242,3.937526,23.122273,42.307020
Cellulophaga,3.0,10.178136,13.866727,0.301126,2.251786,4.202447,15.116640,26.030834
Postechiella,3.0,6.168215,6.186407,0.690269,2.813425,4.936581,8.907188,12.877794
Dokdonia,3.0,4.216697,4.807290,1.005900,1.453250,1.900600,5.822095,9.743590
...,...,...,...,...,...,...,...,...
CAKZUP01,3.0,0.196244,0.301589,0.000000,0.022612,0.045223,0.294366,0.543510
CALHVX01,3.0,0.186574,0.268755,0.012306,0.031818,0.051329,0.273708,0.496087
JAUIGD01,3.0,0.169676,0.293887,0.000000,0.000000,0.000000,0.254514,0.509027
Lentilitoribacter,3.0,0.149837,0.160273,0.024350,0.059564,0.094779,0.212580,0.330381
Psychrobacter,3.0,0.121886,0.211113,0.000000,0.000000,0.000000,0.182829,0.365658

Level: Species

,count,mean,std,min,25%,50%,75%,max
Species,,,,,,,,
unclassified,3.0,78.459246,18.961977,58.060492,69.914462,81.768433,88.658622,95.548812
Cellulophaga lytica,3.0,10.178136,13.866727,0.301126,2.251786,4.202447,15.116640,26.030834
Dokdonia sp947496725,3.0,4.216697,4.807290,1.005900,1.453250,1.900600,5.822095,9.743590
Pseudoalteromonas atlantica,3.0,1.413222,1.257358,0.157823,0.783568,1.409312,2.040922,2.672531
Lacinutrix sp000211855,3.0,1.361587,1.167712,0.129317,0.816515,1.503712,1.977722,2.451731
Maribacter litoralis,3.0,1.104303,1.363866,0.086823,0.329433,0.572042,1.613043,2.654043
Pseudoalteromonas marina,3.0,0.905768,0.924540,0.334394,0.372437,0.410479,1.191454,1.972430
Marinagarivorans sp947494095,3.0,0.423268,0.481044,0.021210,0.156798,0.292387,0.624298,0.956208
Olleya sediminilitoris,3.0,0.417397,0.216793,0.201522,0.308547,0.415572,0.525334,0.635096
Arenicella sp040366405,3.0,0.400376,0.616553,0.006952,0.045091,0.083230,0.597088,1.110946
Croceitalea vernalis,3.0,0.395643,0.271526,0.117516,0.263441,0.409366,0.534707,0.660048
Marinagarivorans algicola,3.0,0.256435,0.404372,0.011903,0.023059,0.034216,0.378701,0.723186
Parasphingorhabdus sp039982415,3.0,0.196201,0.252446,0.037942,0.050636,0.063329,0.275331,0.487332
Lentilitoribacter sp020628775,3.0,0.149837,0.160273,0.024350,0.059564,0.094779,0.212580,0.330381
Psychrobacter sp002377945,3.0,0.121886,0.211113,0.000000,0.000000,0.000000,0.182829,0.365658

### Functions

In [11]:
print_stats(get_bakta_annot_df(hq_df).describe())

CDSs: 3374.03 ± 945.84, Median: 3211.00, IQR: 2693.50-4055.75, Range: 1037.00-5968.00
CRISPR arrays: 0.21 ± 0.77, Median: 0.00, IQR: 0.00-0.00, Range: 0.00-4.00
gaps: 0.00 ± 0.00, Median: 0.00, IQR: 0.00-0.00, Range: 0.00-0.00
hypotheticals: 1032.20 ± 594.48, Median: 904.50, IQR: 564.00-1365.50, Range: 184.00-3018.00
ncRNA regions: 5.92 ± 2.82, Median: 6.00, IQR: 4.00-8.00, Range: 1.00-15.00
ncRNAs: 6.04 ± 6.52, Median: 4.00, IQR: 3.00-6.00, Range: 1.00-51.00
oriCs: 0.03 ± 0.19, Median: 0.00, IQR: 0.00-0.00, Range: 0.00-2.00
oriTs: 0.00 ± 0.00, Median: 0.00, IQR: 0.00-0.00, Range: 0.00-0.00
oriVs: 0.00 ± 0.00, Median: 0.00, IQR: 0.00-0.00, Range: 0.00-0.00
pseudogenes: 5.20 ± 6.15, Median: 3.00, IQR: 1.00-7.00, Range: 0.00-33.00
rRNAs: 1.15 ± 1.19, Median: 1.00, IQR: 0.00-2.00, Range: 0.00-8.00
sORFs: 0.23 ± 0.46, Median: 0.00, IQR: 0.00-0.00, Range: 0.00-2.00
signal peptides: 0.00 ± 0.00, Median: 0.00, IQR: 0.00-0.00, Range: 0.00-0.00
tRNAs: 36.68 ± 8.60, Median: 35.00, IQR: 30.00-42.00, Range: 17.00-64.00
tmRNAs: 0.74 ± 0.49, Median: 1.00, IQR: 0.00-1.00, Range: 0.00-2.00

In [12]:
get_kegg_path_df(hq_df)

Before removing rows and columns with only zeros:
Clusters: 182
KEGG modules: 405

After removing rows and columns with only zeros:
Clusters: 182
KEGG modules: 378

KEGG modules: 194.59 ± 21.95, Median: 195.00, IQR: 186.25-205.00, Range: 78.00-245.00

,"10-membered enediyne core biosynthesis, malonyl-CoA => 3-hydroxyhexadeca-4,6,8,10,12,14-hexaenoyl-ACP => 10-membered enediyne core",3-Hydroxypropionate bi-cycle,"9-membered enediyne core biosynthesis, malonyl-CoA => 3-hydroxyhexadeca-4,6,8,10,12,14-hexaenoyl-ACP => 9-membered enediyne core",ADP-L-glycero-D-manno-heptose biosynthesis,"Abscisic acid biosynthesis, beta-carotene => abscisic acid","Acarbose biosynthesis, sedoheptulopyranose-7P => acarbose",Acylglycerol degradation,"Adenine ribonucleotide biosynthesis, IMP => ADP,ATP","Adenine ribonucleotide degradation, AMP => Urate","Aerobactin biosynthesis, lysine => aerobactin",...,beta-Oxidation,"beta-Oxidation, acyl-CoA synthesis","beta-Oxidation, peroxisome, VLCFA","beta-Oxidation, peroxisome, tri/dihydroxycholestanoyl-CoA => choloyl/chenodeoxycholoyl-CoA",dTDP-D-angolosamine biosynthesis,dTDP-D-desosamine biosynthesis,dTDP-D-forosamine biosynthesis,dTDP-L-megosamine biosynthesis,dTDP-L-olivose biosynthesis,dTDP-L-rhamnose biosynthesis
0,0.0,52.78,0.0,0.0,0.0,0.0,0.0,100.0,77.78,0.0,...,100.0,100.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,100.0
1,0.0,22.22,0.0,100.0,0.0,0.0,0.0,100.0,100.00,0.0,...,100.0,100.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,50.0
2,0.0,11.11,0.0,100.0,0.0,0.0,0.0,100.0,66.67,0.0,...,100.0,100.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,100.0
3,0.0,11.11,0.0,100.0,0.0,0.0,0.0,100.0,66.67,0.0,...,100.0,100.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,100.0
4,0.0,27.78,0.0,20.0,0.0,0.0,0.0,100.0,100.00,0.0,...,100.0,100.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,100.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
185,0.0,25.00,0.0,0.0,0.0,0.0,50.0,100.0,66.67,0.0,...,100.0,100.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,100.0
186,0.0,25.00,0.0,0.0,0.0,0.0,50.0,100.0,66.67,0.0,...,100.0,100.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,100.0
187,0.0,27.78,0.0,0.0,20.0,0.0,0.0,100.0,50.00,0.0,...,100.0,100.0,33.33,0.0,0.0,0.0,0.0,0.0,0.0,100.0
188,0.0,24.54,0.0,0.0,20.0,0.0,0.0,100.0,50.00,0.0,...,50.0,100.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,50.0
189,0.0,24.54,0.0,0.0,20.0,0.0,0.0,100.0,50.00,0.0,...,50.0,100.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,50.0

## MQ: Medium-quality species-level clusters (contamination < 10% and completeness > 50%)

In [13]:
mq_df = reps_df.query("Contamination < 10 and Completeness > 50")
compute_print_stats(mq_df)
print(f"Total number: {len(mq_df)} ({len(mq_df) / len(reps_df) * 100:.2f}%)")

Total number: 328.0
Cluster members: 1.16 ± 0.43, Median: 1.00, IQR: 1.00-1.00, Range: 1.00-3.00
Contamination: 2.17 ± 2.08, Median: 1.61, IQR: 0.78-2.86, Range: 0.00-9.98
Completeness: 86.59 ± 14.03, Median: 92.25, IQR: 80.15-97.80, Range: 50.60-100.00
Total length: 3.37 ± 1.23, Median: 3.19, IQR: 2.47-4.02, Range: 0.22-7.12
Total number: 328 (39.42%)

### Taxonomy

In [14]:
compute_taxo_classification_summary(mq_df)

,Unclassified clusters,Classified clusters,Unclassified clusters %,Classified clusters %
Domain,2,326,0.61,99.39
Phylum,2,326,0.61,99.39
Class,2,326,0.61,99.39
Order,2,326,0.61,99.39
Family,8,320,2.44,97.56
Genus,40,288,12.2,87.8
Species,300,28,91.46,8.54

In [15]:
mq_taxo_levels = get_all_taxo_levels(mq_df)

Level: Domain

                Cluster   Cluster %  Total MAG count
Domain
Bacteria          323.0   98.475610            373.0
unclassified        2.0    0.609756              3.0
Archaea             2.0    0.609756              2.0
Pseudomonadati      1.0    0.304878              2.0
TOTAL             328.0  100.000000            380.0

Level: Phylum

                    Cluster   Cluster %  Total MAG count
Phylum
Pseudomonadota        166.0   50.609756            175.0
Bacteroidota           74.0   22.560976            106.0
Actinomycetota         20.0    6.097561             24.0
Cyanobacteriota        16.0    4.878049             16.0
Myxococcota_A          10.0    3.048780             10.0
Verrucomicrobiota      10.0    3.048780             10.0
Bdellovibrionota        6.0    1.829268              8.0
Patescibacteriota       6.0    1.829268              8.0
Planctomycetota         6.0    1.829268              6.0
Acidobacteriota         4.0    1.219512              4.0
Chloroflexota           2.0    0.609756              4.0
unclassified            2.0    0.609756              3.0
Bdellovibrionota_B      2.0    0.609756              2.0
Myxococcota             2.0    0.609756              2.0
Thermoproteota          2.0    0.609756              2.0
TOTAL                 328.0  100.000000            380.0

Level: Class

                     Cluster   Cluster %  Total MAG count
Class
Bacteroidia             74.0   22.560976            106.0
Gammaproteobacteria     79.0   24.085366             88.0
Alphaproteobacteria     87.0   26.524390             87.0
Acidimicrobiia          20.0    6.097561             24.0
Cyanobacteriia          16.0    4.878049             16.0
Verrucomicrobiia        10.0    3.048780             10.0
UBA9160                 10.0    3.048780             10.0
Bacteriovoracia          6.0    1.829268              8.0
Planctomycetia           6.0    1.829268              6.0
JAEDAM01                 2.0    0.609756              4.0
Anaerolineae             2.0    0.609756              4.0
Blastocatellia           4.0    1.219512              4.0
unclassified             2.0    0.609756              3.0
UBA2361                  2.0    0.609756              2.0
Polyangia                2.0    0.609756              2.0
Nitrososphaeria          2.0    0.609756              2.0
Gracilibacteria          2.0    0.609756              2.0
Saccharimonadia          2.0    0.609756              2.0
TOTAL                  328.0  100.000000            380.0

Level: Order

                       Cluster   Cluster %  Total MAG count
Order
Flavobacteriales          66.0   20.121951             96.0
Pseudomonadales           29.0    8.841463             30.0
Caulobacterales           27.0    8.231707             27.0
Acidimicrobiales          20.0    6.097561             24.0
Rhizobiales               21.0    6.402439             21.0
Rhodobacterales           18.0    5.487805             18.0
Enterobacterales          12.0    3.658537             17.0
Granulosicoccales         16.0    4.878049             16.0
Sphingomonadales          15.0    4.573171             15.0
Arenicellales             13.0    3.963415             13.0
Cyanobacteriales          12.0    3.658537             12.0
UBA9160                   10.0    3.048780             10.0
UBA4575                    6.0    1.829268              8.0
Bacteriovoracales          6.0    1.829268              8.0
Chitinophagales            6.0    1.829268              8.0
Verrucomicrobiales         8.0    2.439024              8.0
Pirellulales               6.0    1.829268              6.0
Geminicoccales             6.0    1.829268              6.0
BD1-5                      2.0    0.609756              4.0
Promineifilales            2.0    0.609756              4.0
Pyrinomonadales            4.0    1.219512              4.0
Thermosynechococcales      4.0    1.219512              4.0
unclassified               2.0    0.609756              3.0
UWMA-0217                  2.0    0.609756              2.0
UBA4473                    2.0    0.609756              2.0
UBA2361                    2.0    0.609756              2.0
Saccharimonadales          2.0    0.609756              2.0
Polyangiales               2.0    0.609756              2.0
Opitutales                 2.0    0.609756              2.0
Nitrososphaerales          2.0    0.609756              2.0
Cytophagales               2.0    0.609756              2.0
Vibrionales                1.0    0.304878              2.0
TOTAL                    328.0  100.000000            380.0

Level: Family

                        Cluster   Cluster %  Total MAG count
Family
Flavobacteriaceae          66.0   20.121951             96.0
Maricaulaceae              19.0    5.792683             19.0
Rhodobacteraceae           18.0    5.487805             18.0
Granulosicoccaceae         16.0    4.878049             16.0
Cellvibrionaceae           14.0    4.268293             15.0
Alteromonadaceae           10.0    3.048780             15.0
Sphingomonadaceae          15.0    4.573171             15.0
Arenicellaceae             13.0    3.963415             13.0
Rhizobiaceae               13.0    3.963415             13.0
SHLQ01                      8.0    2.439024             12.0
unclassified                8.0    2.439024              9.0
Xenococcaceae               8.0    2.439024              8.0
UBA4575                     6.0    1.829268              8.0
Bacteriovoracaceae          6.0    1.829268              8.0
GM7GCV1                     6.0    1.829268              6.0
SZUA-35                     6.0    1.829268              6.0
DEV007                      6.0    1.829268              6.0
Saprospiraceae              4.0    1.219512              6.0
Geminicoccaceae             6.0    1.829268              6.0
UBA4427                     6.0    1.829268              6.0
UBA10347                    6.0    1.829268              6.0
Pirellulaceae               6.0    1.829268              6.0
Hyphomonadaceae             6.0    1.829268              6.0
Azotimanducaceae            4.0    1.219512              4.0
Promineifilaceae            2.0    0.609756              4.0
UBA6164                     2.0    0.609756              4.0
Vibrionaceae                3.0    0.914634              4.0
SMWR01                      4.0    1.219512              4.0
CALHAX01                    4.0    1.219512              4.0
Pyrinomonadaceae            4.0    1.219512              4.0
Thermosynechococcaceae      4.0    1.219512              4.0
Hyphomicrobiaceae           4.0    1.219512              4.0
JAHQVX01                    2.0    0.609756              2.0
Nitrosopumilaceae           2.0    0.609756              2.0
Coraliomargaritaceae        2.0    0.609756              2.0
Cyclobacteriaceae           2.0    0.609756              2.0
DSM-21967                   2.0    0.609756              2.0
JAAUPO01                    2.0    0.609756              2.0
UBA4473                     2.0    0.609756              2.0
JAUIET01                    2.0    0.609756              2.0
Parvularculaceae            2.0    0.609756              2.0
Polyangiaceae               2.0    0.609756              2.0
Akkermansiaceae             2.0    0.609756              2.0
UWMA-0217                   2.0    0.609756              2.0
Moraxellaceae               1.0    0.304878              1.0
TOTAL                     328.0  100.000000            380.0

Level: Genus

                   Cluster   Cluster %  Total MAG count
Genus
unclassified          40.0   12.195122             43.0
Aquimarina            13.0    3.963415             15.0
Arenicella            13.0    3.963415             13.0
JAALLB01              12.0    3.658537             12.0
SHLQ01                 8.0    2.439024             12.0
...                    ...         ...              ...
Maribacter_B           1.0    0.304878              1.0
Litoreibacter          1.0    0.304878              1.0
Lentilitoribacter      1.0    0.304878              1.0
Psychrobacter          1.0    0.304878              1.0
TOTAL                328.0  100.000000            380.0

[88 rows x 3 columns]

Level: Species

                                Cluster   Cluster %  Total MAG count
Species
unclassified                      300.0   91.463415            335.0
Olleya sediminilitoris              1.0    0.304878              3.0
Cellulophaga lytica                 1.0    0.304878              3.0
Dokdonia sp947496725                1.0    0.304878              3.0
Pseudoalteromonas marina            1.0    0.304878              3.0
Polaribacter marinaquae             1.0    0.304878              2.0
Croceitalea vernalis                1.0    0.304878              2.0
Lacinutrix sp000211855              1.0    0.304878              2.0
Maribacter litoralis                1.0    0.304878              2.0
Maribacter sp020629285              1.0    0.304878              2.0
Marinagarivorans sp947494095        1.0    0.304878              2.0
unclassified Vibrio                 1.0    0.304878              2.0
Pseudoalteromonas atlantica         1.0    0.304878              2.0
Tenacibaculum sp004337695           1.0    0.304878              2.0
Vibrio cyclitrophicus               1.0    0.304878              1.0
Vibrio coralliirubri                1.0    0.304878              1.0
Dokdonia sp000355805                1.0    0.304878              1.0
Tenacibaculum sp947499065           1.0    0.304878              1.0
Hellea sp020629875                  1.0    0.304878              1.0
Lentilitoribacter sp020628775       1.0    0.304878              1.0
Polaribacter sp947496195            1.0    0.304878              1.0
Sulfitobacter pontiacus             1.0    0.304878              1.0
Psychrobacter sp002377945           1.0    0.304878              1.0
Maribacter_B vaceletii              1.0    0.304878              1.0
Marinagarivorans algicola           1.0    0.304878              1.0
Arenicella sp040366405              1.0    0.304878              1.0
Aquimarina latercula                1.0    0.304878              1.0
Parasphingorhabdus sp039982415      1.0    0.304878              1.0
Litoreibacter sp947494645           1.0    0.304878              1.0
TOTAL                             328.0  100.000000            380.0

### Relative abundance

In [16]:
mq_relative_abund_df = get_relative_abund_taxo_levels(mq_df, coverage_df)

Unmapped reads: 73.26 ± 8.53, Median: 69.14, IQR: 68.35-76.10, Range: 67.56-83.06
Mapped reads: 26.74 ± 8.53, Median: 30.86, IQR: 23.90-31.65, Range: 16.94-32.44

Level: Family

,count,mean,std,min,25%,50%,75%,max
Family,,,,,,,,
Flavobacteriaceae,3.0,42.058922,10.065736,35.192530,36.281580,37.370631,45.492118,53.613604
Cellvibrionaceae,3.0,7.934858,10.126733,0.490720,2.169040,3.847360,11.656927,19.466494
Sphingomonadaceae,3.0,4.333819,3.692108,0.178980,2.881392,5.583804,6.411239,7.238674
Maricaulaceae,3.0,4.004491,3.044146,0.677865,2.681154,4.684443,5.667804,6.651165
Alteromonadaceae,3.0,3.599345,1.992512,1.458229,2.699435,3.940640,4.669902,5.399165
Arenicellaceae,3.0,3.418590,1.365231,1.938442,2.813646,3.688850,4.158665,4.628479
Vibrionaceae,3.0,2.960235,4.228998,0.066327,0.533570,1.000813,4.407189,7.813565
Granulosicoccaceae,3.0,2.521925,1.468668,0.914845,1.885657,2.856468,3.325465,3.794461
Rhodobacteraceae,3.0,2.476063,2.406922,0.904243,1.090597,1.276951,3.261973,5.246994
GM7GCV1,3.0,2.173926,3.761196,0.000000,0.002399,0.004797,3.260889,6.516980
unclassified,3.0,2.145693,0.696135,1.420043,1.814549,2.209055,2.508518,2.807980
Xenococcaceae,3.0,1.999225,2.481846,0.031509,0.605127,1.178746,2.983082,4.787419
Hyphomonadaceae,3.0,1.737136,2.454153,0.050305,0.329425,0.608544,2.580552,4.552560
Thermosynechococcaceae,3.0,1.427204,2.471991,0.000000,0.000000,0.000000,2.140807,4.281613
Rhizobiaceae,3.0,1.320572,0.956012,0.222275,0.997866,1.773457,1.869721,1.965985
UBA4575,3.0,1.281699,1.372858,0.035490,0.545894,1.056297,1.904803,2.753309
SHLQ01,3.0,1.093774,0.350001,0.691314,0.977189,1.263064,1.295004,1.326945
Bacteriovoracaceae,3.0,1.040841,0.957005,0.039960,0.587805,1.135649,1.541281,1.946913
SZUA-35,3.0,1.031336,0.942651,0.094424,0.557193,1.019963,1.499793,1.979622
UBA4427,3.0,1.006502,1.422012,0.075605,0.188075,0.300544,1.471950,2.643356
Geminicoccaceae,3.0,0.840726,0.801584,0.066588,0.427493,0.788399,1.227795,1.667192
JAHQVX01,3.0,0.821127,1.422234,0.000000,0.000000,0.000000,1.231691,2.463381
Saprospiraceae,3.0,0.812063,0.800233,0.020897,0.407562,0.794228,1.207646,1.621064
UBA10347,3.0,0.740790,1.283086,0.000000,0.000000,0.000000,1.111185,2.222370
Polyangiaceae,3.0,0.734055,1.271420,0.000000,0.000000,0.000000,1.101082,2.202165
Promineifilaceae,3.0,0.585004,0.518744,0.000000,0.383024,0.766047,0.877506,0.988965
Azotimanducaceae,3.0,0.582321,0.393705,0.349335,0.355039,0.360743,0.698814,1.036884
DSM-21967,3.0,0.562105,0.900214,0.022412,0.042495,0.062578,0.831951,1.601323
JAAUPO01,3.0,0.526792,0.632714,0.000000,0.175894,0.351787,0.790187,1.228587
UBA6164,3.0,0.516446,0.138357,0.362477,0.459497,0.556518,0.593431,0.630345
CALHAX01,3.0,0.472402,0.785552,0.000000,0.018996,0.037992,0.708603,1.379214
SMWR01,3.0,0.404579,0.700752,0.000000,0.000000,0.000000,0.606869,1.213737
Pyrinomonadaceae,3.0,0.383959,0.648418,0.000000,0.009636,0.019273,0.575939,1.132605
Hyphomicrobiaceae,3.0,0.362625,0.628085,0.000000,0.000000,0.000000,0.543938,1.087876
Nitrosopumilaceae,3.0,0.319346,0.441749,0.013121,0.066146,0.119170,0.472458,0.825746
Pirellulaceae,3.0,0.315308,0.546129,0.000000,0.000000,0.000000,0.472962,0.945923
DEV007,3.0,0.315185,0.545916,0.000000,0.000000,0.000000,0.472777,0.945555
Cyclobacteriaceae,3.0,0.283995,0.491893,0.000000,0.000000,0.000000,0.425992,0.851984
UWMA-0217,3.0,0.226330,0.392015,0.000000,0.000000,0.000000,0.339495,0.678990
UBA4473,3.0,0.167847,0.248480,0.014627,0.024501,0.034374,0.244457,0.454540
Parvularculaceae,3.0,0.123328,0.199750,0.000000,0.008097,0.016194,0.184991,0.353789
Coraliomargaritaceae,3.0,0.091906,0.159186,0.000000,0.000000,0.000000,0.137860,0.275719
Akkermansiaceae,3.0,0.087884,0.152220,0.000000,0.000000,0.000000,0.131826,0.263653
Moraxellaceae,3.0,0.085830,0.148661,0.000000,0.000000,0.000000,0.128745,0.257489
JAUIET01,3.0,0.071892,0.124521,0.000000,0.000000,0.000000,0.107839,0.215677

Level: Genus

,count,mean,std,min,25%,50%,75%,max
Genus,,,,,,,,
unclassified,3.0,13.626611,13.955864,5.406590,5.569740,5.732889,17.736622,29.740354
Aquimarina,3.0,12.526848,18.888875,0.747715,1.633344,2.518973,18.416414,34.313854
Cellulophaga,3.0,7.038323,9.846555,0.242826,1.392279,2.541733,10.436071,18.330409
Postechiella,3.0,5.244876,5.443666,0.516750,2.269306,4.021862,7.608938,11.196015
Arenicella,3.0,3.418590,1.365231,1.938442,2.813646,3.688850,4.158665,4.628479
...,...,...,...,...,...,...,...,...
Lentilitoribacter,3.0,0.103203,0.113676,0.019636,0.038480,0.057324,0.144986,0.232648
CALGNO01,3.0,0.091942,0.159249,0.000000,0.000000,0.000000,0.137914,0.275827
Roseibacillus,3.0,0.087884,0.152220,0.000000,0.000000,0.000000,0.131826,0.263653
Psychrobacter,3.0,0.085830,0.148661,0.000000,0.000000,0.000000,0.128745,0.257489
Arctic95D-9,3.0,0.081645,0.141413,0.000000,0.000000,0.000000,0.122467,0.244934

Level: Species

,count,mean,std,min,25%,50%,75%,max
Species,,,,,,,,
unclassified,3.0,79.521767,13.879605,66.218567,72.325822,78.433078,86.173367,93.913657
Cellulophaga lytica,3.0,7.038323,9.846555,0.242826,1.392279,2.541733,10.436071,18.330409
Dokdonia sp947496725,3.0,2.940641,3.399557,0.811150,0.980338,1.149525,4.005386,6.861247
Vibrio cyclitrophicus,3.0,1.179877,1.696689,0.024332,0.205920,0.387507,1.757650,3.127792
Tenacibaculum sp004337695,3.0,0.938796,0.850838,0.239604,0.465137,0.690670,1.288393,1.886115
Vibrio coralliirubri,3.0,0.916185,1.264004,0.017500,0.193522,0.369544,1.365527,2.361510
Pseudoalteromonas atlantica,3.0,0.912028,0.747816,0.127268,0.559839,0.992410,1.304408,1.616406
Lacinutrix sp000211855,3.0,0.882009,0.706106,0.104280,0.581583,1.058885,1.270873,1.482861
unclassified Vibrio,3.0,0.864173,1.269219,0.024496,0.134128,0.243761,1.284012,2.324263
Maribacter litoralis,3.0,0.692686,0.807610,0.070013,0.236417,0.402821,1.004023,1.605224
Pseudoalteromonas marina,3.0,0.583891,0.527566,0.269653,0.279352,0.289051,0.741010,1.192969
Maribacter sp020629285,3.0,0.352984,0.294287,0.058582,0.205898,0.353214,0.500186,0.647157
Marinagarivorans sp947494095,3.0,0.329934,0.394051,0.012828,0.109361,0.205893,0.488486,0.771080
Polaribacter marinaquae,3.0,0.311246,0.330591,0.046240,0.126020,0.205800,0.443749,0.681697
Olleya sediminilitoris,3.0,0.287025,0.145673,0.162506,0.206927,0.251347,0.349285,0.447222
Croceitalea vernalis,3.0,0.270691,0.166387,0.082752,0.206431,0.330110,0.364660,0.399211
Arenicella sp040366405,3.0,0.247979,0.368464,0.004895,0.036006,0.067116,0.369521,0.671925
Tenacibaculum sp947499065,3.0,0.224044,0.283415,0.029695,0.061444,0.093194,0.321219,0.549244
Dokdonia sp000355805,3.0,0.209116,0.294572,0.036391,0.039051,0.041712,0.295478,0.549245
Marinagarivorans algicola,3.0,0.204822,0.327770,0.007199,0.015647,0.024094,0.303633,0.583172
Polaribacter sp947496195,3.0,0.185706,0.247207,0.027738,0.043263,0.058788,0.264690,0.470592
Aquimarina latercula,3.0,0.141288,0.072232,0.059900,0.113044,0.166187,0.181982,0.197776
Parasphingorhabdus sp039982415,3.0,0.137356,0.178281,0.030596,0.034449,0.038303,0.190736,0.343170
Litoreibacter sp947494645,3.0,0.133899,0.172748,0.017470,0.034657,0.051844,0.192113,0.332382
Maribacter_B vaceletii,3.0,0.121357,0.088075,0.023870,0.084440,0.145010,0.170100,0.195189
Hellea sp020629875,3.0,0.106440,0.083782,0.031629,0.061176,0.090724,0.143845,0.196967
Lentilitoribacter sp020628775,3.0,0.103203,0.113676,0.019636,0.038480,0.057324,0.144986,0.232648
Psychrobacter sp002377945,3.0,0.085830,0.148661,0.000000,0.000000,0.000000,0.128745,0.257489
Sulfitobacter pontiacus,3.0,0.076705,0.088141,0.006284,0.027282,0.048280,0.111916,0.175551

### Functions

In [17]:
print_stats(get_bakta_annot_df(mq_df).describe())

CDSs: 3084.15 ± 1038.63, Median: 2975.00, IQR: 2299.50-3613.00, Range: 370.00-5968.00
CRISPR arrays: 0.12 ± 0.58, Median: 0.00, IQR: 0.00-0.00, Range: 0.00-4.00
gaps: 0.00 ± 0.00, Median: 0.00, IQR: 0.00-0.00, Range: 0.00-0.00
hypotheticals: 1049.28 ± 631.71, Median: 842.00, IQR: 559.00-1459.50, Range: 84.00-3018.00
ncRNA regions: 5.68 ± 3.21, Median: 5.00, IQR: 3.00-8.00, Range: 0.00-15.00
ncRNAs: 5.36 ± 5.74, Median: 4.00, IQR: 3.00-6.00, Range: 0.00-51.00
oriCs: 0.02 ± 0.16, Median: 0.00, IQR: 0.00-0.00, Range: 0.00-2.00
oriTs: 0.00 ± 0.00, Median: 0.00, IQR: 0.00-0.00, Range: 0.00-0.00
oriVs: 0.00 ± 0.00, Median: 0.00, IQR: 0.00-0.00, Range: 0.00-0.00
pseudogenes: 6.74 ± 7.74, Median: 4.00, IQR: 1.00-9.00, Range: 0.00-40.00
rRNAs: 0.84 ± 1.07, Median: 1.00, IQR: 0.00-1.00, Range: 0.00-8.00
sORFs: 0.19 ± 0.44, Median: 0.00, IQR: 0.00-0.00, Range: 0.00-2.00
signal peptides: 0.00 ± 0.00, Median: 0.00, IQR: 0.00-0.00, Range: 0.00-0.00
tRNAs: 32.41 ± 11.42, Median: 31.00, IQR: 25.00-38.00, Range: 0.00-65.00
tmRNAs: 0.64 ± 0.53, Median: 1.00, IQR: 0.00-1.00, Range: 0.00-2.00

In [18]:
get_kegg_path_df(mq_df)

Before removing rows and columns with only zeros:
Clusters: 328
KEGG modules: 405

After removing rows and columns with only zeros:
Clusters: 328
KEGG modules: 386

KEGG modules: 188.32 ± 30.16, Median: 192.00, IQR: 181.00-201.25, Range: 2.00-245.00

,"10-membered enediyne core biosynthesis, malonyl-CoA => 3-hydroxyhexadeca-4,6,8,10,12,14-hexaenoyl-ACP => 10-membered enediyne core","2-Oxocarboxylic acid chain extension, 2-oxoglutarate => 2-oxoadipate => 2-oxopimelate => 2-oxosuberate",3-Hydroxypropionate bi-cycle,"9-membered enediyne core biosynthesis, malonyl-CoA => 3-hydroxyhexadeca-4,6,8,10,12,14-hexaenoyl-ACP => 9-membered enediyne core",ADP-L-glycero-D-manno-heptose biosynthesis,"Abscisic acid biosynthesis, beta-carotene => abscisic acid","Acarbose biosynthesis, sedoheptulopyranose-7P => acarbose",Acylglycerol degradation,"Adenine ribonucleotide biosynthesis, IMP => ADP,ATP","Adenine ribonucleotide degradation, AMP => Urate",...,"beta-Oxidation, peroxisome, tri/dihydroxycholestanoyl-CoA => choloyl/chenodeoxycholoyl-CoA",dTDP-D-angolosamine biosynthesis,dTDP-D-desosamine biosynthesis,dTDP-D-forosamine biosynthesis,dTDP-D-mycaminose biosynthesis,dTDP-L-megosamine biosynthesis,dTDP-L-mycarose biosynthesis,dTDP-L-olivose biosynthesis,dTDP-L-rhamnose biosynthesis,dTDP-beta-L-noviose biosynthesis
0,0.0,0.0,52.78,0.0,0.0,0.0,0.0,0.0,100.0,77.78,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,100.00,0.0
1,0.0,0.0,22.22,0.0,100.0,0.0,0.0,0.0,100.0,100.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,50.00,0.0
2,0.0,0.0,11.11,0.0,100.0,0.0,0.0,0.0,100.0,66.67,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,100.00,0.0
3,0.0,0.0,11.11,0.0,100.0,0.0,0.0,0.0,100.0,66.67,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,100.00,0.0
4,0.0,0.0,27.78,0.0,20.0,0.0,0.0,0.0,100.0,100.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,100.00,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
325,0.0,0.0,13.89,0.0,0.0,0.0,0.0,0.0,50.0,66.67,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,50.00,0.0
326,0.0,0.0,13.89,0.0,0.0,0.0,0.0,0.0,50.0,66.67,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,50.00,0.0
327,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0
328,0.0,0.0,14.81,0.0,0.0,0.0,12.5,0.0,75.0,33.33,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,33.33,0.0
329,0.0,0.0,14.81,0.0,0.0,0.0,12.5,0.0,75.0,33.33,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,33.33,0.0

## LQ: Low-quality species-level clusters (contamination < 10% and completeness < 50%)

In [19]:
lq_df = reps_df.query("Contamination < 10 and Completeness < 50")
compute_print_stats(lq_df)
print(f"Total number: {len(lq_df)} ({len(lq_df) / len(reps_df) * 100:.2f}%)")

Total number: 502.0
Cluster members: 1.03 ± 0.16, Median: 1.00, IQR: 1.00-1.00, Range: 1.00-2.00
Contamination: 0.89 ± 1.60, Median: 0.17, IQR: 0.01-1.01, Range: 0.00-8.14
Completeness: 16.72 ± 12.34, Median: 11.55, IQR: 7.40-24.30, Range: 0.00-49.40
Total length: 0.80 ± 0.82, Median: 0.54, IQR: 0.29-1.06, Range: 0.05-7.59
Total number: 502 (60.34%)

## Non classified

In [20]:
nc_df = reps_df.query("Contamination >= 10")
print(f"Total number: {len(nc_df)} ({len(nc_df) / len(reps_df) * 100:.2f}%)")

Total number: 2 (0.24%)