# Explore the termite head microbiome use case

This notebook analyzes MAGs for the macroalgal microbiome use case.

**Inputs**: data in `../data/termite-use-case/data/`:
- `drep.csv`: dRep clustering output
- `checkm2.tsv`: CheckM2 quality assessment
- `gtdb.tsv`: GTDB taxonomy classification
- `quast.tsv`: QUAST assembly statistics
- `bakta.tsv`: BAKTA genome annotation

**Outputs**
- Plots: `../results/termite-use-case/`

In [1]:
from pathlib import Path
import sys

import pandas as pd
import numpy as np

sys.path.insert(0, str((Path.cwd() / "bin").resolve()))
sys.path.insert(0, str(Path.cwd().resolve()))

from helpers import (
    load_dfs,
    compute_print_stats,
    explore_species_level_clusters_all,
    compute_taxo_classification_summary,
    get_all_taxo_levels,
    get_bakta_annot_df,
    get_kegg_path_df,
    get_relative_abund_taxo_levels,
    print_stats,
)

In [2]:
uc_name = "termite-head"

metadata_df, reps_df, coverage_df = load_dfs(uc_name)

In [3]:
coverage_df

,Genome,DE96NGSUKBD140734Dm,DE91NGSUKBD140727Sc,DE90NGSUKBD140745Dm,DE86NGSUKBD140720Sc,DE85NGSUKBD140738Dm,DE80NGSUKBD140731Sc,DE75NGSUKBD140724Sc,DE74NGSUKBD140742Dm,DE69NGSUKBD140735Dm,...,DE32NGSUKBD140722Sc,DE31NGSUKBD140740Dm,DE26NGSUKBD140733Dm,DE21NGSUKBD140726Sc,DE20NGSUKBD140744Dm,DE16NGSUKBD140719Sc,DE15NGSUKBD140737Dm,DE10NGSUKBD140730Sc,DE05NGSUKBD140723Sc,DE04NGSUKBD140741Dm
0,1_binette_bin2,0.883811,0.200619,0.162750,0.164405,0.142707,0.207315,0.178231,0.121080,0.860980,...,0.162682,0.125994,1.261375,0.241634,0.099449,0.191555,0.157853,0.212244,0.163792,0.079584
1,1_binette_bin23,0.000000,0.000000,0.108516,0.021952,0.246538,0.000000,0.000000,0.200913,0.000000,...,0.000000,0.246817,0.000000,0.000000,0.198827,0.000000,0.258648,0.000000,0.000000,0.116347
2,1_binette_bin47,0.821822,0.163736,0.134211,0.143792,0.205379,0.175256,0.148529,0.137711,0.668857,...,0.119854,0.151204,0.978956,0.206246,0.132542,0.153159,0.209786,0.156948,0.141854,0.116215
3,1_binette_bin48,1.237963,0.197796,0.122465,0.160881,0.100440,0.174213,0.174545,0.045904,1.052761,...,0.165867,0.050161,1.546077,0.193140,0.047298,0.180315,0.115318,0.250290,0.151385,0.027920
4,1_binette_bin5,0.482139,0.106381,0.062647,0.082426,0.038615,0.103497,0.090936,0.029260,0.510460,...,0.089053,0.030470,0.795406,0.118414,0.025249,0.094004,0.049238,0.114906,0.081979,0.017966
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
498,8_binette_bin87,0.097356,0.071714,0.039776,0.055995,0.006040,0.074462,0.086981,0.016983,0.103300,...,0.081391,0.014946,0.129486,0.088687,0.017116,0.067939,0.007200,0.093004,0.072505,0.014995
499,8_binette_bin88,0.051689,0.257556,0.126706,0.214830,0.003772,0.218943,0.255256,0.051483,0.099592,...,0.247658,0.049858,0.074788,0.247575,0.057471,0.240648,0.005002,0.349767,0.222045,0.029507
500,8_binette_bin89,0.041779,0.497176,0.275187,0.453499,0.000000,0.405015,0.501107,0.095791,0.121200,...,0.548444,0.092285,0.070299,0.438604,0.118154,0.483913,0.004142,0.666231,0.444182,0.049688
501,8_binette_bin90,0.113743,0.078990,0.036378,0.057268,0.007178,0.074341,0.087195,0.016851,0.096049,...,0.079269,0.015727,0.113966,0.091001,0.019369,0.070425,0.007513,0.087980,0.076787,0.012191
502,unmapped,32.418545,39.364487,48.596214,41.024868,58.104230,41.502594,37.899227,55.737050,37.855686,...,35.501183,56.728424,38.276060,42.551666,55.678505,37.714780,58.346092,38.647514,36.949944,51.767532

In [4]:
# WARNING: high percentage of unmapped
# print("Percentage of unmapped reads for coverage")
# print_stats(coverage_df.query("Genome == 'unmapped'").drop(columns="Genome").T.describe())

# Quality

In [5]:
print(f"Total number of MAGs: {reps_df['Cluster members'].sum()}")
print(f"Total number of species-level clusters: {reps_df.shape[0]}")

Total number of MAGs: 523
Total number of species-level clusters: 502

In [6]:
explore_species_level_clusters_all(reps_df)

Species-level clusters with no contamination threshold
Total number: 502.0
Cluster members: 1.04 ± 0.38, Median: 1.00, IQR: 1.00-1.00, Range: 1.00-8.00
Contamination: 2.03 ± 3.50, Median: 0.02, IQR: 0.00-2.92, Range: 0.00-21.60
Completeness: 17.44 ± 21.65, Median: 7.45, IQR: 3.80-19.53, Range: 2.30-99.30
Total length: 1.19 ± 1.57, Median: 0.52, IQR: 0.27-1.45, Range: 0.05-9.83

Species-level clusters with contamination < 5%
Total number: 411.0
Cluster members: 1.04 ± 0.39, Median: 1.00, IQR: 1.00-1.00, Range: 1.00-8.00
Contamination: 0.59 ± 1.21, Median: 0.01, IQR: 0.00-0.39, Range: 0.00-4.84
Completeness: 11.75 ± 17.94, Median: 5.90, IQR: 3.50-10.45, Range: 2.30-99.30
Total length: 0.66 ± 0.78, Median: 0.38, IQR: 0.24-0.76, Range: 0.05-9.42

Species-level clusters with contamination < 10%
Total number: 479.0
Cluster members: 1.04 ± 0.37, Median: 1.00, IQR: 1.00-1.00, Range: 1.00-8.00
Contamination: 1.53 ± 2.62, Median: 0.02, IQR: 0.00-2.04, Range: 0.00-9.97
Completeness: 15.58 ± 20.34, Median: 7.00, IQR: 3.70-16.20, Range: 2.30-99.30
Total length: 1.02 ± 1.32, Median: 0.48, IQR: 0.26-1.18, Range: 0.05-9.42

# Clusters given Bowers et al / MIMAG classification

## HQ: High-quality species-level clusters (contamination < 5% and completeness > 90%)

In [7]:
hq_df = reps_df.query("Contamination < 5 and Completeness > 90")
hq_df

,MAG,Domain,Phylum,Class,Order,Family,Genus,Species,Cluster members,Completeness,...,"kegg_beta-Oxidation, acyl-CoA synthesis","kegg_beta-Oxidation, peroxisome, VLCFA","kegg_beta-Oxidation, peroxisome, tri/dihydroxycholestanoyl-CoA => choloyl/chenodeoxycholoyl-CoA",kegg_dTDP-D-angolosamine biosynthesis,kegg_dTDP-D-forosamine biosynthesis,kegg_dTDP-L-megosamine biosynthesis,kegg_dTDP-L-mycarose biosynthesis,kegg_dTDP-L-oleandrose biosynthesis,kegg_dTDP-L-olivose biosynthesis,kegg_dTDP-L-rhamnose biosynthesis
0,4_binette_bin1,unclassified,unclassified,unclassified,unclassified,unclassified,unclassified,Truepera radiovictrix,8,99.3,...,100.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100.0
1,2_binette_bin1,unclassified,unclassified,unclassified,unclassified,unclassified,unclassified,unclassified,1,98.7,...,100.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100.0
2,5_binette_bin1,unclassified,unclassified,unclassified,unclassified,unclassified,unclassified,Wolbachia sp000829315,3,97.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2_binette_bin2,unclassified,unclassified,unclassified,unclassified,unclassified,unclassified,unclassified,1,95.2,...,100.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100.0
4,2_binette_bin4,unclassified,unclassified,unclassified,unclassified,unclassified,unclassified,unclassified,1,93.5,...,100.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100.0
5,2_binette_bin5,unclassified,unclassified,unclassified,unclassified,unclassified,unclassified,JAISFT01 sp031258265,1,90.4,...,100.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100.0

In [8]:
compute_print_stats(hq_df)

Total number: 6.0
Cluster members: 2.50 ± 2.81, Median: 1.00, IQR: 1.00-2.50, Range: 1.00-8.00
Contamination: 1.20 ± 1.05, Median: 0.89, IQR: 0.39-1.98, Range: 0.17-2.69
Completeness: 95.68 ± 3.37, Median: 96.10, IQR: 93.92-98.28, Range: 90.40-99.30
Total length: 4.05 ± 2.73, Median: 3.33, IQR: 3.04-3.58, Range: 1.61-9.42

### Taxonomy

In [9]:
compute_taxo_classification_summary(hq_df)

,Unclassified clusters,Classified clusters,Unclassified clusters %,Classified clusters %
Domain,6,0,100.0,0.0
Phylum,6,0,100.0,0.0
Class,6,0,100.0,0.0
Order,6,0,100.0,0.0
Family,6,0,100.0,0.0
Genus,6,0,100.0,0.0
Species,3,3,50.0,50.0

In [10]:
hq_taxo_levels = get_all_taxo_levels(hq_df)

Level: Domain

              Cluster  Cluster %  Total MAG count
Domain
unclassified      6.0      100.0             15.0
TOTAL             6.0      100.0             15.0

Level: Phylum

              Cluster  Cluster %  Total MAG count
Phylum
unclassified      6.0      100.0             15.0
TOTAL             6.0      100.0             15.0

Level: Class

              Cluster  Cluster %  Total MAG count
Class
unclassified      6.0      100.0             15.0
TOTAL             6.0      100.0             15.0

Level: Order

              Cluster  Cluster %  Total MAG count
Order
unclassified      6.0      100.0             15.0
TOTAL             6.0      100.0             15.0

Level: Family

              Cluster  Cluster %  Total MAG count
Family
unclassified      6.0      100.0             15.0
TOTAL             6.0      100.0             15.0

Level: Genus

              Cluster  Cluster %  Total MAG count
Genus
unclassified      6.0      100.0             15.0
TOTAL             6.0      100.0             15.0

Level: Species

                       Cluster   Cluster %  Total MAG count
Species
Truepera radiovictrix      1.0   16.666667              8.0
unclassified               3.0   50.000000              3.0
Wolbachia sp000829315      1.0   16.666667              3.0
JAISFT01 sp031258265       1.0   16.666667              1.0
TOTAL                      6.0  100.000000             15.0

### Relative abundance

In [11]:
hq_relative_abund_df = get_relative_abund_taxo_levels(hq_df, coverage_df)

Unmapped reads: 99.53 ± 0.27, Median: 99.46, IQR: 99.38-99.81, Range: 98.86-99.95
Mapped reads: 0.47 ± 0.27, Median: 0.54, IQR: 0.19-0.62, Range: 0.05-1.14

Level: Family

              count   mean           std    min    25%    50%    75%    max
Family
unclassified   28.0  100.0  7.735410e-15  100.0  100.0  100.0  100.0  100.0

Level: Genus

              count   mean           std    min    25%    50%    75%    max
Genus
unclassified   28.0  100.0  7.735410e-15  100.0  100.0  100.0  100.0  100.0

Level: Species

,count,mean,std,min,25%,50%,75%,max
Species,,,,,,,,
Wolbachia sp000829315,28.0,55.772385,24.419160,5.400492,32.943776,63.758037,74.090248,84.897666
Truepera radiovictrix,28.0,40.400900,22.939717,1.123309,24.939831,34.412899,50.248378,85.674791
unclassified,28.0,3.304241,15.588057,0.000000,0.000000,0.000000,0.000000,82.221217
JAISFT01 sp031258265,28.0,0.522474,2.197785,0.000000,0.000000,0.000000,0.000000,11.254981

### Functions

In [12]:
print_stats(get_bakta_annot_df(hq_df).describe())

CDSs: nan ± nan, Median: nan, IQR: nan-nan, Range: nan-nan
CRISPR arrays: nan ± nan, Median: nan, IQR: nan-nan, Range: nan-nan
gaps: nan ± nan, Median: nan, IQR: nan-nan, Range: nan-nan
hypotheticals: nan ± nan, Median: nan, IQR: nan-nan, Range: nan-nan
ncRNA regions: nan ± nan, Median: nan, IQR: nan-nan, Range: nan-nan
ncRNAs: nan ± nan, Median: nan, IQR: nan-nan, Range: nan-nan
oriCs: nan ± nan, Median: nan, IQR: nan-nan, Range: nan-nan
oriTs: nan ± nan, Median: nan, IQR: nan-nan, Range: nan-nan
oriVs: nan ± nan, Median: nan, IQR: nan-nan, Range: nan-nan
pseudogenes: nan ± nan, Median: nan, IQR: nan-nan, Range: nan-nan
rRNAs: nan ± nan, Median: nan, IQR: nan-nan, Range: nan-nan
sORFs: nan ± nan, Median: nan, IQR: nan-nan, Range: nan-nan
signal peptides: nan ± nan, Median: nan, IQR: nan-nan, Range: nan-nan
tRNAs: nan ± nan, Median: nan, IQR: nan-nan, Range: nan-nan
tmRNAs: nan ± nan, Median: nan, IQR: nan-nan, Range: nan-nan

In [13]:
get_kegg_path_df(hq_df)

Before removing rows and columns with only zeros:
Clusters: 6
KEGG modules: 341

After removing rows and columns with only zeros:
Clusters: 6
KEGG modules: 250

KEGG modules: 164.50 ± 24.62, Median: 165.50, IQR: 155.00-176.00, Range: 126.00-199.00

,"2-Oxocarboxylic acid chain extension, 2-oxoglutarate => 2-oxoadipate => 2-oxopimelate => 2-oxosuberate",3-Hydroxypropionate bi-cycle,ADP-L-glycero-D-manno-heptose biosynthesis,"Acarbose biosynthesis, sedoheptulopyranose-7P => acarbose","Acetyl-CoA pathway, CO2 => acetyl-CoA","Adenine ribonucleotide biosynthesis, IMP => ADP,ATP","Adenine ribonucleotide degradation, AMP => Urate","Arginine biosynthesis, glutamate => acetylcitrulline => arginine","Arginine biosynthesis, ornithine => arginine","Ascorbate biosynthesis, animals, glucose-1P => ascorbate",...,Urea cycle,"V/A-type ATPase, prokaryotes","Validamycin A biosynthesis, sedoheptulopyranose-7P => validamycin A","Valine/isoleucine biosynthesis, pyruvate => valine / 2-oxobutanoate => isoleucine","Vancomycin resistance, D-Ala-D-Lac type","Xanthomonas spp. pathogenicity signature, T3SS and effectors","beta-Carotene biosynthesis, GGAP => beta-carotene",beta-Oxidation,"beta-Oxidation, acyl-CoA synthesis",dTDP-L-rhamnose biosynthesis
0,33.33,27.78,0.0,0.0,0.00,100.0,100.00,42.86,100.00,28.57,...,80.0,88.89,0.00,100.0,25.00,0.00,33.33,100.0,100.0,100.0
1,0.00,5.56,0.0,12.5,0.00,75.0,50.00,42.86,100.00,28.57,...,60.0,77.78,11.11,100.0,0.00,0.00,0.00,0.0,100.0,100.0
2,0.00,11.11,0.0,0.0,0.00,100.0,16.67,14.29,0.00,14.29,...,0.0,0.00,0.00,0.0,0.00,1.14,0.00,0.0,0.0,0.0
3,0.00,2.78,20.0,0.0,33.33,75.0,66.67,42.86,66.67,42.86,...,40.0,77.78,0.00,100.0,25.00,0.00,0.00,0.0,100.0,100.0
4,0.00,22.22,100.0,0.0,0.00,75.0,50.00,85.71,66.67,28.57,...,40.0,0.00,0.00,100.0,16.67,0.00,0.00,0.0,100.0,100.0
5,0.00,11.11,0.0,0.0,0.00,75.0,50.00,57.14,100.00,28.57,...,60.0,77.78,0.00,75.0,25.00,0.00,0.00,0.0,100.0,100.0

## MQ: Medium-quality species-level clusters (contamination < 10% and completeness > 50%)

In [14]:
mq_df = reps_df.query("Contamination < 10 and Completeness > 50")
compute_print_stats(mq_df)

Total number: 47.0
Cluster members: 1.21 ± 1.06, Median: 1.00, IQR: 1.00-1.00, Range: 1.00-8.00
Contamination: 4.72 ± 3.18, Median: 4.81, IQR: 1.94-7.76, Range: 0.00-9.97
Completeness: 68.94 ± 14.60, Median: 64.20, IQR: 56.55-80.35, Range: 50.20-99.30
Total length: 3.24 ± 2.04, Median: 2.53, IQR: 1.95-3.61, Range: 0.73-9.42

### Taxonomy

In [15]:
compute_taxo_classification_summary(mq_df)

,Unclassified clusters,Classified clusters,Unclassified clusters %,Classified clusters %
Domain,43,4,91.49,8.51
Phylum,47,0,100.0,0.0
Class,47,0,100.0,0.0
Order,47,0,100.0,0.0
Family,47,0,100.0,0.0
Genus,47,0,100.0,0.0
Species,40,7,85.11,14.89

In [16]:
mq_taxo_levels = get_all_taxo_levels(mq_df)

Level: Domain

              Cluster   Cluster %  Total MAG count
Domain
unclassified     43.0   91.489362             53.0
Archaea           2.0    4.255319              2.0
Bacteria          2.0    4.255319              2.0
TOTAL            47.0  100.000000             57.0

Level: Phylum

              Cluster  Cluster %  Total MAG count
Phylum
unclassified     47.0      100.0             57.0
TOTAL            47.0      100.0             57.0

Level: Class

              Cluster  Cluster %  Total MAG count
Class
unclassified     47.0      100.0             57.0
TOTAL            47.0      100.0             57.0

Level: Order

              Cluster  Cluster %  Total MAG count
Order
unclassified     47.0      100.0             57.0
TOTAL            47.0      100.0             57.0

Level: Family

              Cluster  Cluster %  Total MAG count
Family
unclassified     47.0      100.0             57.0
TOTAL            47.0      100.0             57.0

Level: Genus

              Cluster  Cluster %  Total MAG count
Genus
unclassified     47.0      100.0             57.0
TOTAL            47.0      100.0             57.0

Level: Species

                       Cluster   Cluster %  Total MAG count
Species
unclassified              40.0   85.106383             41.0
Truepera radiovictrix      1.0    2.127660              8.0
Wolbachia sp000829315      1.0    2.127660              3.0
JAIRLU01 sp031258005       1.0    2.127660              1.0
JAIRMT01 sp031258505       1.0    2.127660              1.0
JAISFT01 sp031258225       1.0    2.127660              1.0
JAISFT01 sp031258265       1.0    2.127660              1.0
WQXQ01 sp031257385         1.0    2.127660              1.0
TOTAL                     47.0  100.000000             57.0

### Relative abundance

In [17]:
mq_relative_abund_df = get_relative_abund_taxo_levels(mq_df, coverage_df)

Unmapped reads: 98.15 ± 0.83, Median: 98.43, IQR: 98.17-98.58, Range: 95.19-98.69
Mapped reads: 1.85 ± 0.83, Median: 1.57, IQR: 1.42-1.83, Range: 1.31-4.81

Level: Family

              count   mean           std    min    25%    50%    75%    max
Family
unclassified   28.0  100.0  6.699061e-15  100.0  100.0  100.0  100.0  100.0

Level: Genus

              count   mean           std    min    25%    50%    75%    max
Genus
unclassified   28.0  100.0  6.699061e-15  100.0  100.0  100.0  100.0  100.0

Level: Species

,count,mean,std,min,25%,50%,75%,max
Species,,,,,,,,
unclassified,28.0,74.175267,12.552774,56.636639,64.610457,69.586530,86.342518,96.360377
Wolbachia sp000829315,28.0,15.922415,11.347475,0.634103,5.848744,17.984987,25.334043,32.510285
Truepera radiovictrix,28.0,8.894695,6.335598,0.200635,4.766720,8.346481,10.791468,33.594620
JAIRMT01 sp031258505,28.0,0.411708,1.511784,0.000000,0.000000,0.000000,0.000000,5.830742
JAIRLU01 sp031258005,28.0,0.278736,1.230721,0.000000,0.000000,0.000000,0.000000,6.413844
WQXQ01 sp031257385,28.0,0.128139,0.548118,0.000000,0.000000,0.000000,0.000000,2.827135
JAISFT01 sp031258225,28.0,0.099553,0.418044,0.000000,0.000000,0.000000,0.000000,2.139067
JAISFT01 sp031258265,28.0,0.089488,0.387888,0.000000,0.000000,0.000000,0.000000,2.010260

### Functions

In [18]:
print_stats(get_bakta_annot_df(mq_df).describe())

CDSs: nan ± nan, Median: nan, IQR: nan-nan, Range: nan-nan
CRISPR arrays: nan ± nan, Median: nan, IQR: nan-nan, Range: nan-nan
gaps: nan ± nan, Median: nan, IQR: nan-nan, Range: nan-nan
hypotheticals: nan ± nan, Median: nan, IQR: nan-nan, Range: nan-nan
ncRNA regions: nan ± nan, Median: nan, IQR: nan-nan, Range: nan-nan
ncRNAs: nan ± nan, Median: nan, IQR: nan-nan, Range: nan-nan
oriCs: nan ± nan, Median: nan, IQR: nan-nan, Range: nan-nan
oriTs: nan ± nan, Median: nan, IQR: nan-nan, Range: nan-nan
oriVs: nan ± nan, Median: nan, IQR: nan-nan, Range: nan-nan
pseudogenes: nan ± nan, Median: nan, IQR: nan-nan, Range: nan-nan
rRNAs: nan ± nan, Median: nan, IQR: nan-nan, Range: nan-nan
sORFs: nan ± nan, Median: nan, IQR: nan-nan, Range: nan-nan
signal peptides: nan ± nan, Median: nan, IQR: nan-nan, Range: nan-nan
tRNAs: nan ± nan, Median: nan, IQR: nan-nan, Range: nan-nan
tmRNAs: nan ± nan, Median: nan, IQR: nan-nan, Range: nan-nan

In [19]:
get_kegg_path_df(mq_df)

Before removing rows and columns with only zeros:
Clusters: 47
KEGG modules: 341

After removing rows and columns with only zeros:
Clusters: 47
KEGG modules: 320

KEGG modules: 107.40 ± 64.67, Median: 143.00, IQR: 26.50-154.50, Range: 4.00-207.00

,"2-Oxocarboxylic acid chain extension, 2-oxoglutarate => 2-oxoadipate => 2-oxopimelate => 2-oxosuberate",3-Hydroxypropionate bi-cycle,ADP-L-glycero-D-manno-heptose biosynthesis,"Acarbose biosynthesis, sedoheptulopyranose-7P => acarbose","Acetyl-CoA pathway, CO2 => acetyl-CoA",Acylglycerol degradation,"Adenine ribonucleotide biosynthesis, IMP => ADP,ATP","Adenine ribonucleotide degradation, AMP => Urate","Arginine biosynthesis, glutamate => acetylcitrulline => arginine","Arginine biosynthesis, ornithine => arginine",...,"beta-Oxidation, acyl-CoA synthesis","beta-Oxidation, peroxisome, VLCFA","beta-Oxidation, peroxisome, tri/dihydroxycholestanoyl-CoA => choloyl/chenodeoxycholoyl-CoA",dTDP-D-angolosamine biosynthesis,dTDP-D-forosamine biosynthesis,dTDP-L-megosamine biosynthesis,dTDP-L-mycarose biosynthesis,dTDP-L-oleandrose biosynthesis,dTDP-L-olivose biosynthesis,dTDP-L-rhamnose biosynthesis
0,33.33,27.78,0.0,0.0,0.00,0.0,100.0,100.00,42.86,100.00,...,100.0,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,100.00
1,0.00,5.56,0.0,12.5,0.00,0.0,75.0,50.00,42.86,100.00,...,100.0,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,100.00
2,0.00,11.11,0.0,0.0,0.00,0.0,100.0,16.67,14.29,0.00,...,0.0,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.00
3,0.00,2.78,20.0,0.0,33.33,0.0,75.0,66.67,42.86,66.67,...,100.0,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,100.00
4,0.00,22.22,100.0,0.0,0.00,0.0,75.0,50.00,85.71,66.67,...,100.0,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,100.00
5,0.00,11.11,0.0,0.0,0.00,0.0,75.0,50.00,57.14,100.00,...,100.0,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,100.00
6,0.00,5.56,20.0,0.0,33.33,0.0,100.0,66.67,57.14,100.00,...,100.0,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,100.00
7,0.00,5.56,100.0,0.0,0.00,0.0,100.0,0.00,57.14,100.00,...,0.0,0.00,0.00,0.0,20.0,0.0,0.0,0.0,0.0,83.33
8,0.00,4.17,0.0,0.0,0.00,0.0,100.0,50.00,57.14,100.00,...,100.0,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,100.00
9,0.00,7.41,0.0,0.0,33.33,0.0,75.0,88.89,57.14,100.00,...,100.0,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.00
10,0.00,5.56,0.0,0.0,0.00,0.0,100.0,77.78,57.14,100.00,...,100.0,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,100.00
11,0.00,5.56,0.0,0.0,33.33,0.0,100.0,33.33,57.14,100.00,...,100.0,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,100.00
12,0.00,11.11,0.0,0.0,0.00,0.0,100.0,33.33,28.57,0.00,...,100.0,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,83.33
13,0.00,16.67,0.0,0.0,0.00,0.0,50.0,50.00,85.71,66.67,...,100.0,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,100.00
14,0.00,5.56,100.0,0.0,0.00,0.0,100.0,50.00,57.14,100.00,...,0.0,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,83.33
15,0.00,2.78,40.0,0.0,33.33,0.0,75.0,66.67,28.57,66.67,...,100.0,0.00,0.00,25.0,40.0,20.0,20.0,20.0,50.0,66.67
16,0.00,16.67,0.0,0.0,0.00,0.0,75.0,16.67,71.43,66.67,...,100.0,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,100.00
17,0.00,16.67,40.0,0.0,0.00,0.0,75.0,0.00,57.14,66.67,...,100.0,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,100.00
18,0.00,4.17,0.0,0.0,0.00,0.0,75.0,50.00,28.57,66.67,...,100.0,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,100.00
19,0.00,1.39,40.0,0.0,0.00,0.0,25.0,0.00,0.00,0.00,...,0.0,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.00
20,0.00,12.96,100.0,0.0,0.00,50.0,100.0,66.67,71.43,100.00,...,100.0,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,100.00
21,0.00,2.78,0.0,0.0,0.00,0.0,50.0,61.11,42.86,100.00,...,100.0,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.00
23,0.00,0.00,0.0,0.0,0.00,50.0,25.0,16.67,0.00,0.00,...,0.0,66.67,33.33,0.0,0.0,0.0,0.0,0.0,0.0,0.00
24,0.00,5.56,40.0,0.0,0.00,0.0,50.0,66.67,57.14,100.00,...,100.0,0.00,0.00,25.0,40.0,20.0,20.0,20.0,50.0,66.67
26,0.00,5.56,60.0,0.0,0.00,0.0,100.0,66.67,57.14,100.00,...,100.0,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.00
28,0.00,5.56,40.0,0.0,0.00,0.0,75.0,50.00,28.57,100.00,...,100.0,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,100.00
30,0.00,0.00,0.0,0.0,0.00,0.0,0.0,0.00,0.00,0.00,...,0.0,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.00
33,0.00,2.78,0.0,0.0,33.33,0.0,75.0,66.67,57.14,100.00,...,100.0,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,100.00
34,0.00,14.81,0.0,0.0,0.00,0.0,50.0,50.00,85.71,66.67,...,0.0,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,33.33
35,0.00,0.00,0.0,0.0,0.00,0.0,25.0,0.00,0.00,0.00,...,0.0,33.33,33.33,0.0,0.0,0.0,0.0,0.0,0.0,0.00
36,0.00,2.78,40.0,12.5,33.33,0.0,75.0,66.67,42.86,100.00,...,100.0,0.00,0.00,25.0,40.0,20.0,20.0,20.0,50.0,33.33
37,0.00,0.00,60.0,0.0,0.00,0.0,25.0,0.00,0.00,0.00,...,0.0,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.00
42,0.00,0.00,0.0,0.0,0.00,0.0,0.0,0.00,0.00,0.00,...,0.0,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.00
44,0.00,5.56,0.0,0.0,0.00,0.0,75.0,88.89,57.14,100.00,...,100.0,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.00
45,0.00,5.56,0.0,0.0,0.00,0.0,75.0,88.89,28.57,33.33,...,100.0,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,100.00
50,0.00,0.00,0.0,0.0,0.00,0.0,0.0,0.00,0.00,0.00,...,0.0,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.00
51,0.00,0.00,0.0,0.0,0.00,0.0,25.0,0.00,0.00,0.00,...,0.0,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.00
52,0.00,0.00,0.0,0.0,0.00,0.0,0.0,0.00,0.00,0.00,...,0.0,33.33,33.33,0.0,0.0,0.0,0.0,0.0,0.0,0.00
53,0.00,5.56,40.0,0.0,0.00,0.0,75.0,72.22,42.86,33.33,...,0.0,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.00
55,0.00,0.00,0.0,0.0,0.00,0.0,0.0,0.00,0.00,0.00,...,0.0,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.00
56,0.00,0.00,0.0,0.0,0.00,0.0,0.0,0.00,0.00,0.00,...,0.0,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.00
57,0.00,0.00,0.0,0.0,0.00,0.0,0.0,0.00,0.00,0.00,...,0.0,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.00
61,0.00,0.00,0.0,0.0,0.00,0.0,25.0,0.00,0.00,0.00,...,0.0,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.00
62,0.00,0.00,0.0,0.0,0.00,0.0,0.0,0.00,0.00,0.00,...,0.0,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.00
63,0.00,0.00,0.0,0.0,0.00,0.0,0.0,0.00,0.00,0.00,...,0.0,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.00
64,0.00,0.00,0.0,0.0,0.00,50.0,0.0,0.00,0.00,0.00,...,0.0,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.00
65,0.00,0.00,0.0,0.0,0.00,0.0,25.0,0.00,0.00,0.00,...,0.0,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.00

### LQ: Low-quality species-level clusters (contamination < 10% and completeness < 50%)

In [20]:
lq_df = reps_df.query("Contamination < 10 and Completeness < 50")
compute_print_stats(lq_df)

Total number: 432.0
Cluster members: 1.02 ± 0.16, Median: 1.00, IQR: 1.00-1.00, Range: 1.00-3.00
Contamination: 1.18 ± 2.31, Median: 0.01, IQR: 0.00-0.74, Range: 0.00-9.87
Completeness: 9.78 ± 9.58, Median: 6.30, IQR: 3.60-11.60, Range: 2.30-49.60
Total length: 0.77 ± 0.94, Median: 0.40, IQR: 0.25-0.88, Range: 0.05-5.93