# Explore the aeromicrobiome use case

In [1]:
from pathlib import Path
import sys

import pandas as pd
import numpy as np

sys.path.insert(0, str((Path.cwd() / "bin").resolve()))
sys.path.insert(0, str(Path.cwd().resolve()))

from helpers import (
    load_dfs,
    compute_print_stats,
    explore_species_level_clusters_all,
    compute_taxo_classification_summary,
    get_all_taxo_levels,
    get_bakta_annot_df,
    get_kegg_path_df,
    get_relative_abund_taxo_levels,
    print_stats,
)

In [2]:
data_dp = Path("../data/use-cases/cloud-microbiome/")
data_dp.exists()

data_dp_2 = Path("../data/cloud-use-case/")
data_dp_2.exists()

result_dp = Path("../results/cloud-use-case/")
result_dp.exists()

rep_fn = "reps_cloud.tsv"

metadata_df, reps_df, coverage_df = load_dfs(data_dp_2, result_dp, rep_fn)

In [3]:
metadata_df

,run_accession,Sample ID,Condition,Sampling date,Season,Sampling start,Sampling end,Sampling duration (h),Geographic origin of the air mass,Boundary layer height (min–max [average]) (m a.s.l.),Boundary layer height min (m a.s.l.),Boundary layer height max (m a.s.l.),Boundary layer height average (m a.s.l.),Position of the sampling site relative to the boundary layer,Temperature (°C),Relative humidity (%),Wind speed (m s−1),Liquid water content (LWC) (g m−3),sample_title
0,ERR9966616,20200707AIR,Clear atmosphere,07/07/2020,Summer,09:00,15:30,6.5,Northwest,1268–1834 [1626],1268,1834,1626,In,11.1,61,3.6,NaN,20200707AIR
1,ERR9966617,20200708AIR,Clear atmosphere,08/07/2020,Summer,08:35,14:40,6.1,Northwest,623–1675 [1253],623,1675,1253,In,14.2,53,3.1,NaN,20200708AIR
2,ERR9966618,20200709AIR,Clear atmosphere,09/07/2020,Summer,08:35,14:35,6.0,North,651–2377 [1487],651,2377,1487,In,20.3,48,3.4,NaN,20200709AIR
3,ERR9966619,20200922AIR,Clear atmosphere,22/09/2020,Autumn,08:51,14:46,5.9,West,665–1334 [972],665,1334,972,Out,12.4,78,1.0,NaN,20200922AIR
4,ERR9966620,20201118AIR,Clear atmosphere,18/11/2020,Autumn,09:00,14:50,5.8,West,680–1142 [870],680,1142,870,Out,14.1,41,6.4,NaN,20201118AIR
5,ERR9966621,20191002CLOUD,Cloud,02/10/2019,Autumn,14:47,17:10,2.4,Northwest,1422–1505 [1465],1422,1505,1465,In,6.5,100,3.0,NaN,20191002CLOUD
6,ERR9966622,20191022CLOUD,Cloud,22/10/2019,Autumn,10:06,16:30,6.4,South,698–957 [813],698,957,813,Out,5.7,100,8.7,NaN,20191022CLOUD
7,ERR9966623,20200311CLOUD,Cloud,11/03/2020,Winter,08:55,13:00,4.1,West,964–1145 [1060],964,1145,1060,Out,5.0,100,7.4,NaN,20200311CLOUD
8,ERR9966624,20200717CLOUD,Cloud,17/07/2020,Summer,11:45,15:00,3.3,Northwest,1271–1437 [1343],1271,1437,1343,Out,10.1,100,1.6,0.08,20200717CLOUD
9,ERR9966625,20201016CLOUD,Cloud,16/10/2020,Autumn,08:50,13:30,4.7,Norteast,917–1034 [958],917,1034,958,Out,1.1,100,1.8,0.35,20201016CLOUD
10,ERR9966626,20201028CLOUD,Cloud,28/10/2020,Autumn,09:13,15:15,6.0,West,1026–1529 [1269],1026,1529,1269,Out,5.2,100,11.0,0.23,20201028CLOUD
11,ERR9966627,20201103CLOUD,Cloud,03/11/2020,Autumn,11:00,14:30,3.5,West,1126–1593 [1390],1126,1593,1390,In,2.2,100,8.7,0.06,20201103CLOUD
12,ERR9966628,20201110CLOUD,Cloud,10/11/2020,Autumn,11:02,14:10,3.1,Southwest,691–1276 [1016],691,1276,1016,Out,5.9,100,2.5,0.07,20201110CLOUD
13,ERR9966629,20201119CLOUD,Cloud,19/11/2020,Autumn,08:54,11:47,2.8,West,1207–1234 [1215],1207,1234,1215,Out,0.3,100,7.7,0.11,20201119CLOUD

# Quality

In [ ]:
read_numbers = {
    "ERR9966616": 46.5,
    "ERR9966617": 29.6,
    "ERR9966618": 43.7,
    "ERR9966619": 41.6,
    "ERR9966620": 39.5,
    "ERR9966621": 63.8,
    "ERR9966622": 249.9,
    "ERR9966623": 58.2,
    "ERR9966624": 42.7,
    "ERR9966625": 95.8,
    "ERR9966626": 65.0,
    "ERR9966627": 54.3,
    "ERR9966628": 59.8,
    "ERR9966629": 76.6,
}
read_numbers_df = pd.DataFrame.from_dict(read_numbers, orient="index", columns=["Read numbers (M)"])
print_stats(read_numbers_df.describe())

Read numbers (M): 69.07 ± 54.75, Median: 56.25, IQR: 42.95-64.70, Range: 29.60-249.90

In [4]:
print(f"Total number of MAGs: {reps_df['Cluster members'].sum()}")
print(f"Total number of species-level clusters: {reps_df.shape[0]}")

Total number of MAGs: 230
Total number of species-level clusters: 215

In [5]:
explore_species_level_clusters_all(reps_df)

Species-level clusters with no contamination threshold
Total number: 215.0
Cluster members: 1.07 ± 0.46, Median: 1.00, IQR: 1.00-1.00, Range: 1.00-6.00
Contamination: 2.92 ± 5.33, Median: 0.01, IQR: 0.00-4.50, Range: 0.00-26.55
Completeness: 16.06 ± 20.09, Median: 6.40, IQR: 3.05-19.50, Range: 1.70-100.00
Total length: 1.89 ± 7.83, Median: 0.24, IQR: 0.09-1.11, Range: 0.05-99.18

Species-level clusters with contamination < 5%
Total number: 163.0
Cluster members: 1.04 ± 0.40, Median: 1.00, IQR: 1.00-1.00, Range: 1.00-6.00
Contamination: 0.26 ± 0.86, Median: 0.00, IQR: 0.00-0.03, Range: 0.00-4.75
Completeness: 6.74 ± 9.38, Median: 4.30, IQR: 2.65-6.50, Range: 1.70-96.10
Total length: 0.56 ± 3.42, Median: 0.13, IQR: 0.07-0.35, Range: 0.05-43.50

Species-level clusters with contamination < 10%
Total number: 186.0
Cluster members: 1.07 ± 0.49, Median: 1.00, IQR: 1.00-1.00, Range: 1.00-6.00
Contamination: 1.12 ± 2.50, Median: 0.00, IQR: 0.00-0.12, Range: 0.00-9.69
Completeness: 10.53 ± 14.29, Median: 5.20, IQR: 2.70-9.88, Range: 1.70-96.10
Total length: 0.92 ± 3.87, Median: 0.17, IQR: 0.08-0.65, Range: 0.05-43.50

# Clusters given Bowers et al / MIMAG classification

## HQ: High-quality species-level clusters (contamination < 5% and completeness > 90%)

In [6]:
hq_df = reps_df.query("Contamination < 5 and Completeness > 90")
hq_df

,MAG,Domain,Phylum,Class,Order,Family,Genus,Species,Cluster members,Completeness,...,"kegg_V/A-type ATPase, prokaryotes","kegg_Valine/isoleucine biosynthesis, pyruvate => valine / 2-oxobutanoate => isoleucine","kegg_Violacein biosynthesis, tryptophan => violacein","kegg_Xanthomonas spp. pathogenicity signature, T3SS and effectors","kegg_beta-Carotene biosynthesis, GGAP => beta-carotene",kegg_beta-Oxidation,"kegg_beta-Oxidation, acyl-CoA synthesis","kegg_beta-Oxidation, peroxisome, VLCFA","kegg_beta-Oxidation, peroxisome, tri/dihydroxycholestanoyl-CoA => choloyl/chenodeoxycholoyl-CoA",kegg_dTDP-L-rhamnose biosynthesis
1,ERR9966625_bin_1350,Bacteria,Pseudomonadota,Alphaproteobacteria,Acetobacterales,Acetobacteraceae,CAHJXG01,unclassified,1,96.1,...,NaN,100.0,NaN,2.27,16.67,100.0,100.0,33.33,NaN,83.33

In [7]:
compute_print_stats(hq_df)

Total number: 1.0
Cluster members: 1.00 ± nan, Median: 1.00, IQR: 1.00-1.00, Range: 1.00-1.00
Contamination: 3.94 ± nan, Median: 3.94, IQR: 3.94-3.94, Range: 3.94-3.94
Completeness: 96.10 ± nan, Median: 96.10, IQR: 96.10-96.10, Range: 96.10-96.10
Total length: 5.41 ± nan, Median: 5.41, IQR: 5.41-5.41, Range: 5.41-5.41

In [8]:
print(f"Total number of MAGs: {hq_df['Cluster members'].sum()}")

Total number of MAGs: 1

### Taxonomy

In [9]:
compute_taxo_classification_summary(hq_df)

,Unclassified clusters,Classified clusters,Unclassified clusters %,Classified clusters %
Domain,0,1,0.0,100.0
Phylum,0,1,0.0,100.0
Class,0,1,0.0,100.0
Order,0,1,0.0,100.0
Family,0,1,0.0,100.0
Genus,0,1,0.0,100.0
Species,1,0,100.0,0.0

In [10]:
hq_taxo_levels = get_all_taxo_levels(hq_df)

Level: Domain

          Cluster  Cluster %  Total MAG count
Domain
Bacteria      1.0      100.0              1.0
TOTAL         1.0      100.0              1.0

Level: Phylum

                Cluster  Cluster %  Total MAG count
Phylum
Pseudomonadota      1.0      100.0              1.0
TOTAL               1.0      100.0              1.0

Level: Class

                     Cluster  Cluster %  Total MAG count
Class
Alphaproteobacteria      1.0      100.0              1.0
TOTAL                    1.0      100.0              1.0

Level: Order

                 Cluster  Cluster %  Total MAG count
Order
Acetobacterales      1.0      100.0              1.0
TOTAL                1.0      100.0              1.0

Level: Family

                  Cluster  Cluster %  Total MAG count
Family
Acetobacteraceae      1.0      100.0              1.0
TOTAL                 1.0      100.0              1.0

Level: Genus

          Cluster  Cluster %  Total MAG count
Genus
CAHJXG01      1.0      100.0              1.0
TOTAL         1.0      100.0              1.0

Level: Species

              Cluster  Cluster %  Total MAG count
Species
unclassified      1.0      100.0              1.0
TOTAL             1.0      100.0              1.0

### Relative abundance

In [11]:
hq_relative_abund_df = get_relative_abund_taxo_levels(hq_df, coverage_df)

Level: Family

                  count       mean        std  min    25%    50%    75%    max
Family
Acetobacteraceae   14.0  92.857143  26.726124  0.0  100.0  100.0  100.0  100.0

Level: Genus

          count       mean        std  min    25%    50%    75%    max
Genus
CAHJXG01   14.0  92.857143  26.726124  0.0  100.0  100.0  100.0  100.0

Level: Species

              count       mean        std  min    25%    50%    75%    max
Species
unclassified   14.0  92.857143  26.726124  0.0  100.0  100.0  100.0  100.0

### Functions

In [12]:
print_stats(get_bakta_annot_df(hq_df).describe())

CDSs: 5189.00 ± nan, Median: 5189.00, IQR: 5189.00-5189.00, Range: 5189.00-5189.00
CRISPR arrays: 0.00 ± nan, Median: 0.00, IQR: 0.00-0.00, Range: 0.00-0.00
gaps: 0.00 ± nan, Median: 0.00, IQR: 0.00-0.00, Range: 0.00-0.00
hypotheticals: 3242.00 ± nan, Median: 3242.00, IQR: 3242.00-3242.00, Range: 3242.00-3242.00
ncRNA regions: 7.00 ± nan, Median: 7.00, IQR: 7.00-7.00, Range: 7.00-7.00
ncRNAs: 4.00 ± nan, Median: 4.00, IQR: 4.00-4.00, Range: 4.00-4.00
oriCs: 0.00 ± nan, Median: 0.00, IQR: 0.00-0.00, Range: 0.00-0.00
oriTs: 0.00 ± nan, Median: 0.00, IQR: 0.00-0.00, Range: 0.00-0.00
oriVs: 0.00 ± nan, Median: 0.00, IQR: 0.00-0.00, Range: 0.00-0.00
pseudogenes: 7.00 ± nan, Median: 7.00, IQR: 7.00-7.00, Range: 7.00-7.00
rRNAs: 0.00 ± nan, Median: 0.00, IQR: 0.00-0.00, Range: 0.00-0.00
sORFs: 2.00 ± nan, Median: 2.00, IQR: 2.00-2.00, Range: 2.00-2.00
signal peptides: 0.00 ± nan, Median: 0.00, IQR: 0.00-0.00, Range: 0.00-0.00
tRNAs: 47.00 ± nan, Median: 47.00, IQR: 47.00-47.00, Range: 47.00-47.00
tmRNAs: 1.00 ± nan, Median: 1.00, IQR: 1.00-1.00, Range: 1.00-1.00

In [13]:
get_kegg_path_df(hq_df)

Before removing rows and columns with only zeros:
Clusters: 1
KEGG modules: 341

After removing rows and columns with only zeros:
Clusters: 1
KEGG modules: 230

KEGG modules: 230.00 ± nan, Median: 230.00, IQR: 230.00-230.00, Range: 230.00-230.00

,3-Hydroxypropionate bi-cycle,ADP-L-glycero-D-manno-heptose biosynthesis,"Adenine ribonucleotide biosynthesis, IMP => ADP,ATP","Adenine ribonucleotide degradation, AMP => Urate",Anoxygenic photosystem II,"Arginine biosynthesis, glutamate => acetylcitrulline => arginine","Arginine biosynthesis, ornithine => arginine","Ascorbate biosynthesis, animals, glucose-1P => ascorbate","Ascorbate biosynthesis, plants, fructose-6P => ascorbate","Assimilatory nitrate reduction, nitrate => ammonia",...,"Undecaprenylphosphate alpha-L-Ara4N biosynthesis, UDP-GlcA => undecaprenyl phosphate alpha-L-Ara4N",Urea cycle,"V-type ATPase, eukaryotes","Valine/isoleucine biosynthesis, pyruvate => valine / 2-oxobutanoate => isoleucine","Xanthomonas spp. pathogenicity signature, T3SS and effectors","beta-Carotene biosynthesis, GGAP => beta-carotene",beta-Oxidation,"beta-Oxidation, acyl-CoA synthesis","beta-Oxidation, peroxisome, VLCFA",dTDP-L-rhamnose biosynthesis
1,29.17,60.0,100.0,100.0,100.0,57.14,100.0,42.86,12.5,100.0,...,25.0,80.0,7.69,100.0,2.27,16.67,100.0,100.0,33.33,83.33

### MQ: Medium-quality species-level clusters (contamination < 10% and completeness > 50%)

In [14]:
mq_df = reps_df.query("Contamination < 10 and Completeness > 50")
mq_df.iloc[:, :25]

,MAG,Domain,Phylum,Class,Order,Family,Genus,Species,Cluster members,Completeness,...,GC (%),L50,L90,Largest contig,N50,N90,Total length,Total length (>= 0 bp),Total length (>= 1000 bp),auN
1,ERR9966625_bin_1350,Bacteria,Pseudomonadota,Alphaproteobacteria,Acetobacterales,Acetobacteraceae,CAHJXG01,unclassified,1,96.1,...,64.08,551.0,1311.0,25008.0,3239.0,2517.0,5413774.0,5413774.0,5413774.0,4447.3
10,ERR9966629_bin_2487,unclassified,unclassified,unclassified,unclassified,unclassified,unclassified,unclassified,4,59.7,...,46.26,167.0,469.0,18123.0,4397.0,2068.0,2282670.0,2282670.0,2282670.0,5428.6
11,ERR9966624_bin_1915,unclassified,unclassified,unclassified,unclassified,unclassified,unclassified,unclassified,1,59.5,...,59.92,922.0,1826.0,3564.0,1247.0,1047.0,2579262.0,2579262.0,2579262.0,1269.8
16,ERR9966620_bin_1091,unclassified,unclassified,unclassified,unclassified,unclassified,unclassified,unclassified,1,57.1,...,48.00,755.0,1605.0,5119.0,1450.0,1136.0,2744751.0,2744751.0,2744751.0,1585.9
17,ERR9966627_bin_841,unclassified,unclassified,unclassified,unclassified,unclassified,unclassified,unclassified,1,56.7,...,44.53,114.0,355.0,18136.0,3542.0,1631.0,1301435.0,1301435.0,1301435.0,4491.9
18,ERR9966629_bin_15813,unclassified,unclassified,unclassified,unclassified,unclassified,unclassified,unclassified,1,56.1,...,53.21,132.0,377.0,19901.0,4227.0,1991.0,1765345.0,1765345.0,1765345.0,5283.9
19,ERR9966620_bin_1469,Bacteria,Pseudomonadota,Alphaproteobacteria,Acetobacterales,Acetobacteraceae,CAHJXG01,unclassified,6,55.9,...,51.61,5870.0,18191.0,27845.0,1894.0,1114.0,43499712.0,43499712.0,43499712.0,3020.6
20,ERR9966628_bin_3376,unclassified,unclassified,unclassified,unclassified,unclassified,unclassified,unclassified,1,55.2,...,49.80,244.0,455.0,3417.0,3118.0,2892.0,1583889.0,1583889.0,1583889.0,3114.3

ERR9966629_bin_2487: Unclassified Bacteria

ERR9966624_bin_1915:  Unclassified Archaea

ERR9966620_bin_1091:  Unclassified Bacteria

ERR9966627_bin_841: Unclassified

ERR9966629_bin_15813: Unclassified

ERR9966628_bin_3376: Unclassified

In [15]:
compute_print_stats(mq_df)

Total number: 8.0
Cluster members: 2.00 ± 1.93, Median: 1.00, IQR: 1.00-1.75, Range: 1.00-6.00
Contamination: 7.13 ± 2.27, Median: 7.85, IQR: 5.82-8.73, Range: 3.73-9.69
Completeness: 62.04 ± 13.86, Median: 56.90, IQR: 56.05-59.55, Range: 55.20-96.10
Total length: 7.65 ± 14.54, Median: 2.43, IQR: 1.72-3.41, Range: 1.30-43.50

In [16]:
print(f"Total number of MAGs: {mq_df['Cluster members'].sum()}")

Total number of MAGs: 16

### Taxonomy

In [17]:
compute_taxo_classification_summary(mq_df)

,Unclassified clusters,Classified clusters,Unclassified clusters %,Classified clusters %
Domain,6,2,75.0,25.0
Phylum,6,2,75.0,25.0
Class,6,2,75.0,25.0
Order,6,2,75.0,25.0
Family,6,2,75.0,25.0
Genus,6,2,75.0,25.0
Species,8,0,100.0,0.0

In [18]:
mq_taxo_levels = get_all_taxo_levels(mq_df)

Level: Domain

              Cluster  Cluster %  Total MAG count
Domain
unclassified      6.0       75.0              9.0
Bacteria          2.0       25.0              7.0
TOTAL             8.0      100.0             16.0

Level: Phylum

                Cluster  Cluster %  Total MAG count
Phylum
unclassified        6.0       75.0              9.0
Pseudomonadota      2.0       25.0              7.0
TOTAL               8.0      100.0             16.0

Level: Class

                     Cluster  Cluster %  Total MAG count
Class
unclassified             6.0       75.0              9.0
Alphaproteobacteria      2.0       25.0              7.0
TOTAL                    8.0      100.0             16.0

Level: Order

                 Cluster  Cluster %  Total MAG count
Order
unclassified         6.0       75.0              9.0
Acetobacterales      2.0       25.0              7.0
TOTAL                8.0      100.0             16.0

Level: Family

                  Cluster  Cluster %  Total MAG count
Family
unclassified          6.0       75.0              9.0
Acetobacteraceae      2.0       25.0              7.0
TOTAL                 8.0      100.0             16.0

Level: Genus

              Cluster  Cluster %  Total MAG count
Genus
unclassified      6.0       75.0              9.0
CAHJXG01          2.0       25.0              7.0
TOTAL             8.0      100.0             16.0

Level: Species

              Cluster  Cluster %  Total MAG count
Species
unclassified      8.0      100.0             16.0
TOTAL             8.0      100.0             16.0

### Relative abundance

In [19]:
mq_relative_abund_df = get_relative_abund_taxo_levels(mq_df, coverage_df)

Level: Family

,count,mean,std,min,25%,50%,75%,max
Family,,,,,,,,
unclassified,14.0,68.223169,37.455606,0.0,76.105590,85.218047,88.416510,97.79188
Acetobacteraceae,14.0,24.633974,32.674469,0.0,9.467131,12.756283,20.737445,100.00000

Level: Genus

,count,mean,std,min,25%,50%,75%,max
Genus,,,,,,,,
unclassified,14.0,68.223169,37.455606,0.0,76.105590,85.218047,88.416510,97.79188
CAHJXG01,14.0,24.633974,32.674469,0.0,9.467131,12.756283,20.737445,100.00000

Level: Species

              count       mean        std  min    25%    50%    75%    max
Species
unclassified   14.0  92.857143  26.726124  0.0  100.0  100.0  100.0  100.0

In [20]:
mq_relative_abund_df

,,,ERR9966616,ERR9966617,ERR9966618,ERR9966619,ERR9966620,ERR9966621,ERR9966622,ERR9966623,ERR9966624,ERR9966625,ERR9966626,ERR9966627,ERR9966628,ERR9966629
Family,Genus,Species,,,,,,,,,,,,,,
Acetobacteraceae,CAHJXG01,unclassified,100.0,NaN,100.0,2.20812,21.624311,16.529524,18.076845,11.437973,4.004964,24.65111,13.034381,12.020041,12.478184,8.810184
unclassified,unclassified,unclassified,0.0,NaN,0.0,97.79188,78.375689,83.470476,81.923155,88.562027,95.995036,75.34889,86.965619,87.979959,87.521816,91.189816

### Functions

In [21]:
mq_bakta_annot = get_bakta_annot_df(mq_df)
mq_bakta_annot

,CDSs,CRISPR arrays,gaps,hypotheticals,ncRNA regions,ncRNAs,oriCs,oriTs,oriVs,pseudogenes,rRNAs,sORFs,signal peptides,tRNAs,tmRNAs
1,5189,0,0,3242,7,4,0,0,0,7,0,2,0,47,1
10,2097,0,0,2079,0,0,0,0,0,1,16,0,0,37,0
11,4344,0,0,4342,0,0,0,0,0,0,0,0,0,14,0
16,4949,0,0,4945,0,0,0,0,0,0,0,0,0,12,0
17,1433,1,0,1429,0,0,0,0,0,0,8,0,0,13,0
18,1722,0,0,1713,0,1,1,1,0,1,13,0,0,19,0
19,73538,0,0,72226,5,2,0,0,0,21,21,1,0,226,0
20,2726,0,0,2724,0,0,0,0,0,0,0,0,0,5,0

In [22]:
print_stats(mq_bakta_annot.describe())

CDSs: 11999.75 ± 24908.46, Median: 3535.00, IQR: 2003.25-5009.00, Range: 1433.00-73538.00
CRISPR arrays: 0.12 ± 0.35, Median: 0.00, IQR: 0.00-0.00, Range: 0.00-1.00
gaps: 0.00 ± 0.00, Median: 0.00, IQR: 0.00-0.00, Range: 0.00-0.00
hypotheticals: 11587.50 ± 24532.69, Median: 2983.00, IQR: 1987.50-4492.75, Range: 1429.00-72226.00
ncRNA regions: 1.50 ± 2.83, Median: 0.00, IQR: 0.00-1.25, Range: 0.00-7.00
ncRNAs: 0.88 ± 1.46, Median: 0.00, IQR: 0.00-1.25, Range: 0.00-4.00
oriCs: 0.12 ± 0.35, Median: 0.00, IQR: 0.00-0.00, Range: 0.00-1.00
oriTs: 0.12 ± 0.35, Median: 0.00, IQR: 0.00-0.00, Range: 0.00-1.00
oriVs: 0.00 ± 0.00, Median: 0.00, IQR: 0.00-0.00, Range: 0.00-0.00
pseudogenes: 3.75 ± 7.36, Median: 0.50, IQR: 0.00-2.50, Range: 0.00-21.00
rRNAs: 7.25 ± 8.53, Median: 4.00, IQR: 0.00-13.75, Range: 0.00-21.00
sORFs: 0.38 ± 0.74, Median: 0.00, IQR: 0.00-0.25, Range: 0.00-2.00
signal peptides: 0.00 ± 0.00, Median: 0.00, IQR: 0.00-0.00, Range: 0.00-0.00
tRNAs: 46.62 ± 73.83, Median: 16.50, IQR: 12.75-39.50, Range: 5.00-226.00
tmRNAs: 0.12 ± 0.35, Median: 0.00, IQR: 0.00-0.00, Range: 0.00-1.00

In [23]:
get_kegg_path_df(mq_df)

Before removing rows and columns with only zeros:
Clusters: 8
KEGG modules: 341

After removing rows and columns with only zeros:
Clusters: 8
KEGG modules: 290

KEGG modules: 91.88 ± 104.41, Median: 54.50, IQR: 12.50-125.75, Range: 8.00-275.00

,3-Hydroxypropionate bi-cycle,ADP-L-glycero-D-manno-heptose biosynthesis,Acylglycerol degradation,"Adenine ribonucleotide biosynthesis, IMP => ADP,ATP","Adenine ribonucleotide degradation, AMP => Urate","Aflatoxin biosynthesis, malonyl-CoA => aflatoxin B1","Anammox, nitrite + ammonia => nitrogen",Anoxygenic photosystem II,"Anthranilate degradation, anthranilate => catechol","Arginine biosynthesis, glutamate => acetylcitrulline => arginine",...,Urea cycle,"V-type ATPase, eukaryotes","Valine/isoleucine biosynthesis, pyruvate => valine / 2-oxobutanoate => isoleucine","Xanthomonas spp. pathogenicity signature, T3SS and effectors","beta-Carotene biosynthesis, GGAP => beta-carotene",beta-Oxidation,"beta-Oxidation, acyl-CoA synthesis","beta-Oxidation, peroxisome, VLCFA","beta-Oxidation, peroxisome, tri/dihydroxycholestanoyl-CoA => choloyl/chenodeoxycholoyl-CoA",dTDP-L-rhamnose biosynthesis
1,29.17,60.0,0.0,100.0,100.00,0.00,0.00,100.0,0.0,57.14,...,80.0,7.69,100.0,2.27,16.67,100.00,100.0,33.33,0.00,83.33
10,0.00,0.0,0.0,0.0,0.00,0.00,0.00,0.0,0.0,0.00,...,0.0,0.00,0.0,0.00,0.00,0.00,0.0,0.00,0.00,0.00
11,0.00,0.0,50.0,25.0,16.67,0.00,0.00,0.0,0.0,0.00,...,40.0,15.38,50.0,0.00,0.00,16.67,0.0,0.00,0.00,0.00
16,0.00,0.0,50.0,25.0,0.00,0.00,0.00,0.0,0.0,0.00,...,0.0,7.69,25.0,0.00,0.00,33.33,100.0,33.33,0.00,0.00
17,0.00,0.0,0.0,0.0,0.00,0.00,0.00,0.0,0.0,0.00,...,0.0,0.00,0.0,0.00,0.00,0.00,0.0,0.00,0.00,0.00
18,0.00,0.0,0.0,0.0,0.00,0.00,0.00,0.0,0.0,0.00,...,0.0,0.00,0.0,0.00,0.00,0.00,0.0,0.00,0.00,0.00
19,26.39,60.0,50.0,75.0,66.67,7.14,33.33,100.0,25.0,57.14,...,60.0,76.92,100.0,0.00,33.33,100.00,100.0,66.67,33.33,100.00
20,0.00,0.0,0.0,0.0,0.00,0.00,0.00,0.0,0.0,0.00,...,0.0,0.00,12.5,0.00,0.00,0.00,0.0,0.00,0.00,16.67

In [24]:
kegg_path_df = get_kegg_path_df(mq_df)

Before removing rows and columns with only zeros:
Clusters: 8
KEGG modules: 341

After removing rows and columns with only zeros:
Clusters: 8
KEGG modules: 290

KEGG modules: 91.88 ± 104.41, Median: 54.50, IQR: 12.50-125.75, Range: 8.00-275.00

### LQ: Low-quality species-level clusters (contamination < 10% and completeness < 50%)

In [25]:
lq_df = reps_df.query("Contamination < 10 and Completeness < 50")
compute_print_stats(lq_df)

Total number: 178.0
Cluster members: 1.03 ± 0.25, Median: 1.00, IQR: 1.00-1.00, Range: 1.00-4.00
Contamination: 0.85 ± 2.16, Median: 0.00, IQR: 0.00-0.09, Range: 0.00-9.57
Completeness: 8.21 ± 8.98, Median: 4.80, IQR: 2.70-8.45, Range: 1.70-42.50
Total length: 0.62 ± 2.27, Median: 0.15, IQR: 0.08-0.58, Range: 0.05-28.08

### Taxonomy

In [26]:
compute_taxo_classification_summary(lq_df)

,Unclassified clusters,Classified clusters,Unclassified clusters %,Classified clusters %
Domain,176,2,98.88,1.12
Phylum,176,2,98.88,1.12
Class,176,2,98.88,1.12
Order,176,2,98.88,1.12
Family,176,2,98.88,1.12
Genus,176,2,98.88,1.12
Species,176,2,98.88,1.12

In [27]:
lq_taxo_levels = get_all_taxo_levels(lq_df)

Level: Domain

              Cluster   Cluster %  Total MAG count
Domain
unclassified    176.0   98.876404            181.0
Bacteria          2.0    1.123596              2.0
TOTAL           178.0  100.000000            183.0

Level: Phylum

                Cluster   Cluster %  Total MAG count
Phylum
unclassified      176.0   98.876404            181.0
Actinomycetota      1.0    0.561798              1.0
Pseudomonadota      1.0    0.561798              1.0
TOTAL             178.0  100.000000            183.0

Level: Class

                     Cluster   Cluster %  Total MAG count
Class
unclassified           176.0   98.876404            181.0
Actinomycetes            1.0    0.561798              1.0
Alphaproteobacteria      1.0    0.561798              1.0
TOTAL                  178.0  100.000000            183.0

Level: Order

                 Cluster   Cluster %  Total MAG count
Order
unclassified       176.0   98.876404            181.0
Acetobacterales      1.0    0.561798              1.0
Mycobacteriales      1.0    0.561798              1.0
TOTAL              178.0  100.000000            183.0

Level: Family

                  Cluster   Cluster %  Total MAG count
Family
unclassified        176.0   98.876404            181.0
Acetobacteraceae      1.0    0.561798              1.0
Mycobacteriaceae      1.0    0.561798              1.0
TOTAL               178.0  100.000000            183.0

Level: Genus

               Cluster   Cluster %  Total MAG count
Genus
unclassified     176.0   98.876404            181.0
Mycobacterium      1.0    0.561798              1.0
Roseomonas         1.0    0.561798              1.0
TOTAL            178.0  100.000000            183.0

Level: Species

                           Cluster   Cluster %  Total MAG count
Species
unclassified                 176.0   98.876404            181.0
Mycobacterium sp002013775      1.0    0.561798              1.0
Roseomonas mucosa              1.0    0.561798              1.0
TOTAL                        178.0  100.000000            183.0

### Relative abundance

In [28]:
lq_relative_abund_df = get_relative_abund_taxo_levels(lq_df, coverage_df)

Level: Family

,count,mean,std,min,25%,50%,75%,max
Family,,,,,,,,
unclassified,14.0,99.953125,0.113666,99.645077,100.0,100.0,100.0,100.000000
Acetobacteraceae,14.0,0.027760,0.094592,0.000000,0.0,0.0,0.0,0.354923
Mycobacteriaceae,14.0,0.019115,0.071521,0.000000,0.0,0.0,0.0,0.267609

Level: Genus

,count,mean,std,min,25%,50%,75%,max
Genus,,,,,,,,
unclassified,14.0,99.953125,0.113666,99.645077,100.0,100.0,100.0,100.000000
Roseomonas,14.0,0.027760,0.094592,0.000000,0.0,0.0,0.0,0.354923
Mycobacterium,14.0,0.019115,0.071521,0.000000,0.0,0.0,0.0,0.267609

Level: Species

,count,mean,std,min,25%,50%,75%,max
Species,,,,,,,,
unclassified,14.0,99.953125,0.113666,99.645077,100.0,100.0,100.0,100.000000
Roseomonas mucosa,14.0,0.027760,0.094592,0.000000,0.0,0.0,0.0,0.354923
Mycobacterium sp002013775,14.0,0.019115,0.071521,0.000000,0.0,0.0,0.0,0.267609

### Functions

In [29]:
print_stats(get_bakta_annot_df(lq_df).describe())

CDSs: 920.07 ± 3699.33, Median: 166.50, IQR: 67.00-866.00, Range: 2.00-46384.00
CRISPR arrays: 0.01 ± 0.11, Median: 0.00, IQR: 0.00-0.00, Range: 0.00-1.00
gaps: 0.00 ± 0.00, Median: 0.00, IQR: 0.00-0.00, Range: 0.00-0.00
hypotheticals: 902.20 ± 3664.99, Median: 159.00, IQR: 64.50-791.25, Range: 2.00-45905.00
ncRNA regions: 0.10 ± 0.71, Median: 0.00, IQR: 0.00-0.00, Range: 0.00-6.00
ncRNAs: 0.07 ± 0.56, Median: 0.00, IQR: 0.00-0.00, Range: 0.00-6.00
oriCs: 0.00 ± 0.00, Median: 0.00, IQR: 0.00-0.00, Range: 0.00-0.00
oriTs: 0.00 ± 0.00, Median: 0.00, IQR: 0.00-0.00, Range: 0.00-0.00
oriVs: 0.00 ± 0.00, Median: 0.00, IQR: 0.00-0.00, Range: 0.00-0.00
pseudogenes: 0.67 ± 2.58, Median: 0.00, IQR: 0.00-0.00, Range: 0.00-26.00
rRNAs: 0.57 ± 1.97, Median: 0.00, IQR: 0.00-0.00, Range: 0.00-16.00
sORFs: 0.03 ± 0.22, Median: 0.00, IQR: 0.00-0.00, Range: 0.00-2.00
signal peptides: 0.00 ± 0.00, Median: 0.00, IQR: 0.00-0.00, Range: 0.00-0.00
tRNAs: 3.93 ± 9.13, Median: 0.50, IQR: 0.00-3.75, Range: 0.00-80.00
tmRNAs: 0.00 ± 0.00, Median: 0.00, IQR: 0.00-0.00, Range: 0.00-0.00

In [30]:
get_kegg_path_df(lq_df)

Before removing rows and columns with only zeros:
Clusters: 178
KEGG modules: 341

After removing rows and columns with only zeros:
Clusters: 146
KEGG modules: 309

KEGG modules: 19.88 ± 33.44, Median: 7.50, IQR: 3.00-21.00, Range: 1.00-238.00

,3-Hydroxypropionate bi-cycle,ADP-L-glycero-D-manno-heptose biosynthesis,"Abscisic acid biosynthesis, beta-carotene => abscisic acid",Acylglycerol degradation,"Adenine ribonucleotide biosynthesis, IMP => ADP,ATP","Adenine ribonucleotide degradation, AMP => Urate","Aflatoxin biosynthesis, malonyl-CoA => aflatoxin B1",Anoxygenic photosystem II,"Arginine biosynthesis, glutamate => acetylcitrulline => arginine","Arginine biosynthesis, ornithine => arginine",...,"V-type ATPase, eukaryotes","V/A-type ATPase, prokaryotes","Valine/isoleucine biosynthesis, pyruvate => valine / 2-oxobutanoate => isoleucine","Violacein biosynthesis, tryptophan => violacein","beta-Carotene biosynthesis, GGAP => beta-carotene",beta-Oxidation,"beta-Oxidation, acyl-CoA synthesis","beta-Oxidation, peroxisome, VLCFA","beta-Oxidation, peroxisome, tri/dihydroxycholestanoyl-CoA => choloyl/chenodeoxycholoyl-CoA",dTDP-L-rhamnose biosynthesis
29,1.39,0.0,0.0,50.0,25.0,16.67,0.00,0.0,14.29,33.33,...,7.69,0.0,37.5,0.0,0.0,66.67,100.0,66.67,0.00,0.00
30,0.00,0.0,0.0,50.0,0.0,16.67,14.29,0.0,0.00,33.33,...,0.00,0.0,25.0,0.0,0.0,0.00,0.0,0.00,0.00,0.00
31,5.56,0.0,0.0,0.0,50.0,0.00,0.00,0.0,0.00,0.00,...,15.38,0.0,50.0,0.0,0.0,0.00,0.0,0.00,0.00,0.00
32,13.89,0.0,0.0,100.0,75.0,100.00,14.29,0.0,28.57,100.00,...,30.77,0.0,100.0,0.0,0.0,83.33,100.0,66.67,33.33,50.00
34,0.00,0.0,0.0,50.0,25.0,0.00,0.00,0.0,0.00,33.33,...,15.38,0.0,50.0,0.0,0.0,16.67,100.0,0.00,0.00,16.67
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
210,0.00,0.0,0.0,0.0,0.0,0.00,0.00,0.0,0.00,0.00,...,0.00,0.0,25.0,0.0,0.0,0.00,0.0,0.00,0.00,0.00
211,0.00,0.0,0.0,0.0,0.0,0.00,0.00,0.0,0.00,0.00,...,0.00,0.0,0.0,0.0,0.0,0.00,0.0,0.00,0.00,0.00
212,0.00,0.0,0.0,0.0,0.0,0.00,0.00,0.0,0.00,0.00,...,0.00,0.0,0.0,0.0,0.0,0.00,0.0,0.00,0.00,0.00
213,0.00,0.0,0.0,0.0,0.0,0.00,0.00,0.0,0.00,0.00,...,7.69,0.0,0.0,0.0,0.0,0.00,0.0,0.00,0.00,0.00
214,0.00,0.0,0.0,0.0,0.0,0.00,0.00,0.0,0.00,0.00,...,0.00,0.0,0.0,0.0,0.0,33.33,0.0,0.00,0.00,0.00

# Cluster with completness = 100%

In [31]:
complete_df = reps_df.query("Completeness == 100")
complete_df

,MAG,Domain,Phylum,Class,Order,Family,Genus,Species,Cluster members,Completeness,...,"kegg_V/A-type ATPase, prokaryotes","kegg_Valine/isoleucine biosynthesis, pyruvate => valine / 2-oxobutanoate => isoleucine","kegg_Violacein biosynthesis, tryptophan => violacein","kegg_Xanthomonas spp. pathogenicity signature, T3SS and effectors","kegg_beta-Carotene biosynthesis, GGAP => beta-carotene",kegg_beta-Oxidation,"kegg_beta-Oxidation, acyl-CoA synthesis","kegg_beta-Oxidation, peroxisome, VLCFA","kegg_beta-Oxidation, peroxisome, tri/dihydroxycholestanoyl-CoA => choloyl/chenodeoxycholoyl-CoA",kegg_dTDP-L-rhamnose biosynthesis
0,ERR9966624_bin_2765,unclassified,unclassified,unclassified,unclassified,unclassified,unclassified,unclassified,1,100.0,...,NaN,62.5,NaN,NaN,NaN,66.67,100.0,NaN,NaN,NaN

Unclassified Archaea