# Explore the macroalgal microbiome use case

In [1]:
from pathlib import Path
import sys

import pandas as pd
import numpy as np

sys.path.insert(0, str((Path.cwd() / "bin").resolve()))
sys.path.insert(0, str(Path.cwd().resolve()))

from helpers import (
    load_dfs,
    compute_print_stats,
    explore_species_level_clusters_all,
    compute_taxo_classification_summary,
    get_all_taxo_levels,
    get_bakta_annot_df,
    get_kegg_path_df,
    get_relative_abund_taxo_levels,
    print_stats,
)

In [2]:
data_dp = Path("../data/use-cases/marine-microbiome/")
data_dp.exists()

data_dp_2 = Path("../data/marine-use-case/")
data_dp_2.exists()

result_dp = Path("../results/marine-use-case/")
result_dp.exists()

rep_fn = "reps_marine.tsv"

metadata_df, reps_df, coverage_df = load_dfs(data_dp_2, result_dp, rep_fn)

Metadata file not found: ../data/marine-use-case/metadata.tsv

# Quality

In [3]:
print(f"Total number of MAGs: {reps_df['Cluster members'].sum()}")
print(f"Total number of species-level clusters: {reps_df.shape[0]}")

Total number of MAGs: 153
Total number of species-level clusters: 132

In [4]:
explore_species_level_clusters_all(reps_df)

Species-level clusters with no contamination threshold
Total number: 132.0
Cluster members: 15.62 ± 43.65, Median=1.00, IQR=1.00-1.16, Range=0.00-132.00
Contamination: 18.31 ± 43.14, Median=2.71, IQR=0.49-3.95, Range=0.00-132.00
Completeness: 75.92 ± 43.74, Median=91.23, IQR=76.60-97.65, Range=0.00-132.00
Total length: 2.61 ± 2.34, Median=2.92, IQR=0.93-3.67, Range=0.00-7.15

Species-level clusters with contamination < 5%
Total number: 112.0
Cluster members: 13.40 ± 36.98, Median=1.00, IQR=1.00-1.18, Range=0.00-112.00
Contamination: 13.62 ± 36.92, Median=1.19, IQR=0.35-2.02, Range=0.00-112.00
Completeness: 74.28 ± 41.43, Median=92.51, IQR=76.60-98.45, Range=0.00-112.00
Total length: 2.61 ± 2.31, Median=2.92, IQR=1.14-3.63, Range=0.00-7.15

Species-level clusters with contamination < 10%
Total number: 124.0
Cluster members: 14.73 ± 40.98, Median=1.00, IQR=1.00-1.16, Range=0.00-124.00
Contamination: 15.56 ± 40.74, Median=1.86, IQR=0.39-2.54, Range=0.00-124.00
Completeness: 75.20 ± 42.68, Median=91.75, IQR=76.60-97.90, Range=0.00-124.00
Total length: 2.62 ± 2.31, Median=2.92, IQR=1.16-3.65, Range=0.00-7.15

# Clusters given Bowers et al / MIMAG classification

## HQ: High-quality species-level clusters (contamination < 5% and completeness > 90%)

In [5]:
hq_df = reps_df.query("Contamination < 5 and Completeness > 90")
hq_df

,MAG,Domain,Phylum,Class,Order,Family,Genus,Species,Cluster members,Completeness,...,"kegg_beta-Oxidation, acyl-CoA synthesis","kegg_beta-Oxidation, peroxisome, VLCFA","kegg_beta-Oxidation, peroxisome, tri/dihydroxycholestanoyl-CoA => choloyl/chenodeoxycholoyl-CoA",kegg_dTDP-D-angolosamine biosynthesis,kegg_dTDP-D-desosamine biosynthesis,kegg_dTDP-D-forosamine biosynthesis,kegg_dTDP-D-mycaminose biosynthesis,kegg_dTDP-L-megosamine biosynthesis,kegg_dTDP-L-olivose biosynthesis,kegg_dTDP-L-rhamnose biosynthesis
0,SRR22878281.fastq_bin_1875330,Bacteria,Pseudomonadota,Gammaproteobacteria,Pseudomonadales,DSM-21967,unclassified,unclassified,1,100.0,...,100.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,50.00
1,SRR22878281.fastq_bin_2019818,Bacteria,Pseudomonadota,Alphaproteobacteria,Rhodobacterales,Rhodobacteraceae,Sulfitobacter,unclassified,1,100.0,...,100.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,SRR22878281.fastq_bin_861208,Bacteria,Pseudomonadota,Gammaproteobacteria,Pseudomonadales,Cellvibrionaceae,Marinagarivorans,Marinagarivorans sp947494095,2,100.0,...,100.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,50.00
3,SRR22878281.fastq_bin_1318659,Bacteria,Pseudomonadota,Alphaproteobacteria,Rhizobiales,Hyphomicrobiaceae,CAJQQK01,unclassified,1,100.0,...,100.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100.00
4,SRR22878283.fastq_bin_617325,Bacteria,Pseudomonadota,Gammaproteobacteria,Enterobacterales,Alteromonadaceae,Thalassotalea_F,unclassified,1,100.0,...,100.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,33.33
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
71,SRR22878281.fastq_bin_1315445,Bacteria,Bacteroidota,Bacteroidia,Flavobacteriales,Flavobacteriaceae,Olleya,Olleya sediminilitoris,1,91.5,...,100.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100.00
72,SRR22878281.fastq_bin_1633526,Bacteria,Pseudomonadota,Alphaproteobacteria,Caulobacterales,Maricaulaceae,JACOMS01,unclassified,1,90.7,...,100.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100.00
74,SRR22878283.fastq_bin_563799,Bacteria,Bacteroidota,Bacteroidia,Flavobacteriales,Flavobacteriaceae,Aquimarina,unclassified,1,90.3,...,100.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100.00
75,SRR22878283.fastq_bin_299277,Bacteria,Pseudomonadota,Alphaproteobacteria,Geminicoccales,Geminicoccaceae,unclassified,unclassified,1,90.2,...,100.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
76,SRR22878281.fastq_bin_2091047,Bacteria,Pseudomonadota,Alphaproteobacteria,Rhizobiales,Rhizobiaceae,Lentilitoribacter,Lentilitoribacter sp020628775,1,90.1,...,100.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
compute_print_stats(hq_df)

Total number: 72.0
Cluster members: 8.96 ± 23.65, Median=1.00, IQR=1.00-1.17, Range=0.00-72.00
Contamination: 9.04 ± 23.65, Median=1.06, IQR=0.17-1.56, Range=0.00-72.00
Completeness: 72.45 ± 41.07, Median=94.12, IQR=72.00-96.65, Range=0.00-100.00
Total length: 2.67 ± 2.33, Median=2.99, IQR=1.16-3.76, Range=0.00-7.15

### Taxonomy

In [7]:
compute_taxo_classification_summary(hq_df)

,Unclassified clusters,Classified clusters,Unclassified clusters %,Classified clusters %
Domain,0,72,0.0,100.0
Phylum,0,72,0.0,100.0
Class,0,72,0.0,100.0
Order,0,72,0.0,100.0
Family,0,72,0.0,100.0
Genus,10,62,13.89,86.11
Species,62,10,86.11,13.89

In [8]:
hq_taxo_levels = get_all_taxo_levels(hq_df)

Level: Domain

          Cluster  Cluster %  Total MAG count
Domain
Bacteria     72.0      100.0             84.0
TOTAL        72.0      100.0             84.0

Level: Phylum

                  Cluster   Cluster %  Total MAG count
Phylum
Pseudomonadota       43.0   59.722222             46.0
Bacteroidota         15.0   20.833333             24.0
Actinomycetota        3.0    4.166667              3.0
Cyanobacteriota       3.0    4.166667              3.0
Myxococcota_A         3.0    4.166667              3.0
Bdellovibrionota      2.0    2.777778              2.0
Acidobacteriota       1.0    1.388889              1.0
Myxococcota           1.0    1.388889              1.0
Patescibacteria       1.0    1.388889              1.0
TOTAL                72.0  100.000000             84.0

Level: Class

                     Cluster   Cluster %  Total MAG count
Class
Gammaproteobacteria     23.0   31.944444             26.0
Bacteroidia             15.0   20.833333             24.0
Alphaproteobacteria     20.0   27.777778             20.0
Acidimicrobiia           3.0    4.166667              3.0
Cyanobacteriia           3.0    4.166667              3.0
UBA9160                  3.0    4.166667              3.0
Bacteriovoracia          1.0    1.388889              1.0
Blastocatellia           1.0    1.388889              1.0
Polyangia                1.0    1.388889              1.0
Saccharimonadia          1.0    1.388889              1.0
UBA2361                  1.0    1.388889              1.0
TOTAL                   72.0  100.000000             84.0

Level: Order

                   Cluster   Cluster %  Total MAG count
Order
Flavobacteriales      13.0   18.055556             22.0
Pseudomonadales       10.0   13.888889             11.0
Sphingomonadales       6.0    8.333333              6.0
Granulosicoccales      5.0    6.944444              5.0
Caulobacterales        5.0    6.944444              5.0
Arenicellales          4.0    5.555556              4.0
Enterobacterales       3.0    4.166667              4.0
Rhizobiales            4.0    5.555556              4.0
Acidimicrobiales       3.0    4.166667              3.0
UBA9160                3.0    4.166667              3.0
Geminicoccales         3.0    4.166667              3.0
Cyanobacteriales       3.0    4.166667              3.0
Chitinophagales        2.0    2.777778              2.0
Rhodobacterales        2.0    2.777778              2.0
UBA4575                1.0    1.388889              2.0
Pyrinomonadales        1.0    1.388889              1.0
Saccharimonadales      1.0    1.388889              1.0
Bacteriovoracales      1.0    1.388889              1.0
UBA2361                1.0    1.388889              1.0
Polyangiales           1.0    1.388889              1.0
TOTAL                 72.0  100.000000             84.0

Level: Family

                    Cluster   Cluster %  Total MAG count
Family
Flavobacteriaceae      13.0   18.055556             22.0
Cellvibrionaceae        6.0    8.333333              7.0
Sphingomonadaceae       6.0    8.333333              6.0
Granulosicoccaceae      5.0    6.944444              5.0
Maricaulaceae           4.0    5.555556              4.0
Arenicellaceae          4.0    5.555556              4.0
Alteromonadaceae        3.0    4.166667              4.0
Geminicoccaceae         3.0    4.166667              3.0
SMWR01                  2.0    2.777778              2.0
UBA4575                 1.0    1.388889              2.0
Xenococcaceae           2.0    2.777778              2.0
Rhodobacteraceae        2.0    2.777778              2.0
Rhizobiaceae            2.0    2.777778              2.0
SHLQ01                  1.0    1.388889              1.0
J046                    1.0    1.388889              1.0
JAHQVX01                1.0    1.388889              1.0
Bacteriovoracaceae      1.0    1.388889              1.0
Moraxellaceae           1.0    1.388889              1.0
Polyangiaceae           1.0    1.388889              1.0
Pyrinomonadaceae        1.0    1.388889              1.0
GM7GCV1                 1.0    1.388889              1.0
CALFBO01                1.0    1.388889              1.0
UBA10347                1.0    1.388889              1.0
CALHAX01                1.0    1.388889              1.0
SZUA-35                 1.0    1.388889              1.0
Saprospiraceae          1.0    1.388889              1.0
Azotimanducaceae_A      1.0    1.388889              1.0
Spirulinaceae           1.0    1.388889              1.0
UBA4427                 1.0    1.388889              1.0
Hyphomonadaceae         1.0    1.388889              1.0
Hyphomicrobiaceae       1.0    1.388889              1.0
DSM-21967               1.0    1.388889              1.0
TOTAL                  72.0  100.000000             84.0

Level: Genus

                    Cluster   Cluster %  Total MAG count
Genus
unclassified           10.0   13.888889             10.0
Aquimarina              4.0    5.555556              5.0
Arenicella              4.0    5.555556              4.0
Marinagarivorans        2.0    2.777778              3.0
CALKXS01                1.0    1.388889              3.0
Dokdonia                1.0    1.388889              3.0
Cellulophaga            1.0    1.388889              3.0
Sphingorhabdus_B        3.0    4.166667              3.0
Parasphingorhabdus      2.0    2.777778              2.0
Granulosicoccus         2.0    2.777778              2.0
JABDMD01                1.0    1.388889              2.0
Maribacter              1.0    1.388889              2.0
Alteromonas             1.0    1.388889              2.0
CALDCK01                2.0    2.777778              2.0
CALFVT01                2.0    2.777778              2.0
Waterburya              2.0    2.777778              2.0
Lacinutrix              1.0    1.388889              2.0
CALLCD01                1.0    1.388889              1.0
CAKZTE01                1.0    1.388889              1.0
CALHAX01                1.0    1.388889              1.0
CALHVX01                1.0    1.388889              1.0
CALKXV01                1.0    1.388889              1.0
JAHQVX01                1.0    1.388889              1.0
CANLBN01                1.0    1.388889              1.0
Erythrobacter           1.0    1.388889              1.0
GCA-1730015             1.0    1.388889              1.0
CALFCE01                1.0    1.388889              1.0
JAALLB01                1.0    1.388889              1.0
JACOMS01                1.0    1.388889              1.0
GCA-2746115             1.0    1.388889              1.0
UBA10347                1.0    1.388889              1.0
JANQPX01                1.0    1.388889              1.0
Lentilitoribacter       1.0    1.388889              1.0
CALEWY01                1.0    1.388889              1.0
SHLQ01                  1.0    1.388889              1.0
Maribacter_C            1.0    1.388889              1.0
CAKZSB01                1.0    1.388889              1.0
Olleya                  1.0    1.388889              1.0
CAKZJW01                1.0    1.388889              1.0
Pseudoalteromonas       1.0    1.388889              1.0
Psychrobacter           1.0    1.388889              1.0
SZUA-265                1.0    1.388889              1.0
CAJQQK01                1.0    1.388889              1.0
Sulfitobacter           1.0    1.388889              1.0
Thalassotalea_F         1.0    1.388889              1.0
UBA4427                 1.0    1.388889              1.0
Aridibacter             1.0    1.388889              1.0
Wenyingzhuangia         1.0    1.388889              1.0
Agarilytica             1.0    1.388889              1.0
TOTAL                  72.0  100.000000             84.0

Level: Species

                               Cluster   Cluster %  Total MAG count
Species
unclassified                      62.0   86.111111             67.0
Cellulophaga lytica                1.0    1.388889              3.0
Dokdonia sp947496725               1.0    1.388889              3.0
Lacinutrix sp000211855             1.0    1.388889              2.0
Maribacter litoralis               1.0    1.388889              2.0
Marinagarivorans sp947494095       1.0    1.388889              2.0
Lentilitoribacter sp020628775      1.0    1.388889              1.0
Marinagarivorans algicola          1.0    1.388889              1.0
Olleya sediminilitoris             1.0    1.388889              1.0
Pseudoalteromonas atlantica        1.0    1.388889              1.0
Psychrobacter sp002377945          1.0    1.388889              1.0
TOTAL                             72.0  100.000000             84.0

### Relative abundance

In [9]:
hq_relative_abund_df = get_relative_abund_taxo_levels(hq_df, coverage_df)

Level: Family

,count,mean,std,min,25%,50%,75%,max
Family,,,,,,,,
Flavobacteriaceae,3.0,54.406818,11.972552,40.605333,50.609581,60.613829,61.307560,62.001292
Cellvibrionaceae,3.0,12.705046,15.962483,0.528488,3.669258,6.810027,18.793325,30.776623
Sphingomonadaceae,3.0,5.334757,4.721238,0.357579,3.127282,5.896986,7.823346,9.749706
Alteromonadaceae,3.0,4.940316,3.673391,2.415036,2.833274,3.251513,6.202956,9.154400
Granulosicoccaceae,3.0,2.639934,2.503232,0.325501,1.311539,2.297578,3.797151,5.296724
Maricaulaceae,3.0,2.499389,3.061324,0.251852,0.756071,1.260291,3.623157,5.986023
Arenicellaceae,3.0,2.232936,1.837160,0.272319,1.392018,2.511718,3.213245,3.914772
Xenococcaceae,3.0,1.964088,2.054110,0.000000,0.897276,1.794552,2.946132,4.097712
GM7GCV1,3.0,1.609061,2.778269,0.000000,0.005029,0.010058,2.413591,4.817124
Polyangiaceae,3.0,1.190781,2.062492,0.000000,0.000000,0.000000,1.786171,3.572342
Spirulinaceae,3.0,1.148192,1.887275,0.049681,0.058586,0.067490,1.697448,3.327406
Geminicoccaceae,3.0,1.117256,1.172840,0.110198,0.473404,0.836611,1.620785,2.404959
JAHQVX01,3.0,0.899994,1.558835,0.000000,0.000000,0.000000,1.349991,2.699981
Rhizobiaceae,3.0,0.823029,0.724160,0.262959,0.414148,0.565338,1.103064,1.640790
UBA4575,3.0,0.727793,0.771271,0.052789,0.307479,0.562170,1.065295,1.568421
Rhodobacteraceae,3.0,0.719815,1.049210,0.022900,0.116467,0.210034,1.068273,1.926512
DSM-21967,3.0,0.628211,0.967771,0.033989,0.069852,0.105715,0.925322,1.744929
Bacteriovoracaceae,3.0,0.581793,0.893752,0.017156,0.066574,0.115993,0.864111,1.612230
SMWR01,3.0,0.434528,0.752625,0.000000,0.000000,0.000000,0.651792,1.303585
J046,3.0,0.430162,0.745062,0.000000,0.000000,0.000000,0.645243,1.290485
UBA10347,3.0,0.397820,0.689044,0.000000,0.000000,0.000000,0.596730,1.193459
CALHAX01,3.0,0.372338,0.611894,0.000000,0.019235,0.038470,0.558507,1.078543
Pyrinomonadaceae,3.0,0.300326,0.520180,0.000000,0.000000,0.000000,0.450489,0.900978
SZUA-35,3.0,0.267928,0.464065,0.000000,0.000000,0.000000,0.401892,0.803784
Saprospiraceae,3.0,0.261226,0.452457,0.000000,0.000000,0.000000,0.391840,0.783679
Hyphomicrobiaceae,3.0,0.243257,0.421333,0.000000,0.000000,0.000000,0.364885,0.729770
Hyphomonadaceae,3.0,0.227332,0.356809,0.000000,0.021710,0.043420,0.340998,0.638577
SHLQ01,3.0,0.217266,0.376315,0.000000,0.000000,0.000000,0.325899,0.651797
CALFBO01,3.0,0.196278,0.339964,0.000000,0.000000,0.000000,0.294417,0.588835
Moraxellaceae,3.0,0.183857,0.318450,0.000000,0.000000,0.000000,0.275785,0.551571
UBA4427,3.0,0.151419,0.262265,0.000000,0.000000,0.000000,0.227128,0.454256
Azotimanducaceae_A,3.0,0.147055,0.200186,0.013570,0.031966,0.050363,0.213797,0.377232

Level: Genus

,count,mean,std,min,25%,50%,75%,max
Genus,,,,,,,,
Aquimarina,3.0,17.365965,27.929093,0.190145,1.252771,2.315397,25.953875,49.592353
Cellulophaga,3.0,16.315908,20.740947,0.724405,4.546157,8.367910,24.111660,39.855409
unclassified,3.0,13.440930,16.014464,3.383743,4.207206,5.030670,18.469524,31.908377
Dokdonia,3.0,6.954436,6.313209,2.198284,3.373177,4.548070,9.332511,14.116952
CALKXS01,3.0,4.460793,5.703566,0.538345,1.189359,1.840374,6.422018,11.003662
Pseudoalteromonas,3.0,2.776779,2.659802,0.396809,1.341198,2.285588,3.966765,5.647941
Sphingorhabdus_B,3.0,2.733346,2.650235,0.076912,1.411349,2.745786,4.061562,5.377339
Lacinutrix,3.0,2.563545,2.359587,0.340233,1.325751,2.311269,3.675202,5.039135
Arenicella,3.0,2.232936,1.837160,0.272319,1.392018,2.511718,3.213245,3.914772
Wenyingzhuangia,3.0,2.213353,3.653452,0.021025,0.104584,0.188142,3.309517,6.430893
Maribacter,3.0,2.192411,2.790527,0.196287,0.598088,0.999890,3.190473,5.381057
Waterburya,3.0,1.964088,2.054110,0.000000,0.897276,1.794552,2.946132,4.097712
CALFVT01,3.0,1.738411,2.920829,0.019112,0.052178,0.085244,2.598061,5.110878
GCA-2746115,3.0,1.620330,2.806494,0.000000,0.000000,0.000000,2.430495,4.860990
Marinagarivorans,3.0,1.521379,2.131242,0.077818,0.297458,0.517097,2.243160,3.969222
Erythrobacter,3.0,1.482964,2.422239,0.020431,0.084981,0.149530,2.214231,4.278931
Alteromonas,3.0,1.387362,1.331984,0.113684,0.695617,1.277551,2.024202,2.770853
SZUA-265,3.0,1.190781,2.062492,0.000000,0.000000,0.000000,1.786171,3.572342
Parasphingorhabdus,3.0,1.118447,1.742824,0.093436,0.112286,0.131136,1.630953,3.130769
Maribacter_C,3.0,1.073059,1.487700,0.161569,0.214683,0.267797,1.528805,2.789812
CANLBN01,3.0,0.924659,1.601556,0.000000,0.000000,0.000000,1.386989,2.773977
JAHQVX01,3.0,0.899994,1.558835,0.000000,0.000000,0.000000,1.349991,2.699981
Granulosicoccus,3.0,0.853538,0.802723,0.282250,0.394652,0.507054,1.139182,1.771310
Agarilytica,3.0,0.789363,1.367217,0.000000,0.000000,0.000000,1.184045,2.368089
Olleya,3.0,0.778594,0.255798,0.490098,0.679037,0.867976,0.922841,0.977707
Thalassotalea_F,3.0,0.776175,0.781484,0.015765,0.375686,0.735606,1.156379,1.577153
JABDMD01,3.0,0.727793,0.771271,0.052789,0.307479,0.562170,1.065295,1.568421
GCA-1730015,3.0,0.669298,1.122010,0.000000,0.021626,0.043251,1.003947,1.964643
CALFCE01,3.0,0.596841,1.033759,0.000000,0.000000,0.000000,0.895262,1.790524
CAKZJW01,3.0,0.581793,0.893752,0.017156,0.066574,0.115993,0.864111,1.612230
JAALLB01,3.0,0.568349,0.878327,0.052582,0.061271,0.069960,0.826232,1.582504
CAKZSB01,3.0,0.520257,0.901112,0.000000,0.000000,0.000000,0.780386,1.560772
CALKXV01,3.0,0.504303,0.775380,0.022900,0.057072,0.091244,0.745005,1.398766
JACOMS01,3.0,0.457486,0.660449,0.035040,0.076944,0.118848,0.668709,1.218571
CALDCK01,3.0,0.434528,0.752625,0.000000,0.000000,0.000000,0.651792,1.303585
UBA10347,3.0,0.397820,0.689044,0.000000,0.000000,0.000000,0.596730,1.193459
CALHAX01,3.0,0.372338,0.611894,0.000000,0.019235,0.038470,0.558507,1.078543
CAKZTE01,3.0,0.303491,0.464892,0.022608,0.035184,0.047760,0.443933,0.840105
Aridibacter,3.0,0.300326,0.520180,0.000000,0.000000,0.000000,0.450489,0.900978
JANQPX01,3.0,0.287525,0.475700,0.000000,0.012981,0.025963,0.431287,0.836611
CALEWY01,3.0,0.267928,0.464065,0.000000,0.000000,0.000000,0.401892,0.803784
Lentilitoribacter,3.0,0.254680,0.233429,0.058285,0.125642,0.192999,0.352877,0.512755
CAJQQK01,3.0,0.243257,0.421333,0.000000,0.000000,0.000000,0.364885,0.729770
CALLCD01,3.0,0.227332,0.356809,0.000000,0.021710,0.043420,0.340998,0.638577
SHLQ01,3.0,0.217266,0.376315,0.000000,0.000000,0.000000,0.325899,0.651797
Sulfitobacter,3.0,0.215512,0.276849,0.000000,0.059395,0.118790,0.323268,0.527746
Psychrobacter,3.0,0.183857,0.318450,0.000000,0.000000,0.000000,0.275785,0.551571
UBA4427,3.0,0.151419,0.262265,0.000000,0.000000,0.000000,0.227128,0.454256
CALHVX01,3.0,0.147055,0.200186,0.013570,0.031966,0.050363,0.213797,0.377232

Level: Species

,count,mean,std,min,25%,50%,75%,max
Species,,,,,,,,
unclassified,3.0,66.458411,27.039881,37.871763,53.874428,69.877093,80.751735,91.626377
Cellulophaga lytica,3.0,16.315908,20.740947,0.724405,4.546157,8.367910,24.111660,39.855409
Dokdonia sp947496725,3.0,6.954436,6.313209,2.198284,3.373177,4.548070,9.332511,14.116952
Pseudoalteromonas atlantica,3.0,2.776779,2.659802,0.396809,1.341198,2.285588,3.966765,5.647941
Lacinutrix sp000211855,3.0,2.563545,2.359587,0.340233,1.325751,2.311269,3.675202,5.039135
Maribacter litoralis,3.0,2.192411,2.790527,0.196287,0.598088,0.999890,3.190473,5.381057
Marinagarivorans sp947494095,3.0,0.931253,1.186702,0.049801,0.256593,0.463386,1.371980,2.280574
Olleya sediminilitoris,3.0,0.778594,0.255798,0.490098,0.679037,0.867976,0.922841,0.977707
Marinagarivorans algicola,3.0,0.590126,0.951435,0.028017,0.040864,0.053711,0.871180,1.688648
Lentilitoribacter sp020628775,3.0,0.254680,0.233429,0.058285,0.125642,0.192999,0.352877,0.512755
Psychrobacter sp002377945,3.0,0.183857,0.318450,0.000000,0.000000,0.000000,0.275785,0.551571

### Functions

In [10]:
print_stats(get_bakta_annot_df(hq_df).describe())

CDSs: 2665.76 ± 1898.82, Median=2945.38, IQR=1111.25-3488.52, Range=72.00-5994.00
CRISPR arrays: 9.64 ± 25.23, Median=0.15, IQR=0.00-1.61, Range=0.00-72.00
gaps: 9.00 ± 25.46, Median=0.00, IQR=0.00-0.00, Range=0.00-72.00
hypotheticals: 874.37 ± 827.32, Median=696.66, IQR=419.56-1040.53, Range=72.00-2644.00
ncRNA regions: 13.95 ± 23.74, Median=5.43, IQR=3.69-9.25, Range=1.00-72.00
ncRNAs: 19.19 ± 26.78, Median=6.33, IQR=4.50-18.66, Range=2.00-72.00
oriCs: 9.16 ± 25.40, Median=0.02, IQR=0.00-0.40, Range=0.00-72.00
oriTs: 9.00 ± 25.46, Median=0.00, IQR=0.00-0.00, Range=0.00-72.00
oriVs: 9.00 ± 25.46, Median=0.00, IQR=0.00-0.00, Range=0.00-72.00
pseudogenes: 13.70 ± 24.33, Median=4.81, IQR=1.50-10.00, Range=0.00-72.00
rRNAs: 10.55 ± 24.93, Median=1.22, IQR=0.75-3.25, Range=0.00-72.00
sORFs: 9.33 ± 25.33, Median=0.08, IQR=0.00-0.83, Range=0.00-72.00
signal peptides: 9.00 ± 25.46, Median=0.00, IQR=0.00-0.00, Range=0.00-72.00
tRNAs: 38.45 ± 20.68, Median=36.76, IQR=28.50-46.94, Range=8.83-72.00
tmRNAs: 9.66 ± 25.20, Median=0.88, IQR=0.37-1.25, Range=0.00-72.00

In [11]:
get_kegg_path_df(hq_df)

Before removing rows and columns with only zeros:
Clusters: 72
KEGG modules: 377

After removing rows and columns with only zeros:
Clusters: 72
KEGG modules: 368

,"10-membered enediyne core biosynthesis, malonyl-CoA => 3-hydroxyhexadeca-4,6,8,10,12,14-hexaenoyl-ACP => 10-membered enediyne core",3-Hydroxypropionate bi-cycle,"9-membered enediyne core biosynthesis, malonyl-CoA => 3-hydroxyhexadeca-4,6,8,10,12,14-hexaenoyl-ACP => 9-membered enediyne core",ADP-L-glycero-D-manno-heptose biosynthesis,"Abscisic acid biosynthesis, beta-carotene => abscisic acid","Acarbose biosynthesis, sedoheptulopyranose-7P => acarbose",Acylglycerol degradation,"Adenine ribonucleotide biosynthesis, IMP => ADP,ATP","Adenine ribonucleotide degradation, AMP => Urate","Aerobactin biosynthesis, lysine => aerobactin",...,beta-Oxidation,"beta-Oxidation, acyl-CoA synthesis","beta-Oxidation, peroxisome, VLCFA","beta-Oxidation, peroxisome, tri/dihydroxycholestanoyl-CoA => choloyl/chenodeoxycholoyl-CoA",dTDP-D-angolosamine biosynthesis,dTDP-D-desosamine biosynthesis,dTDP-D-forosamine biosynthesis,dTDP-L-megosamine biosynthesis,dTDP-L-olivose biosynthesis,dTDP-L-rhamnose biosynthesis
0,0.0,27.78,0.0,20.0,0.0,0.0,0.0,100.0,66.67,0.0,...,100.00,100.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,50.00
1,0.0,62.50,0.0,0.0,0.0,0.0,0.0,100.0,100.00,0.0,...,66.67,100.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00
2,0.0,11.11,0.0,80.0,0.0,0.0,0.0,100.0,66.67,0.0,...,66.67,100.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,50.00
3,0.0,52.78,0.0,0.0,0.0,0.0,0.0,100.0,77.78,0.0,...,100.00,100.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,100.00
4,0.0,11.11,0.0,80.0,0.0,0.0,0.0,100.0,66.67,0.0,...,100.00,100.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,33.33
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
71,0.0,27.78,0.0,0.0,20.0,0.0,0.0,100.0,50.00,0.0,...,50.00,100.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,100.00
72,0.0,25.00,0.0,0.0,0.0,0.0,50.0,100.0,50.00,0.0,...,100.00,100.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,100.00
74,0.0,20.83,0.0,0.0,20.0,0.0,0.0,75.0,50.00,0.0,...,50.00,100.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,100.00
75,0.0,62.50,0.0,60.0,0.0,12.5,50.0,50.0,100.00,0.0,...,100.00,100.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00
76,0.0,13.89,0.0,0.0,0.0,0.0,0.0,75.0,83.33,0.0,...,16.67,100.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00

### MQ: Medium-quality species-level clusters (contamination < 10% and completeness > 50%)

In [12]:
mq_df = reps_df.query("Contamination < 10 and Completeness > 50")
compute_print_stats(mq_df)

Total number: 124.0
Cluster members: 14.73 ± 40.98, Median=1.00, IQR=1.00-1.16, Range=0.00-124.00
Contamination: 15.56 ± 40.74, Median=1.86, IQR=0.39-2.54, Range=0.00-124.00
Completeness: 75.20 ± 42.68, Median=91.75, IQR=76.60-97.90, Range=0.00-124.00
Total length: 2.62 ± 2.31, Median=2.92, IQR=1.16-3.65, Range=0.00-7.15

### Taxonomy

In [13]:
compute_taxo_classification_summary(mq_df)

,Unclassified clusters,Classified clusters,Unclassified clusters %,Classified clusters %
Domain,0,124,0.0,100.0
Phylum,0,124,0.0,100.0
Class,0,124,0.0,100.0
Order,0,124,0.0,100.0
Family,0,124,0.0,100.0
Genus,16,108,12.9,87.1
Species,109,15,87.9,12.1

In [14]:
mq_taxo_levels = get_all_taxo_levels(mq_df)

Level: Domain

          Cluster  Cluster %  Total MAG count
Domain
Bacteria    124.0      100.0            144.0
TOTAL       124.0      100.0            144.0

Level: Phylum

                   Cluster   Cluster %  Total MAG count
Phylum
Pseudomonadota        63.0   50.806452             67.0
Bacteroidota          32.0   25.806452             46.0
Actinomycetota         7.0    5.645161              7.0
Cyanobacteriota        5.0    4.032258              5.0
Bdellovibrionota       4.0    3.225806              4.0
Myxococcota_A          4.0    3.225806              4.0
Patescibacteria        2.0    1.612903              3.0
Acidobacteriota        2.0    1.612903              2.0
Verrucomicrobiota      2.0    1.612903              2.0
Chloroflexota          1.0    0.806452              2.0
Myxococcota            1.0    0.806452              1.0
Planctomycetota        1.0    0.806452              1.0
TOTAL                124.0  100.000000            144.0

Level: Class

                     Cluster   Cluster %  Total MAG count
Class
Bacteroidia             32.0   25.806452             46.0
Gammaproteobacteria     30.0   24.193548             34.0
Alphaproteobacteria     33.0   26.612903             33.0
Acidimicrobiia           7.0    5.645161              7.0
Cyanobacteriia           5.0    4.032258              5.0
UBA9160                  4.0    3.225806              4.0
Bacteriovoracia          3.0    2.419355              3.0
Blastocatellia           2.0    1.612903              2.0
Verrucomicrobiae         2.0    1.612903              2.0
Anaerolineae             1.0    0.806452              2.0
JAEDAM01                 1.0    0.806452              2.0
Planctomycetia           1.0    0.806452              1.0
Polyangia                1.0    0.806452              1.0
Saccharimonadia          1.0    0.806452              1.0
UBA2361                  1.0    0.806452              1.0
TOTAL                  124.0  100.000000            144.0

Level: Order

                    Cluster   Cluster %  Total MAG count
Order
Flavobacteriales       28.0   22.580645             41.0
Pseudomonadales        13.0   10.483871             14.0
Caulobacterales        10.0    8.064516             10.0
Rhizobiales             8.0    6.451613              8.0
Acidimicrobiales        7.0    5.645161              7.0
Sphingomonadales        7.0    5.645161              7.0
Enterobacterales        5.0    4.032258              7.0
Granulosicoccales       6.0    4.838710              6.0
Cyanobacteriales        5.0    4.032258              5.0
Rhodobacterales         5.0    4.032258              5.0
Arenicellales           4.0    3.225806              4.0
Chitinophagales         3.0    2.419355              4.0
UBA9160                 4.0    3.225806              4.0
Bacteriovoracales       3.0    2.419355              3.0
Geminicoccales          3.0    2.419355              3.0
Pyrinomonadales         2.0    1.612903              2.0
Verrucomicrobiales      2.0    1.612903              2.0
Promineifilales         1.0    0.806452              2.0
UBA4575                 1.0    0.806452              2.0
BD1-5                   1.0    0.806452              2.0
Pirellulales            1.0    0.806452              1.0
Saccharimonadales       1.0    0.806452              1.0
Cytophagales            1.0    0.806452              1.0
UBA2361                 1.0    0.806452              1.0
UWMA-0217               1.0    0.806452              1.0
Polyangiales            1.0    0.806452              1.0
TOTAL                 124.0  100.000000            144.0

Level: Family

                    Cluster   Cluster %  Total MAG count
Family
Flavobacteriaceae      28.0   22.580645             41.0
Cellvibrionaceae        7.0    5.645161              8.0
Maricaulaceae           8.0    6.451613              8.0
Sphingomonadaceae       7.0    5.645161              7.0
Alteromonadaceae        5.0    4.032258              7.0
Granulosicoccaceae      6.0    4.838710              6.0
Rhodobacteraceae        5.0    4.032258              5.0
Rhizobiaceae            4.0    3.225806              4.0
Arenicellaceae          4.0    3.225806              4.0
Xenococcaceae           4.0    3.225806              4.0
UBA10347                3.0    2.419355              3.0
Saprospiraceae          2.0    1.612903              3.0
Bacteriovoracaceae      3.0    2.419355              3.0
Geminicoccaceae         3.0    2.419355              3.0
Promineifilaceae        1.0    0.806452              2.0
UBA6164                 1.0    0.806452              2.0
UBA4575                 1.0    0.806452              2.0
SHLQ01                  2.0    1.612903              2.0
Hyphomicrobiaceae       2.0    1.612903              2.0
DEV007                  2.0    1.612903              2.0
CALHAX01                2.0    1.612903              2.0
UBA4427                 2.0    1.612903              2.0
SZUA-35                 2.0    1.612903              2.0
Azotimanducaceae_A      2.0    1.612903              2.0
SMWR01                  2.0    1.612903              2.0
Pyrinomonadaceae        2.0    1.612903              2.0
GM7GCV1                 2.0    1.612903              2.0
Spirulinaceae           1.0    0.806452              1.0
UWMA-0217               1.0    0.806452              1.0
DSM-21967               1.0    0.806452              1.0
CALFBO01                1.0    0.806452              1.0
Polyangiaceae           1.0    0.806452              1.0
Pirellulaceae           1.0    0.806452              1.0
Parvularculaceae        1.0    0.806452              1.0
Cyclobacteriaceae       1.0    0.806452              1.0
JAHQVX01                1.0    0.806452              1.0
J046                    1.0    0.806452              1.0
Hyphomonadaceae         1.0    0.806452              1.0
Moraxellaceae           1.0    0.806452              1.0
TOTAL                 124.0  100.000000            144.0

Level: Genus

                     Cluster   Cluster %  Total MAG count
Genus
unclassified            16.0   12.903226             17.0
Aquimarina               6.0    4.838710              7.0
CALKXS01                 2.0    1.612903              5.0
Arenicella               4.0    3.225806              4.0
Marinagarivorans         3.0    2.419355              4.0
...                      ...         ...              ...
JANQPX01                 1.0    0.806452              1.0
CAKZTE01                 1.0    0.806452              1.0
CAKZUP01                 1.0    0.806452              1.0
Robiginitomaculum_A      1.0    0.806452              1.0
TOTAL                  124.0  100.000000            144.0

[73 rows x 3 columns]

Level: Species

                               Cluster   Cluster %  Total MAG count
Species
unclassified                     109.0   87.903226            120.0
Cellulophaga lytica                1.0    0.806452              3.0
Dokdonia sp947496725               1.0    0.806452              3.0
Lacinutrix sp000211855             1.0    0.806452              2.0
Maribacter litoralis               1.0    0.806452              2.0
Marinagarivorans sp947494095       1.0    0.806452              2.0
Polaribacter sp002005425           1.0    0.806452              2.0
Pseudoalteromonas marina           1.0    0.806452              2.0
Dokdonia sp000355805               1.0    0.806452              1.0
Hellea sp020629875                 1.0    0.806452              1.0
Lentilitoribacter sp020628775      1.0    0.806452              1.0
Maribacter_B vaceletii             1.0    0.806452              1.0
Marinagarivorans algicola          1.0    0.806452              1.0
Olleya sediminilitoris             1.0    0.806452              1.0
Pseudoalteromonas atlantica        1.0    0.806452              1.0
Psychrobacter sp002377945          1.0    0.806452              1.0
TOTAL                            124.0  100.000000            144.0

### Relative abundance

In [15]:
mq_relative_abund_df = get_relative_abund_taxo_levels(mq_df, coverage_df)

Level: Family

,count,mean,std,min,25%,50%,75%,max
Family,,,,,,,,
Flavobacteriaceae,3.0,52.534698,7.970125,43.759450,49.139933,54.520415,56.922322,59.324229
Cellvibrionaceae,3.0,9.681132,11.551575,0.433136,3.206958,5.980781,14.305131,22.629481
Alteromonadaceae,3.0,5.862877,4.069195,2.614367,3.580738,4.547109,7.487132,10.427156
Sphingomonadaceae,3.0,4.411065,3.811057,0.262156,2.738608,5.215059,6.485520,7.755980
Maricaulaceae,3.0,3.085988,2.629372,0.546445,1.730575,2.914705,4.355759,5.796814
Granulosicoccaceae,3.0,2.231240,1.958650,0.273384,1.251518,2.229652,3.210168,4.190684
Xenococcaceae,3.0,1.941529,2.213049,0.038660,0.727248,1.415836,2.892963,4.370091
GM7GCV1,3.0,1.892661,3.271048,0.000000,0.004122,0.008244,2.838991,5.669739
Arenicellaceae,3.0,1.755117,1.498364,0.215454,1.028452,1.841449,2.524949,3.208449
Bacteriovoracaceae,3.0,1.258772,1.171124,0.037718,0.701863,1.366008,1.869299,2.372591
Rhodobacteraceae,3.0,1.196817,1.123310,0.372191,0.557123,0.742054,1.609130,2.476205
Rhizobiaceae,3.0,1.058053,0.897161,0.215301,0.586490,0.957678,1.479429,2.001180
Saprospiraceae,3.0,0.992770,0.941063,0.021792,0.538778,1.055765,1.478259,1.900753
Geminicoccaceae,3.0,0.889741,0.927972,0.080791,0.383228,0.685665,1.294215,1.902765
Polyangiaceae,3.0,0.873013,1.512102,0.000000,0.000000,0.000000,1.309519,2.619038
Spirulinaceae,3.0,0.844527,1.381272,0.040717,0.047057,0.053397,1.246431,2.439465
SZUA-35,3.0,0.774236,0.838079,0.054979,0.314074,0.573169,1.133864,1.694558
UBA4427,3.0,0.772525,1.097372,0.044904,0.141412,0.237919,1.136335,2.034751
JAHQVX01,3.0,0.737612,1.277582,0.000000,0.000000,0.000000,1.106419,2.212837
Promineifilaceae,3.0,0.681800,0.599860,0.000000,0.458451,0.916902,1.022700,1.128499
Azotimanducaceae_A,3.0,0.651558,0.484446,0.309170,0.374411,0.439653,0.822752,1.205852
UBA10347,3.0,0.650682,1.127015,0.000000,0.000000,0.000000,0.976024,1.952047
UBA6164,3.0,0.577705,0.098429,0.477862,0.529229,0.580597,0.627627,0.674657
UBA4575,3.0,0.550794,0.559518,0.041765,0.251253,0.460741,0.805309,1.149877
DSM-21967,3.0,0.511499,0.795934,0.026891,0.052198,0.077504,0.753802,1.430100
CALHAX01,3.0,0.418142,0.681943,0.000000,0.024679,0.049359,0.627212,1.205066
SMWR01,3.0,0.356128,0.616833,0.000000,0.000000,0.000000,0.534193,1.068385
J046,3.0,0.352550,0.610634,0.000000,0.000000,0.000000,0.528825,1.057649
SHLQ01,3.0,0.344738,0.597103,0.000000,0.000000,0.000000,0.517106,1.034213
Cyclobacteriaceae,3.0,0.343484,0.594931,0.000000,0.000000,0.000000,0.515226,1.030451
Pyrinomonadaceae,3.0,0.342486,0.573126,0.000000,0.011660,0.023320,0.513729,1.004138
Hyphomicrobiaceae,3.0,0.321095,0.556153,0.000000,0.000000,0.000000,0.481643,0.963286
DEV007,3.0,0.207228,0.358929,0.000000,0.000000,0.000000,0.310842,0.621684
Hyphomonadaceae,3.0,0.185065,0.293406,0.000000,0.015916,0.031833,0.277597,0.523362
UWMA-0217,3.0,0.183423,0.317698,0.000000,0.000000,0.000000,0.275134,0.550269
CALFBO01,3.0,0.160865,0.278626,0.000000,0.000000,0.000000,0.241297,0.482594
Moraxellaceae,3.0,0.150685,0.260993,0.000000,0.000000,0.000000,0.226027,0.452054
Parvularculaceae,3.0,0.110006,0.174763,0.000000,0.009248,0.018496,0.165009,0.311522
Pirellulaceae,3.0,0.105695,0.183069,0.000000,0.000000,0.000000,0.158543,0.317085

Level: Genus

,count,mean,std,min,25%,50%,75%,max
Genus,,,,,,,,
Aquimarina,3.0,14.261016,21.664229,0.548040,1.773184,2.998327,21.117504,39.236680
Cellulophaga,3.0,13.124170,17.149387,0.573137,3.354007,6.134877,19.399687,32.664496
unclassified,3.0,12.528162,13.353631,4.501149,4.820647,5.140145,16.541668,27.943192
Dokdonia,3.0,6.024364,5.838831,1.876259,2.685877,3.495496,8.098416,12.701336
CALKXS01,3.0,4.863202,4.570993,0.475747,2.495841,4.515936,7.056930,9.597924
...,...,...,...,...,...,...,...,...
Hyella,3.0,0.170169,0.245469,0.023112,0.028481,0.033850,0.243697,0.453544
Psychrobacter,3.0,0.150685,0.260993,0.000000,0.000000,0.000000,0.226027,0.452054
CAKZUP01,3.0,0.127120,0.190880,0.000000,0.017373,0.034745,0.190680,0.346615
CALHVX01,3.0,0.118943,0.165261,0.010736,0.023830,0.036923,0.173046,0.309170
JAUIGD01,3.0,0.105381,0.182526,0.000000,0.000000,0.000000,0.158072,0.316144

Level: Species

,count,mean,std,min,25%,50%,75%,max
Species,,,,,,,,
unclassified,3.0,70.261688,23.022711,46.320085,59.272665,72.225244,82.232490,92.239735
Cellulophaga lytica,3.0,13.124170,17.149387,0.573137,3.354007,6.134877,19.399687,32.664496
Dokdonia sp947496725,3.0,5.547845,5.275887,1.739247,2.536817,3.334387,7.452144,11.569900
Pseudoalteromonas atlantica,3.0,2.109303,1.924294,0.313949,1.093580,1.873210,3.006980,4.140750
Lacinutrix sp000211855,3.0,1.952617,1.713356,0.269187,1.081722,1.894258,2.794333,3.694408
Maribacter litoralis,3.0,1.639956,2.023735,0.155299,0.487392,0.819484,2.382285,3.945086
Pseudoalteromonas marina,3.0,1.499831,1.519447,0.546760,0.623703,0.700647,1.976367,3.252087
Marinagarivorans sp947494095,3.0,0.740215,0.937418,0.036511,0.208145,0.379780,1.092067,1.804354
Polaribacter sp002005425,3.0,0.734626,0.838630,0.132733,0.255674,0.378616,1.035573,1.692530
Olleya sediminilitoris,3.0,0.608471,0.208178,0.387758,0.512054,0.636351,0.718827,0.801304
Dokdonia sp000355805,3.0,0.476518,0.567303,0.137012,0.149060,0.161108,0.646272,1.131436
Marinagarivorans algicola,3.0,0.466864,0.752813,0.020541,0.032281,0.044020,0.690026,1.336032
Maribacter_B vaceletii,3.0,0.265254,0.176854,0.061443,0.208754,0.356065,0.367160,0.378254
Hellea sp020629875,3.0,0.219337,0.122983,0.103353,0.154861,0.206368,0.277330,0.348291
Lentilitoribacter sp020628775,3.0,0.202617,0.194408,0.046114,0.093805,0.141496,0.280869,0.420241
Psychrobacter sp002377945,3.0,0.150685,0.260993,0.000000,0.000000,0.000000,0.226027,0.452054

### Functions

In [16]:
print_stats(get_bakta_annot_df(mq_df).describe())

CDSs: 2632.26 ± 1873.61, Median=2852.62, IQR=1113.58-3422.41, Range=124.00-5994.00
CRISPR arrays: 16.10 ± 43.62, Median=0.10, IQR=0.00-1.48, Range=0.00-124.00
gaps: 15.50 ± 43.84, Median=0.00, IQR=0.00-0.00, Range=0.00-124.00
hypotheticals: 949.58 ± 937.26, Median=747.35, IQR=405.81-1092.05, Range=101.00-3017.00
ncRNA regions: 20.46 ± 42.01, Median=5.89, IQR=3.72-9.25, Range=0.00-124.00
ncRNAs: 25.26 ± 43.13, Median=6.11, IQR=3.75-17.91, Range=1.00-124.00
oriCs: 15.65 ± 43.78, Median=0.02, IQR=0.00-0.38, Range=0.00-124.00
oriTs: 15.50 ± 43.84, Median=0.00, IQR=0.00-0.00, Range=0.00-124.00
oriVs: 15.50 ± 43.84, Median=0.00, IQR=0.00-0.00, Range=0.00-124.00
pseudogenes: 22.28 ± 42.11, Median=6.11, IQR=2.50-14.00, Range=0.00-124.00
rRNAs: 16.92 ± 43.33, Median=1.05, IQR=0.75-2.69, Range=0.00-124.00
sORFs: 15.83 ± 43.71, Median=0.10, IQR=0.00-0.84, Range=0.00-124.00
signal peptides: 15.50 ± 43.84, Median=0.00, IQR=0.00-0.00, Range=0.00-124.00
tRNAs: 44.13 ± 36.13, Median=34.62, IQR=25.25-46.75, Range=9.83-124.00
tmRNAs: 16.28 ± 43.54, Median=0.86, IQR=0.40-1.50, Range=0.00-124.00

In [17]:
get_kegg_path_df(mq_df)

Before removing rows and columns with only zeros:
Clusters: 124
KEGG modules: 377

After removing rows and columns with only zeros:
Clusters: 124
KEGG modules: 375

,"10-membered enediyne core biosynthesis, malonyl-CoA => 3-hydroxyhexadeca-4,6,8,10,12,14-hexaenoyl-ACP => 10-membered enediyne core","2-Oxocarboxylic acid chain extension, 2-oxoglutarate => 2-oxoadipate => 2-oxopimelate => 2-oxosuberate",3-Hydroxypropionate bi-cycle,"9-membered enediyne core biosynthesis, malonyl-CoA => 3-hydroxyhexadeca-4,6,8,10,12,14-hexaenoyl-ACP => 9-membered enediyne core",ADP-L-glycero-D-manno-heptose biosynthesis,"Abscisic acid biosynthesis, beta-carotene => abscisic acid","Acarbose biosynthesis, sedoheptulopyranose-7P => acarbose",Acylglycerol degradation,"Adenine ribonucleotide biosynthesis, IMP => ADP,ATP","Adenine ribonucleotide degradation, AMP => Urate",...,beta-Oxidation,"beta-Oxidation, acyl-CoA synthesis","beta-Oxidation, peroxisome, VLCFA","beta-Oxidation, peroxisome, tri/dihydroxycholestanoyl-CoA => choloyl/chenodeoxycholoyl-CoA",dTDP-D-angolosamine biosynthesis,dTDP-D-desosamine biosynthesis,dTDP-D-forosamine biosynthesis,dTDP-L-megosamine biosynthesis,dTDP-L-olivose biosynthesis,dTDP-L-rhamnose biosynthesis
0,0.0,0.0,27.78,0.0,20.0,0.0,0.0,0.0,100.0,66.67,...,100.00,100.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,50.00
1,0.0,0.0,62.50,0.0,0.0,0.0,0.0,0.0,100.0,100.00,...,66.67,100.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00
2,0.0,0.0,11.11,0.0,80.0,0.0,0.0,0.0,100.0,66.67,...,66.67,100.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,50.00
3,0.0,0.0,52.78,0.0,0.0,0.0,0.0,0.0,100.0,77.78,...,100.00,100.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,100.00
4,0.0,0.0,11.11,0.0,80.0,0.0,0.0,0.0,100.0,66.67,...,100.00,100.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,33.33
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
125,0.0,0.0,11.11,0.0,0.0,20.0,0.0,0.0,75.0,50.00,...,50.00,100.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,100.00
127,0.0,0.0,16.67,0.0,0.0,0.0,0.0,50.0,75.0,83.33,...,66.67,100.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,50.00
128,0.0,0.0,48.15,0.0,0.0,0.0,0.0,50.0,75.0,0.00,...,100.00,100.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,16.67
129,0.0,0.0,27.78,0.0,0.0,0.0,0.0,0.0,100.0,50.00,...,50.00,100.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,83.33
130,0.0,0.0,56.48,0.0,0.0,0.0,0.0,0.0,100.0,100.00,...,100.00,100.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,100.00

### LQ: Low-quality species-level clusters (contamination < 10% and completeness < 50%)

In [18]:
lq_df = reps_df.query("Contamination < 10 and Completeness < 50")
compute_print_stats(lq_df)

Total number: 0.0
Cluster members: 0.00 ± 0.00, Median=0.00, IQR=0.00-0.00, Range=0.00-0.00
Contamination: 0.00 ± 0.00, Median=0.00, IQR=0.00-0.00, Range=0.00-0.00
Completeness: 0.00 ± 0.00, Median=0.00, IQR=0.00-0.00, Range=0.00-0.00
Total length: 0.00 ± 0.00, Median=0.00, IQR=0.00-0.00, Range=0.00-0.00