# Explore the termite head microbiome use case

In [1]:
from pathlib import Path
import sys

import pandas as pd
import numpy as np

sys.path.insert(0, str((Path.cwd() / "bin").resolve()))
sys.path.insert(0, str(Path.cwd().resolve()))

from helpers import (
    load_dfs,
    compute_print_stats,
    explore_species_level_clusters_all,
    compute_taxo_classification_summary,
    get_all_taxo_levels,
    get_bakta_annot_df,
    get_kegg_path_df,
    get_relative_abund_taxo_levels,
    print_stats,
)

In [2]:
data_dp = Path("../data/use-cases/termite-microbiome/")
data_dp.exists()

data_dp_2 = Path("../data/termite-use-case/")
data_dp_2.exists()

result_dp = Path("../results/termite-use-case/")
result_dp.exists()

rep_fn = "reps_termite.tsv"

metadata_df, reps_df, coverage_df = load_dfs(data_dp_2, result_dp, rep_fn)

# Quality

In [3]:
print(f"Total number of MAGs: {reps_df['Cluster members'].sum()}")
print(f"Total number of species-level clusters: {reps_df.shape[0]}")

Total number of MAGs: 21
Total number of species-level clusters: 14

In [4]:
explore_species_level_clusters_all(reps_df)

Species-level clusters with no contamination threshold
Total number: 14.0
Cluster members: 1.50 ± 1.40, Median: 1.00, IQR: 1.00-1.00, Range: 1.00-6.00
Contamination: 2.86 ± 3.05, Median: 1.82, IQR: 0.57-3.84, Range: 0.13-9.97
Completeness: 88.32 ± 9.60, Median: 89.80, IQR: 81.70-96.90, Range: 72.00-100.00
Total length: 51.12 ± 178.42, Median: 2.90, IQR: 2.63-3.33, Range: 1.61-670.97

Species-level clusters with contamination < 5%
Total number: 11.0
Cluster members: 1.64 ± 1.57, Median: 1.00, IQR: 1.00-1.00, Range: 1.00-6.00
Contamination: 1.54 ± 1.37, Median: 0.92, IQR: 0.45-2.49, Range: 0.13-3.88
Completeness: 89.08 ± 9.09, Median: 91.50, IQR: 83.50-95.40, Range: 72.00-100.00
Total length: 3.60 ± 2.26, Median: 2.89, IQR: 2.68-3.21, Range: 1.61-9.85

Species-level clusters with contamination < 10%
Total number: 14.0
Cluster members: 1.50 ± 1.40, Median: 1.00, IQR: 1.00-1.00, Range: 1.00-6.00
Contamination: 2.86 ± 3.05, Median: 1.82, IQR: 0.57-3.84, Range: 0.13-9.97
Completeness: 88.32 ± 9.60, Median: 89.80, IQR: 81.70-96.90, Range: 72.00-100.00
Total length: 51.12 ± 178.42, Median: 2.90, IQR: 2.63-3.33, Range: 1.61-670.97

# Clusters given Bowers et al / MIMAG classification

## HQ: High-quality species-level clusters (contamination < 5% and completeness > 90%)

In [5]:
hq_df = reps_df.query("Contamination < 5 and Completeness > 90")
hq_df

,MAG,Domain,Phylum,Class,Order,Family,Genus,Species,Cluster members,Completeness,...,"kegg_Valine/isoleucine biosynthesis, pyruvate => valine / 2-oxobutanoate => isoleucine","kegg_Vancomycin resistance, D-Ala-D-Lac type","kegg_Vancomycin resistance, D-Ala-D-Ser type","kegg_Xanthomonas spp. pathogenicity signature, T3SS and effectors","kegg_beta-Carotene biosynthesis, GGAP => beta-carotene",kegg_beta-Oxidation,"kegg_beta-Oxidation, acyl-CoA synthesis","kegg_beta-Oxidation, peroxisome, VLCFA","kegg_beta-Oxidation, peroxisome, tri/dihydroxycholestanoyl-CoA => choloyl/chenodeoxycholoyl-CoA",kegg_dTDP-L-rhamnose biosynthesis
1,group_7_bin_7843,Bacteria,Deinococcota,Deinococci,Deinococcales,Trueperaceae,Truepera,Truepera radiovictrix,6,100.0,...,100.0,25.0,NaN,NaN,33.33,100.00,100.0,NaN,NaN,100.00
2,group_2_bin_312419,Bacteria,Margulisbacteria,Termititenacia,Termititenacales,Termititenacaceae,unclassified,unclassified,1,99.9,...,100.0,NaN,NaN,NaN,NaN,NaN,100.0,NaN,NaN,100.00
3,group_5_bin_1238,Bacteria,Pseudomonadota,Alphaproteobacteria,Rickettsiales,Anaplasmataceae,Wolbachia,Wolbachia sp000829315,3,98.4,...,25.0,NaN,NaN,1.14,NaN,NaN,NaN,NaN,NaN,NaN
4,group_2_bin_253990,Bacteria,Pseudomonadota,Gammaproteobacteria,Burkholderiales,Rhodocyclaceae,Propionivibrio,unclassified,1,92.4,...,100.0,NaN,NaN,9.09,16.67,33.33,100.0,NaN,NaN,100.00
5,group_2_bin_518144,Bacteria,Spirochaetota,Spirochaetia,Treponematales,Breznakiellaceae,JAIRRR01,unclassified,1,92.2,...,50.0,25.0,NaN,NaN,NaN,NaN,100.0,NaN,NaN,100.00
6,group_2_bin_643563,Bacteria,Bacteroidota,Bacteroidia,Bacteroidales,UBA932,JAITMY01,unclassified,1,91.5,...,100.0,NaN,NaN,NaN,NaN,NaN,100.0,NaN,NaN,66.67

In [6]:
compute_print_stats(hq_df)

Total number: 6.0
Cluster members: 2.17 ± 2.04, Median: 1.00, IQR: 1.00-2.50, Range: 1.00-6.00
Contamination: 1.18 ± 1.38, Median: 0.71, IQR: 0.44-1.14, Range: 0.13-3.88
Completeness: 95.73 ± 4.10, Median: 95.40, IQR: 92.25-99.53, Range: 91.50-100.00
Total length: 4.35 ± 2.95, Median: 3.21, IQR: 2.91-4.85, Range: 1.61-9.85

### Taxonomy

In [7]:
compute_taxo_classification_summary(hq_df)

,Unclassified clusters,Classified clusters,Unclassified clusters %,Classified clusters %
Domain,0,6,0.0,100.0
Phylum,0,6,0.0,100.0
Class,0,6,0.0,100.0
Order,0,6,0.0,100.0
Family,0,6,0.0,100.0
Genus,1,5,16.67,83.33
Species,4,2,66.67,33.33

In [8]:
hq_taxo_levels = get_all_taxo_levels(hq_df)

Level: Domain

          Cluster  Cluster %  Total MAG count
Domain
Bacteria      6.0      100.0             13.0
TOTAL         6.0      100.0             13.0

Level: Phylum

                  Cluster   Cluster %  Total MAG count
Phylum
Deinococcota          1.0   16.666667              6.0
Pseudomonadota        2.0   33.333333              4.0
Bacteroidota          1.0   16.666667              1.0
Margulisbacteria      1.0   16.666667              1.0
Spirochaetota         1.0   16.666667              1.0
TOTAL                 6.0  100.000000             13.0

Level: Class

                     Cluster   Cluster %  Total MAG count
Class
Deinococci               1.0   16.666667              6.0
Alphaproteobacteria      1.0   16.666667              3.0
Bacteroidia              1.0   16.666667              1.0
Gammaproteobacteria      1.0   16.666667              1.0
Spirochaetia             1.0   16.666667              1.0
Termititenacia           1.0   16.666667              1.0
TOTAL                    6.0  100.000000             13.0

Level: Order

                  Cluster   Cluster %  Total MAG count
Order
Deinococcales         1.0   16.666667              6.0
Rickettsiales         1.0   16.666667              3.0
Bacteroidales         1.0   16.666667              1.0
Burkholderiales       1.0   16.666667              1.0
Termititenacales      1.0   16.666667              1.0
Treponematales        1.0   16.666667              1.0
TOTAL                 6.0  100.000000             13.0

Level: Family

                   Cluster   Cluster %  Total MAG count
Family
Trueperaceae           1.0   16.666667              6.0
Anaplasmataceae        1.0   16.666667              3.0
Breznakiellaceae       1.0   16.666667              1.0
Rhodocyclaceae         1.0   16.666667              1.0
Termititenacaceae      1.0   16.666667              1.0
UBA932                 1.0   16.666667              1.0
TOTAL                  6.0  100.000000             13.0

Level: Genus

                Cluster   Cluster %  Total MAG count
Genus
Truepera            1.0   16.666667              6.0
Wolbachia           1.0   16.666667              3.0
JAIRRR01            1.0   16.666667              1.0
JAITMY01            1.0   16.666667              1.0
Propionivibrio      1.0   16.666667              1.0
unclassified        1.0   16.666667              1.0
TOTAL               6.0  100.000000             13.0

Level: Species

                       Cluster   Cluster %  Total MAG count
Species
Truepera radiovictrix      1.0   16.666667              6.0
unclassified               4.0   66.666667              4.0
Wolbachia sp000829315      1.0   16.666667              3.0
TOTAL                      6.0  100.000000             13.0

### Relative abundance

In [9]:
hq_relative_abund_df = get_relative_abund_taxo_levels(hq_df, coverage_df)

Level: Family

,count,mean,std,min,25%,50%,75%,max
Family,,,,,,,,
Anaplasmataceae,28.0,70.400731,21.745621,17.699482,68.611798,79.793750,85.576322,88.416903
Trueperaceae,28.0,26.073219,18.638669,1.586812,14.242743,19.356402,28.510878,71.844708
UBA932,28.0,1.401837,7.417822,0.000000,0.000000,0.000000,0.000000,39.251426
Breznakiellaceae,28.0,1.275454,5.127133,0.000000,0.000000,0.000000,0.000000,25.524911
Rhodocyclaceae,28.0,0.463132,1.707111,0.000000,0.000000,0.000000,0.000000,7.035747
Termititenacaceae,28.0,0.385628,1.706954,0.000000,0.000000,0.000000,0.000000,8.901622

Level: Genus

,count,mean,std,min,25%,50%,75%,max
Genus,,,,,,,,
Wolbachia,28.0,70.400731,21.745621,17.699482,68.611798,79.793750,85.576322,88.416903
Truepera,28.0,26.073219,18.638669,1.586812,14.242743,19.356402,28.510878,71.844708
JAITMY01,28.0,1.401837,7.417822,0.000000,0.000000,0.000000,0.000000,39.251426
JAIRRR01,28.0,1.275454,5.127133,0.000000,0.000000,0.000000,0.000000,25.524911
Propionivibrio,28.0,0.463132,1.707111,0.000000,0.000000,0.000000,0.000000,7.035747
unclassified,28.0,0.385628,1.706954,0.000000,0.000000,0.000000,0.000000,8.901622

Level: Species

,count,mean,std,min,25%,50%,75%,max
Species,,,,,,,,
Wolbachia sp000829315,28.0,70.400731,21.745621,17.699482,68.611798,79.793750,85.576322,88.416903
Truepera radiovictrix,28.0,26.073219,18.638669,1.586812,14.242743,19.356402,28.510878,71.844708
unclassified,28.0,3.526051,15.505248,0.000000,0.000000,0.000000,0.000000,80.713706

### Functions

In [10]:
print_stats(get_bakta_annot_df(hq_df).describe())

CDSs: 0.00 ± 0.00, Median: 0.00, IQR: 0.00-0.00, Range: 0.00-0.00
CRISPR arrays: 0.00 ± 0.00, Median: 0.00, IQR: 0.00-0.00, Range: 0.00-0.00
gaps: 0.00 ± 0.00, Median: 0.00, IQR: 0.00-0.00, Range: 0.00-0.00
hypotheticals: 0.00 ± 0.00, Median: 0.00, IQR: 0.00-0.00, Range: 0.00-0.00
ncRNA regions: 0.00 ± 0.00, Median: 0.00, IQR: 0.00-0.00, Range: 0.00-0.00
ncRNAs: 0.00 ± 0.00, Median: 0.00, IQR: 0.00-0.00, Range: 0.00-0.00
oriCs: 0.00 ± 0.00, Median: 0.00, IQR: 0.00-0.00, Range: 0.00-0.00
oriTs: 0.00 ± 0.00, Median: 0.00, IQR: 0.00-0.00, Range: 0.00-0.00
oriVs: 0.00 ± 0.00, Median: 0.00, IQR: 0.00-0.00, Range: 0.00-0.00
pseudogenes: 0.00 ± 0.00, Median: 0.00, IQR: 0.00-0.00, Range: 0.00-0.00
rRNAs: 1.67 ± 2.42, Median: 0.50, IQR: 0.00-2.50, Range: 0.00-6.00
sORFs: 0.00 ± 0.00, Median: 0.00, IQR: 0.00-0.00, Range: 0.00-0.00
signal peptides: 0.00 ± 0.00, Median: 0.00, IQR: 0.00-0.00, Range: 0.00-0.00
tRNAs: 0.00 ± 0.00, Median: 0.00, IQR: 0.00-0.00, Range: 0.00-0.00
tmRNAs: 0.00 ± 0.00, Median: 0.00, IQR: 0.00-0.00, Range: 0.00-0.00

In [11]:
get_kegg_path_df(hq_df)

Before removing rows and columns with only zeros:
Clusters: 6
KEGG modules: 314

After removing rows and columns with only zeros:
Clusters: 6
KEGG modules: 258

KEGG modules: 162.50 ± 26.63, Median: 161.00, IQR: 152.00-172.25, Range: 124.00-204.00

,"2-Oxocarboxylic acid chain extension, 2-oxoglutarate => 2-oxoadipate => 2-oxopimelate => 2-oxosuberate",3-Hydroxypropionate bi-cycle,ADP-L-glycero-D-manno-heptose biosynthesis,"Acarbose biosynthesis, sedoheptulopyranose-7P => acarbose","Acetyl-CoA pathway, CO2 => acetyl-CoA","Adenine ribonucleotide biosynthesis, IMP => ADP,ATP","Adenine ribonucleotide degradation, AMP => Urate","Arginine biosynthesis, glutamate => acetylcitrulline => arginine","Arginine biosynthesis, ornithine => arginine","Ascorbate biosynthesis, animals, glucose-1P => ascorbate",...,Urea cycle,"V/A-type ATPase, prokaryotes","Validamycin A biosynthesis, sedoheptulopyranose-7P => validamycin A","Valine/isoleucine biosynthesis, pyruvate => valine / 2-oxobutanoate => isoleucine","Vancomycin resistance, D-Ala-D-Lac type","Xanthomonas spp. pathogenicity signature, T3SS and effectors","beta-Carotene biosynthesis, GGAP => beta-carotene",beta-Oxidation,"beta-Oxidation, acyl-CoA synthesis",dTDP-L-rhamnose biosynthesis
1,33.33,27.78,0.0,0.0,0.00,100.0,100.00,28.57,66.67,28.57,...,60.0,88.89,0.00,100.0,25.0,0.00,33.33,100.00,100.0,100.00
2,0.00,5.56,0.0,12.5,0.00,75.0,50.00,42.86,100.00,28.57,...,60.0,77.78,11.11,100.0,0.0,0.00,0.00,0.00,100.0,100.00
3,0.00,11.11,0.0,0.0,0.00,75.0,16.67,14.29,0.00,14.29,...,0.0,0.00,0.00,25.0,0.0,1.14,0.00,0.00,0.0,0.00
4,0.00,5.56,100.0,0.0,0.00,75.0,33.33,71.43,100.00,14.29,...,60.0,0.00,0.00,100.0,0.0,9.09,16.67,33.33,100.0,100.00
5,0.00,2.78,20.0,0.0,33.33,50.0,66.67,14.29,33.33,28.57,...,20.0,77.78,0.00,50.0,25.0,0.00,0.00,0.00,100.0,100.00
6,0.00,22.22,80.0,0.0,0.00,75.0,16.67,85.71,66.67,28.57,...,40.0,0.00,0.00,100.0,0.0,0.00,0.00,0.00,100.0,66.67

### MQ: Medium-quality species-level clusters (contamination < 10% and completeness > 50%)

In [12]:
mq_df = reps_df.query("Contamination < 10 and Completeness > 50")
compute_print_stats(mq_df)

Total number: 14.0
Cluster members: 1.50 ± 1.40, Median: 1.00, IQR: 1.00-1.00, Range: 1.00-6.00
Contamination: 2.86 ± 3.05, Median: 1.82, IQR: 0.57-3.84, Range: 0.13-9.97
Completeness: 88.32 ± 9.60, Median: 89.80, IQR: 81.70-96.90, Range: 72.00-100.00
Total length: 51.12 ± 178.42, Median: 2.90, IQR: 2.63-3.33, Range: 1.61-670.97

### Taxonomy

In [13]:
compute_taxo_classification_summary(mq_df)

,Unclassified clusters,Classified clusters,Unclassified clusters %,Classified clusters %
Domain,1,13,7.14,92.86
Phylum,1,13,7.14,92.86
Class,1,13,7.14,92.86
Order,1,13,7.14,92.86
Family,1,13,7.14,92.86
Genus,2,12,14.29,85.71
Species,9,5,64.29,35.71

In [14]:
mq_taxo_levels = get_all_taxo_levels(mq_df)

Level: Domain

              Cluster   Cluster %  Total MAG count
Domain
Bacteria         13.0   92.857143             20.0
unclassified      1.0    7.142857              1.0
TOTAL            14.0  100.000000             21.0

Level: Phylum

                  Cluster   Cluster %  Total MAG count
Phylum
Spirochaetota         6.0   42.857143              6.0
Deinococcota          1.0    7.142857              6.0
Pseudomonadota        2.0   14.285714              4.0
Bacteroidota          3.0   21.428571              3.0
Margulisbacteria      1.0    7.142857              1.0
unclassified          1.0    7.142857              1.0
TOTAL                14.0  100.000000             21.0

Level: Class

                     Cluster   Cluster %  Total MAG count
Class
Spirochaetia             6.0   42.857143              6.0
Deinococci               1.0    7.142857              6.0
Bacteroidia              3.0   21.428571              3.0
Alphaproteobacteria      1.0    7.142857              3.0
Gammaproteobacteria      1.0    7.142857              1.0
Termititenacia           1.0    7.142857              1.0
unclassified             1.0    7.142857              1.0
TOTAL                   14.0  100.000000             21.0

Level: Order

                  Cluster   Cluster %  Total MAG count
Order
Treponematales        6.0   42.857143              6.0
Deinococcales         1.0    7.142857              6.0
Bacteroidales         3.0   21.428571              3.0
Rickettsiales         1.0    7.142857              3.0
Burkholderiales       1.0    7.142857              1.0
Termititenacales      1.0    7.142857              1.0
unclassified          1.0    7.142857              1.0
TOTAL                14.0  100.000000             21.0

Level: Family

                   Cluster   Cluster %  Total MAG count
Family
Breznakiellaceae       6.0   42.857143              6.0
Trueperaceae           1.0    7.142857              6.0
Anaplasmataceae        1.0    7.142857              3.0
Azobacteroidaceae      1.0    7.142857              1.0
Marinifilaceae         1.0    7.142857              1.0
Rhodocyclaceae         1.0    7.142857              1.0
Termititenacaceae      1.0    7.142857              1.0
UBA932                 1.0    7.142857              1.0
unclassified           1.0    7.142857              1.0
TOTAL                 14.0  100.000000             21.0

Level: Genus

                Cluster   Cluster %  Total MAG count
Genus
Truepera            1.0    7.142857              6.0
Wolbachia           1.0    7.142857              3.0
JAISFT01            2.0   14.285714              2.0
unclassified        2.0   14.285714              2.0
JAIRKS01            1.0    7.142857              1.0
JAIRMO01            1.0    7.142857              1.0
JAIRMT01            1.0    7.142857              1.0
JAIRRR01            1.0    7.142857              1.0
JAITMY01            1.0    7.142857              1.0
Propionivibrio      1.0    7.142857              1.0
WQXQ01              1.0    7.142857              1.0
WRFZ01              1.0    7.142857              1.0
TOTAL              14.0  100.000000             21.0

Level: Species

                       Cluster   Cluster %  Total MAG count
Species
unclassified               9.0   64.285714              9.0
Truepera radiovictrix      1.0    7.142857              6.0
Wolbachia sp000829315      1.0    7.142857              3.0
JAIRMT01 sp031258505       1.0    7.142857              1.0
JAISFT01 sp031258225       1.0    7.142857              1.0
JAISFT01 sp031258265       1.0    7.142857              1.0
TOTAL                     14.0  100.000000             21.0

### Relative abundance

In [15]:
mq_relative_abund_df = get_relative_abund_taxo_levels(mq_df, coverage_df)

Level: Family

,count,mean,std,min,25%,50%,75%,max
Family,,,,,,,,
Anaplasmataceae,28.0,59.430150,21.488902,8.355348,56.387234,70.096448,72.117532,78.553025
Trueperaceae,28.0,20.698964,13.780085,0.749082,11.558213,17.298974,23.469264,63.998660
unclassified,28.0,14.112458,6.766245,1.942826,10.253545,11.581622,18.610035,31.585881
Breznakiellaceae,28.0,3.613006,13.274748,0.000000,0.000000,0.000000,0.000000,52.360361
Azobacteroidaceae,28.0,1.018320,3.162928,0.000000,0.000000,0.000000,0.000000,11.998474
UBA932,28.0,0.661761,3.501712,0.000000,0.000000,0.000000,0.000000,18.529317
Rhodocyclaceae,28.0,0.192630,0.727420,0.000000,0.000000,0.000000,0.000000,3.321346
Termititenacaceae,28.0,0.173732,0.799346,0.000000,0.000000,0.000000,0.000000,4.202165
Marinifilaceae,28.0,0.098978,0.523744,0.000000,0.000000,0.000000,0.000000,2.771390

Level: Genus

,count,mean,std,min,25%,50%,75%,max
Genus,,,,,,,,
Wolbachia,28.0,59.430150,21.488902,8.355348,56.387234,70.096448,72.117532,78.553025
Truepera,28.0,20.698964,13.780085,0.749082,11.558213,17.298974,23.469264,63.998660
unclassified,28.0,14.286191,6.492293,4.928190,10.253545,11.581622,18.610035,31.585881
JAIRMT01,28.0,1.903005,7.842085,0.000000,0.000000,0.000000,0.000000,39.723633
WRFZ01,28.0,1.018320,3.162928,0.000000,0.000000,0.000000,0.000000,11.998474
JAITMY01,28.0,0.661761,3.501712,0.000000,0.000000,0.000000,0.000000,18.529317
JAIRRR01,28.0,0.557447,2.350380,0.000000,0.000000,0.000000,0.000000,12.049477
JAISFT01,28.0,0.483147,1.969930,0.000000,0.000000,0.000000,0.000000,9.911112
WQXQ01,28.0,0.346461,1.363598,0.000000,0.000000,0.000000,0.000000,6.654739
JAIRMO01,28.0,0.322946,1.317119,0.000000,0.000000,0.000000,0.000000,6.627977
Propionivibrio,28.0,0.192630,0.727420,0.000000,0.000000,0.000000,0.000000,3.321346
JAIRKS01,28.0,0.098978,0.523744,0.000000,0.000000,0.000000,0.000000,2.771390

Level: Species

,count,mean,std,min,25%,50%,75%,max
Species,,,,,,,,
Wolbachia sp000829315,28.0,59.430150,21.488902,8.355348,56.387234,70.096448,72.117532,78.553025
Truepera radiovictrix,28.0,20.698964,13.780085,0.749082,11.558213,17.298974,23.469264,63.998660
unclassified,28.0,17.484734,12.043803,7.992525,10.519620,12.330538,19.304934,67.423964
JAIRMT01 sp031258505,28.0,1.903005,7.842085,0.000000,0.000000,0.000000,0.000000,39.723633
JAISFT01 sp031258225,28.0,0.258720,1.033913,0.000000,0.000000,0.000000,0.000000,5.121697
JAISFT01 sp031258265,28.0,0.224427,0.938121,0.000000,0.000000,0.000000,0.000000,4.789415

### Functions

In [16]:
print_stats(get_bakta_annot_df(mq_df).describe())

CDSs: 0.00 ± 0.00, Median: 0.00, IQR: 0.00-0.00, Range: 0.00-0.00
CRISPR arrays: 0.00 ± 0.00, Median: 0.00, IQR: 0.00-0.00, Range: 0.00-0.00
gaps: 0.00 ± 0.00, Median: 0.00, IQR: 0.00-0.00, Range: 0.00-0.00
hypotheticals: 0.00 ± 0.00, Median: 0.00, IQR: 0.00-0.00, Range: 0.00-0.00
ncRNA regions: 0.00 ± 0.00, Median: 0.00, IQR: 0.00-0.00, Range: 0.00-0.00
ncRNAs: 0.00 ± 0.00, Median: 0.00, IQR: 0.00-0.00, Range: 0.00-0.00
oriCs: 0.00 ± 0.00, Median: 0.00, IQR: 0.00-0.00, Range: 0.00-0.00
oriTs: 0.00 ± 0.00, Median: 0.00, IQR: 0.00-0.00, Range: 0.00-0.00
oriVs: 0.00 ± 0.00, Median: 0.00, IQR: 0.00-0.00, Range: 0.00-0.00
pseudogenes: 0.00 ± 0.00, Median: 0.00, IQR: 0.00-0.00, Range: 0.00-0.00
rRNAs: 15.36 ± 53.46, Median: 1.00, IQR: 0.00-1.00, Range: 0.00-201.00
sORFs: 0.00 ± 0.00, Median: 0.00, IQR: 0.00-0.00, Range: 0.00-0.00
signal peptides: 0.00 ± 0.00, Median: 0.00, IQR: 0.00-0.00, Range: 0.00-0.00
tRNAs: 0.00 ± 0.00, Median: 0.00, IQR: 0.00-0.00, Range: 0.00-0.00
tmRNAs: 0.00 ± 0.00, Median: 0.00, IQR: 0.00-0.00, Range: 0.00-0.00

In [17]:
get_kegg_path_df(mq_df)

Before removing rows and columns with only zeros:
Clusters: 14
KEGG modules: 314

After removing rows and columns with only zeros:
Clusters: 14
KEGG modules: 314

KEGG modules: 158.07 ± 23.22, Median: 152.50, IQR: 143.25-164.00, Range: 124.00-206.00

,"2-Oxocarboxylic acid chain extension, 2-oxoglutarate => 2-oxoadipate => 2-oxopimelate => 2-oxosuberate",3-Hydroxypropionate bi-cycle,ADP-L-glycero-D-manno-heptose biosynthesis,"Acarbose biosynthesis, sedoheptulopyranose-7P => acarbose","Acetyl-CoA pathway, CO2 => acetyl-CoA",Acylglycerol degradation,"Adenine ribonucleotide biosynthesis, IMP => ADP,ATP","Adenine ribonucleotide degradation, AMP => Urate","Arginine biosynthesis, glutamate => acetylcitrulline => arginine","Arginine biosynthesis, ornithine => arginine",...,"Valine/isoleucine biosynthesis, pyruvate => valine / 2-oxobutanoate => isoleucine","Vancomycin resistance, D-Ala-D-Lac type","Vancomycin resistance, D-Ala-D-Ser type","Xanthomonas spp. pathogenicity signature, T3SS and effectors","beta-Carotene biosynthesis, GGAP => beta-carotene",beta-Oxidation,"beta-Oxidation, acyl-CoA synthesis","beta-Oxidation, peroxisome, VLCFA","beta-Oxidation, peroxisome, tri/dihydroxycholestanoyl-CoA => choloyl/chenodeoxycholoyl-CoA",dTDP-L-rhamnose biosynthesis
0,0.00,5.56,20.0,0.0,0.00,50.0,100.0,100.00,0.00,0.00,...,0.0,0.0,0.0,0.00,0.00,100.00,100.0,66.67,66.67,33.33
1,33.33,27.78,0.0,0.0,0.00,0.0,100.0,100.00,28.57,66.67,...,100.0,25.0,0.0,0.00,33.33,100.00,100.0,0.00,0.00,100.00
2,0.00,5.56,0.0,12.5,0.00,0.0,75.0,50.00,42.86,100.00,...,100.0,0.0,0.0,0.00,0.00,0.00,100.0,0.00,0.00,100.00
3,0.00,11.11,0.0,0.0,0.00,0.0,75.0,16.67,14.29,0.00,...,25.0,0.0,0.0,1.14,0.00,0.00,0.0,0.00,0.00,0.00
4,0.00,5.56,100.0,0.0,0.00,0.0,75.0,33.33,71.43,100.00,...,100.0,0.0,0.0,9.09,16.67,33.33,100.0,0.00,0.00,100.00
5,0.00,2.78,20.0,0.0,33.33,0.0,50.0,66.67,14.29,33.33,...,50.0,25.0,0.0,0.00,0.00,0.00,100.0,0.00,0.00,100.00
6,0.00,22.22,80.0,0.0,0.00,0.0,75.0,16.67,85.71,66.67,...,100.0,0.0,0.0,0.00,0.00,0.00,100.0,0.00,0.00,66.67
7,0.00,7.41,0.0,0.0,33.33,0.0,75.0,88.89,57.14,100.00,...,50.0,25.0,0.0,0.00,0.00,0.00,100.0,0.00,0.00,0.00
8,0.00,11.11,20.0,0.0,33.33,0.0,50.0,66.67,57.14,100.00,...,100.0,25.0,0.0,0.00,0.00,0.00,100.0,0.00,0.00,0.00
9,0.00,1.39,0.0,0.0,0.00,0.0,100.0,50.00,57.14,100.00,...,50.0,75.0,60.0,0.00,0.00,0.00,100.0,0.00,0.00,100.00
10,0.00,5.56,0.0,0.0,0.00,0.0,75.0,50.00,57.14,100.00,...,75.0,0.0,0.0,0.00,0.00,0.00,100.0,0.00,0.00,0.00
11,0.00,0.00,0.0,0.0,33.33,0.0,100.0,33.33,57.14,100.00,...,100.0,75.0,60.0,0.00,0.00,0.00,100.0,0.00,0.00,100.00
12,0.00,3.70,0.0,0.0,0.00,0.0,100.0,50.00,42.86,33.33,...,75.0,0.0,0.0,0.00,0.00,0.00,100.0,0.00,0.00,100.00
13,0.00,16.67,20.0,0.0,0.00,0.0,75.0,0.00,57.14,100.00,...,50.0,0.0,0.0,0.00,0.00,0.00,100.0,0.00,0.00,100.00

### LQ: Low-quality species-level clusters (contamination < 10% and completeness < 50%)

In [18]:
lq_df = reps_df.query("Contamination < 10 and Completeness < 50")
compute_print_stats(lq_df)

Total number: 0.0
Cluster members: nan ± nan, Median: nan, IQR: nan-nan, Range: nan-nan
Contamination: nan ± nan, Median: nan, IQR: nan-nan, Range: nan-nan
Completeness: nan ± nan, Median: nan, IQR: nan-nan, Range: nan-nan
Total length: nan ± nan, Median: nan, IQR: nan-nan, Range: nan-nan