# Explore the bee microbiome use case

This notebook analyzes MAGs for the macroalgal microbiome use case.

**Inputs**: data in `../data/bee-use-case/data/`:
- `drep.csv`: dRep clustering output
- `checkm2.tsv`: CheckM2 quality assessment
- `gtdb.tsv`: GTDB taxonomy classification
- `quast.tsv`: QUAST assembly statistics
- `bakta.tsv`: BAKTA genome annotation

**Outputs**
- Plots: `../results/bee-use-case/`

In [1]:
from pathlib import Path
import sys

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.colors import LinearSegmentedColormap
from matplotlib.patches import Patch
from matplotlib import colors as mcolors


import seaborn as sns
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

sys.path.insert(0, str((Path.cwd() / "bin").resolve()))
sys.path.insert(0, str(Path.cwd().resolve()))

from helpers import (
    load_dfs,
    compute_print_stats,
    explore_species_level_clusters_all,
    compute_taxo_classification_summary,
    get_all_taxo_levels,
    get_bakta_annot_df,
    get_kegg_path_df,
    get_relative_abund_taxo_levels,
    print_stats,
)

In [2]:
data_dp = Path("../data/use-cases/bee-microbiome/")
data_dp.exists()

data_dp_2 = Path("../data/bee-use-case/")
data_dp_2.exists()

result_dp = Path("../results/bee-use-case/")
result_dp.exists()

metadata_df, reps_df, coverage_df = load_dfs(data_dp_2, result_dp)

In [3]:
expert_evaluation_fp = data_dp / "expert_evaluation.xlsx"
df_expert = pd.read_excel(expert_evaluation_fp)

# Quick overview
print(f"Rows: {len(df_expert)}")
print(f"Columns: {df_expert.shape[1]}")

Rows: 48
Columns: 22

In [4]:
sample_order = [
    "C1", "C2", "C3",
    "P1", "P2", "P3",
    "T1", "T2", "T3",
    "TP1", "TP2", "TP3",
    "N1", "N2", "N3",
    "NP1", "NP2", "NP3",
    "NT1", "NT2", "NT3",
]
metadata_df["Replicate"] = metadata_df["Replicate"].astype(str).str.replace(r"\s+Replicate", "", regex=True)

In [5]:
# WARNING: high percentage of unmapped
print("Percentage of unmapped reads for coverage")
print_stats(coverage_df.query("Genome == 'unmapped'").drop(columns="Genome").T.describe())

Percentage of unmapped reads for coverage
738: 3.92 ± 1.48, Median: 3.55, IQR: 2.65-4.53, Range: 2.27-7.33

# Quality

In [6]:
read_numbers = {
    "SRR24759596": 28.0,
    "SRR24759597": 18.1,
    "SRR24759598": 43.9,
    "SRR24759599": 55.3,
    "SRR24759600": 35.8,
    "SRR24759601": 11.9,
    "SRR24759602": 18.6,
    "SRR24759603": 32.0,
    "SRR24759604": 42.5,
    "SRR24759605": 48.7,
    "SRR24759606": 45.6,
    "SRR24759607": 7.8,
    "SRR24759608": 44.7,
    "SRR24759609": 45.8,
    "SRR24759610": 48.0,
    "SRR24759611": 42.1,
    "SRR24759612": 32.6,
    "SRR24759613": 42.3,
    "SRR24759614": 40.4,
    "SRR24759615": 43.6,
    "SRR24759616": 42.8
}
read_numbers_df = pd.DataFrame.from_dict(read_numbers, orient="index", columns=["Read numbers (M)"])
print_stats(read_numbers_df.describe())

Read numbers (M): 36.69 ± 12.90, Median: 42.30, IQR: 32.00-44.70, Range: 7.80-55.30

In [7]:
print(f"Total number of MAGs: {reps_df['Cluster members'].sum()}")
print(f"Total number of species-level clusters: {reps_df.shape[0]}")

Total number of MAGs: 1408
Total number of species-level clusters: 738

In [8]:
explore_species_level_clusters_all(reps_df)

Species-level clusters with no contamination threshold
Total number: 738.0
Cluster members: 1.91 ± 3.28, Median: 1.00, IQR: 1.00-1.00, Range: 1.00-31.00
Contamination: 1.13 ± 1.90, Median: 0.30, IQR: 0.06-1.18, Range: 0.00-9.97
Completeness: 17.93 ± 20.86, Median: 10.50, IQR: 7.70-16.80, Range: 2.20-100.00
Total length: 0.57 ± 0.65, Median: 0.34, IQR: 0.23-0.56, Range: 0.05-5.48

Species-level clusters with contamination < 5%
Total number: 693.0
Cluster members: 1.92 ± 3.25, Median: 1.00, IQR: 1.00-1.00, Range: 1.00-31.00
Contamination: 0.74 ± 1.07, Median: 0.27, IQR: 0.05-0.89, Range: 0.00-4.94
Completeness: 16.73 ± 20.36, Median: 10.20, IQR: 7.60-14.70, Range: 2.20-100.00
Total length: 0.54 ± 0.64, Median: 0.33, IQR: 0.23-0.54, Range: 0.05-5.48

Species-level clusters with contamination < 10%
Total number: 738.0
Cluster members: 1.91 ± 3.28, Median: 1.00, IQR: 1.00-1.00, Range: 1.00-31.00
Contamination: 1.13 ± 1.90, Median: 0.30, IQR: 0.06-1.18, Range: 0.00-9.97
Completeness: 17.93 ± 20.86, Median: 10.50, IQR: 7.70-16.80, Range: 2.20-100.00
Total length: 0.57 ± 0.65, Median: 0.34, IQR: 0.23-0.56, Range: 0.05-5.48

# Clusters given Bowers et al / MIMAG classification

## HQ: High-quality species-level clusters (contamination < 5% and completeness > 90%)

In [9]:
hq_df = reps_df.query("Contamination < 5 and Completeness > 90")
compute_print_stats(hq_df)

Total number: 25.0
Cluster members: 10.88 ± 8.76, Median: 11.00, IQR: 3.00-18.00, Range: 1.00-31.00
Contamination: 0.86 ± 0.92, Median: 0.54, IQR: 0.16-1.25, Range: 0.03-3.39
Completeness: 98.57 ± 2.44, Median: 99.80, IQR: 98.40-100.00, Range: 91.40-100.00
Total length: 2.90 ± 1.12, Median: 2.76, IQR: 2.14-3.48, Range: 1.26-5.48

### Taxonomy

In [10]:
compute_taxo_classification_summary(hq_df)

,Unclassified clusters,Classified clusters,Unclassified clusters %,Classified clusters %
Domain,0,25,0.0,100.0
Phylum,0,25,0.0,100.0
Class,0,25,0.0,100.0
Order,0,25,0.0,100.0
Family,0,25,0.0,100.0
Genus,0,25,0.0,100.0
Species,3,22,12.0,88.0

In [11]:
hq_taxo_levels = get_all_taxo_levels(hq_df)

Level: Domain

          Cluster  Cluster %  Total MAG count
Domain
Bacteria     25.0      100.0            272.0
TOTAL        25.0      100.0            272.0

Level: Phylum

                Cluster  Cluster %  Total MAG count
Phylum
Bacillota          10.0       40.0            120.0
Pseudomonadota     13.0       52.0            111.0
Actinomycetota      1.0        4.0             31.0
Bacteroidota        1.0        4.0             10.0
TOTAL              25.0      100.0            272.0

Level: Class

                     Cluster  Cluster %  Total MAG count
Class
Bacilli                  7.0       28.0            103.0
Gammaproteobacteria     12.0       48.0            100.0
Actinomycetes            1.0        4.0             31.0
Clostridia               3.0       12.0             17.0
Alphaproteobacteria      1.0        4.0             11.0
Bacteroidia              1.0        4.0             10.0
TOTAL                   25.0      100.0            272.0

Level: Order

                    Cluster  Cluster %  Total MAG count
Order
Lactobacillales         6.0       24.0            102.0
Enterobacterales        6.0       24.0             53.0
Actinomycetales         1.0        4.0             31.0
Burkholderiales         1.0        4.0             27.0
Pseudomonadales         4.0       16.0             18.0
Lachnospirales          2.0        8.0             14.0
Rhizobiales             1.0        4.0             11.0
Flavobacteriales        1.0        4.0             10.0
Tissierellales          1.0        4.0              3.0
Enterobacterales_A      1.0        4.0              2.0
Bacillales_D            1.0        4.0              1.0
TOTAL                  25.0      100.0            272.0

Level: Family

                      Cluster  Cluster %  Total MAG count
Family
Lactobacillaceae          5.0       20.0             89.0
Enterobacteriaceae        6.0       24.0             53.0
Bifidobacteriaceae        1.0        4.0             31.0
Neisseriaceae             1.0        4.0             27.0
Pseudomonadaceae          4.0       16.0             18.0
Lachnospiraceae           2.0        8.0             14.0
Enterococcaceae           1.0        4.0             13.0
Rhizobiaceae              1.0        4.0             11.0
Weeksellaceae             1.0        4.0             10.0
Tepidimicrobiaceae        1.0        4.0              3.0
Enterobacteriaceae_A      1.0        4.0              2.0
Amphibacillaceae          1.0        4.0              1.0
TOTAL                    25.0      100.0            272.0

Level: Genus

                     Cluster  Cluster %  Total MAG count
Genus
Apilactobacillus         2.0        8.0             39.0
Bombiscardovia           1.0        4.0             31.0
Snodgrassella            1.0        4.0             27.0
Fructobacillus           1.0        4.0             21.0
Frischella               1.0        4.0             21.0
Entomomonas              4.0       16.0             18.0
Lactobacillus            1.0        4.0             18.0
Proteus                  1.0        4.0             15.0
Enterococcus             1.0        4.0             13.0
Novisyntrophococcus      1.0        4.0             12.0
Bartonella_A             1.0        4.0             11.0
Klebsiella               1.0        4.0             11.0
Bombilactobacillus       1.0        4.0             11.0
Apibacter                1.0        4.0             10.0
Providencia              2.0        8.0              5.0
Schnuerera               1.0        4.0              3.0
Arsenophonus             1.0        4.0              2.0
Mobilisporobacter        1.0        4.0              2.0
Serratia                 1.0        4.0              1.0
Virgibacillus            1.0        4.0              1.0
TOTAL                   25.0      100.0            272.0

Level: Species

                                Cluster  Cluster %  Total MAG count
Species
Bombiscardovia coryneforme          1.0        4.0             31.0
Snodgrassella alvi                  1.0        4.0             27.0
Fructobacillus fructosus            1.0        4.0             21.0
Apilactobacillus kunkeei_C          1.0        4.0             21.0
Frischella perrara                  1.0        4.0             21.0
Lactobacillus helsingborgensis      1.0        4.0             18.0
Apilactobacillus kunkeei            1.0        4.0             18.0
unclassified                        3.0       12.0             17.0
Proteus mirabilis                   1.0        4.0             15.0
Enterococcus faecalis               1.0        4.0             13.0
Novisyntrophococcus liquoris        1.0        4.0             12.0
Klebsiella oxytoca                  1.0        4.0             11.0
Bombilactobacillus mellis           1.0        4.0             11.0
Apibacter sp945280365               1.0        4.0             10.0
Entomomonas sp040391985             1.0        4.0              7.0
Entomomonas sp945283395             1.0        4.0              6.0
Providencia alcalifaciens           1.0        4.0              4.0
Schnuerera sp021655095              1.0        4.0              3.0
Arsenophonus apicola                1.0        4.0              2.0
Providencia hangzhouensis           1.0        4.0              1.0
Entomomonas moraniae                1.0        4.0              1.0
Serratia ureilytica                 1.0        4.0              1.0
Virgibacillus proomii_B             1.0        4.0              1.0
TOTAL                              25.0      100.0            272.0

### Relative abundance

In [12]:
hq_relative_abund_df = get_relative_abund_taxo_levels(hq_df, coverage_df)

Unmapped reads: 97.99 ± 0.63, Median: 98.04, IQR: 97.69-98.47, Range: 96.38-98.86
Mapped reads: 2.01 ± 0.63, Median: 1.96, IQR: 1.53-2.31, Range: 1.14-3.62

Level: Family

,count,mean,std,min,25%,50%,75%,max
Family,,,,,,,,
Lactobacillaceae,21.0,29.474026,11.277514,16.195624,18.891546,27.103494,38.855413,49.985107
Enterobacteriaceae,21.0,26.106860,12.801258,8.565245,18.925036,20.197614,33.829097,59.959677
Bifidobacteriaceae,21.0,14.834319,5.813520,4.520713,10.321686,15.101173,20.735697,26.198460
Neisseriaceae,21.0,13.450944,6.529704,2.563699,8.228466,12.253934,17.021209,25.000389
Pseudomonadaceae,21.0,6.227870,9.735293,0.000000,0.927756,1.302256,5.447459,35.044877
Enterobacteriaceae_A,21.0,2.598459,10.420032,0.000000,0.000000,0.194781,0.292013,47.999582
Lachnospiraceae,21.0,2.248636,2.488984,0.299311,1.001204,1.458546,1.984761,9.156576
Enterococcaceae,21.0,1.642941,1.122110,0.000000,0.782234,1.484973,2.537494,3.614520
Weeksellaceae,21.0,1.389835,1.450400,0.000000,0.220541,0.521633,2.477421,4.701882
Rhizobiaceae,21.0,1.382412,1.127969,0.000000,0.332545,1.321532,2.077815,3.768241
Amphibacillaceae,21.0,0.390728,1.742188,0.000000,0.000000,0.000000,0.000000,7.992983
Tepidimicrobiaceae,21.0,0.252971,0.610646,0.000000,0.000000,0.000000,0.000000,2.091269

Level: Genus

,count,mean,std,min,25%,50%,75%,max
Genus,,,,,,,,
Apilactobacillus,21.0,19.533153,8.707160,9.634613,12.632939,17.422982,22.950254,39.544072
Bombiscardovia,21.0,14.834319,5.813520,4.520713,10.321686,15.101173,20.735697,26.198460
Snodgrassella,21.0,13.450944,6.529704,2.563699,8.228466,12.253934,17.021209,25.000389
Frischella,21.0,13.337759,7.381081,1.794902,5.806258,15.555865,18.884089,26.537865
Proteus,21.0,9.169647,9.971945,0.000000,0.984134,8.560328,13.520202,38.845161
Entomomonas,21.0,6.227870,9.735293,0.000000,0.927756,1.302256,5.447459,35.044877
Fructobacillus,21.0,4.730643,2.619312,1.753222,2.454262,4.510225,5.245008,11.443680
Lactobacillus,21.0,3.693691,3.448845,0.569242,1.226562,2.258792,5.386091,13.069713
Arsenophonus,21.0,2.598459,10.420032,0.000000,0.000000,0.194781,0.292013,47.999582
Klebsiella,21.0,2.229657,3.285238,0.000000,0.382318,1.822705,2.493298,14.522391
Novisyntrophococcus,21.0,2.032286,2.196287,0.299311,0.892815,1.447700,1.882802,8.556889
Enterococcus,21.0,1.642941,1.122110,0.000000,0.782234,1.484973,2.537494,3.614520
Bombilactobacillus,21.0,1.516540,1.215421,0.191965,0.620481,1.049785,2.198830,4.760596
Apibacter,21.0,1.389835,1.450400,0.000000,0.220541,0.521633,2.477421,4.701882
Bartonella_A,21.0,1.382412,1.127969,0.000000,0.332545,1.321532,2.077815,3.768241
Providencia,21.0,1.185982,2.110606,0.000000,0.000000,0.342297,0.749145,7.429144
Virgibacillus,21.0,0.390728,1.742188,0.000000,0.000000,0.000000,0.000000,7.992983
Schnuerera,21.0,0.252971,0.610646,0.000000,0.000000,0.000000,0.000000,2.091269
Mobilisporobacter,21.0,0.216350,0.685494,0.000000,0.000000,0.000000,0.000000,2.997924
Serratia,21.0,0.183814,0.640549,0.000000,0.000000,0.000000,0.000000,2.913478

Level: Species

,count,mean,std,min,25%,50%,75%,max
Species,,,,,,,,
Bombiscardovia coryneforme,21.0,14.834319,5.813520,4.520713,10.321686,15.101173,20.735697,26.198460
Snodgrassella alvi,21.0,13.450944,6.529704,2.563699,8.228466,12.253934,17.021209,25.000389
Frischella perrara,21.0,13.337759,7.381081,1.794902,5.806258,15.555865,18.884089,26.537865
Apilactobacillus kunkeei_C,21.0,12.417001,6.396346,4.386389,6.799073,11.726097,16.231213,26.686901
Proteus mirabilis,21.0,9.169647,9.971945,0.000000,0.984134,8.560328,13.520202,38.845161
Apilactobacillus kunkeei,21.0,7.116151,3.420425,2.780449,4.431025,6.174900,8.685110,16.257300
Fructobacillus fructosus,21.0,4.730643,2.619312,1.753222,2.454262,4.510225,5.245008,11.443680
unclassified,21.0,4.127854,6.281151,0.000000,1.321532,1.595972,2.891076,22.520844
Lactobacillus helsingborgensis,21.0,3.693691,3.448845,0.569242,1.226562,2.258792,5.386091,13.069713
Arsenophonus apicola,21.0,2.598459,10.420032,0.000000,0.000000,0.194781,0.292013,47.999582
Klebsiella oxytoca,21.0,2.229657,3.285238,0.000000,0.382318,1.822705,2.493298,14.522391
Entomomonas sp040391985,21.0,2.151699,4.800649,0.000000,0.000000,0.096604,0.843119,19.120429
Novisyntrophococcus liquoris,21.0,2.032286,2.196287,0.299311,0.892815,1.447700,1.882802,8.556889
Enterococcus faecalis,21.0,1.642941,1.122110,0.000000,0.782234,1.484973,2.537494,3.614520
Bombilactobacillus mellis,21.0,1.516540,1.215421,0.191965,0.620481,1.049785,2.198830,4.760596
Apibacter sp945280365,21.0,1.389835,1.450400,0.000000,0.220541,0.521633,2.477421,4.701882
Entomomonas moraniae,21.0,0.894031,3.332955,0.000000,0.000000,0.106868,0.247704,15.409060
Providencia alcalifaciens,21.0,0.787789,1.715762,0.000000,0.000000,0.097033,0.639776,7.362096
Entomomonas sp945283395,21.0,0.653048,0.767517,0.000000,0.000000,0.462850,0.691196,2.679892
Providencia hangzhouensis,21.0,0.398193,1.386402,0.000000,0.000000,0.000000,0.067048,6.342582
Virgibacillus proomii_B,21.0,0.390728,1.742188,0.000000,0.000000,0.000000,0.000000,7.992983
Schnuerera sp021655095,21.0,0.252971,0.610646,0.000000,0.000000,0.000000,0.000000,2.091269
Serratia ureilytica,21.0,0.183814,0.640549,0.000000,0.000000,0.000000,0.000000,2.913478

### Functions

In [13]:
print_stats(get_bakta_annot_df(hq_df).describe())

CDSs: nan ± nan, Median: nan, IQR: nan-nan, Range: nan-nan
CRISPR arrays: nan ± nan, Median: nan, IQR: nan-nan, Range: nan-nan
gaps: nan ± nan, Median: nan, IQR: nan-nan, Range: nan-nan
hypotheticals: nan ± nan, Median: nan, IQR: nan-nan, Range: nan-nan
ncRNA regions: nan ± nan, Median: nan, IQR: nan-nan, Range: nan-nan
ncRNAs: nan ± nan, Median: nan, IQR: nan-nan, Range: nan-nan
oriCs: nan ± nan, Median: nan, IQR: nan-nan, Range: nan-nan
oriTs: nan ± nan, Median: nan, IQR: nan-nan, Range: nan-nan
oriVs: nan ± nan, Median: nan, IQR: nan-nan, Range: nan-nan
pseudogenes: nan ± nan, Median: nan, IQR: nan-nan, Range: nan-nan
rRNAs: nan ± nan, Median: nan, IQR: nan-nan, Range: nan-nan
sORFs: nan ± nan, Median: nan, IQR: nan-nan, Range: nan-nan
signal peptides: nan ± nan, Median: nan, IQR: nan-nan, Range: nan-nan
tRNAs: nan ± nan, Median: nan, IQR: nan-nan, Range: nan-nan
tmRNAs: nan ± nan, Median: nan, IQR: nan-nan, Range: nan-nan

In [14]:
get_kegg_path_df(hq_df)

Before removing rows and columns with only zeros:
Clusters: 25
KEGG modules: 319

After removing rows and columns with only zeros:
Clusters: 25
KEGG modules: 296

KEGG modules: 171.72 ± 37.18, Median: 178.00, IQR: 146.00-196.00, Range: 103.00-233.00

,3-Hydroxypropionate bi-cycle,ADP-L-glycero-D-manno-heptose biosynthesis,"Acetyl-CoA pathway, CO2 => acetyl-CoA",Acylglycerol degradation,"Adenine ribonucleotide biosynthesis, IMP => ADP,ATP","Adenine ribonucleotide degradation, AMP => Urate","Aerobactin biosynthesis, lysine => aerobactin","Anammox, nitrite + ammonia => nitrogen","Anthranilate degradation, anthranilate => catechol","Arginine biosynthesis, glutamate => acetylcitrulline => arginine",...,"Vancomycin resistance, D-Ala-D-Lac type","Vancomycin resistance, D-Ala-D-Ser type","Vibrio cholerae pathogenicity signature, cholera toxins","Xanthomonas spp. pathogenicity signature, T3SS and effectors","Xylene degradation, xylene => methylbenzoate","beta-Carotene biosynthesis, GGAP => beta-carotene","beta-Lactam resistance, Bla system",beta-Oxidation,"beta-Oxidation, acyl-CoA synthesis",dTDP-L-rhamnose biosynthesis
0,16.67,100.0,0.00,0.0,100.0,66.67,0.0,0.00,0.00,100.00,...,25.00,0.0,0.00,6.82,0.00,0.00,0.00,100.00,100.0,83.33
1,16.67,100.0,0.00,50.0,100.0,66.67,25.0,0.00,0.00,85.71,...,0.00,0.0,0.00,5.68,0.00,0.00,0.00,100.00,100.0,50.00
2,16.67,80.0,0.00,0.0,100.0,66.67,0.0,0.00,0.00,100.00,...,25.00,0.0,0.00,0.00,0.00,0.00,33.33,0.00,100.0,100.00
3,16.67,100.0,0.00,0.0,100.0,66.67,0.0,0.00,25.00,100.00,...,25.00,0.0,0.00,6.82,0.00,0.00,0.00,100.00,100.0,83.33
4,16.67,80.0,0.00,50.0,100.0,66.67,0.0,0.00,0.00,100.00,...,0.00,0.0,0.00,0.00,0.00,0.00,0.00,100.00,100.0,100.00
5,16.67,80.0,0.00,50.0,100.0,66.67,0.0,0.00,0.00,100.00,...,25.00,0.0,16.67,0.00,0.00,0.00,0.00,66.67,100.0,100.00
6,5.56,100.0,0.00,50.0,75.0,50.00,0.0,0.00,0.00,100.00,...,25.00,0.0,0.00,1.14,0.00,0.00,0.00,0.00,0.0,0.00
7,11.11,0.0,0.00,0.0,50.0,77.78,0.0,0.00,0.00,14.29,...,25.00,0.0,0.00,1.14,0.00,0.00,33.33,0.00,0.0,33.33
8,12.96,0.0,0.00,0.0,75.0,16.67,0.0,0.00,0.00,57.14,...,0.00,0.0,0.00,0.00,0.00,0.00,33.33,0.00,100.0,0.00
9,22.22,100.0,0.00,0.0,100.0,66.67,0.0,0.00,25.00,100.00,...,0.00,0.0,0.00,0.00,33.33,0.00,33.33,100.00,100.0,83.33
10,16.67,0.0,0.00,0.0,100.0,66.67,0.0,0.00,0.00,85.71,...,25.00,0.0,0.00,0.00,0.00,0.00,33.33,0.00,100.0,100.00
11,22.22,20.0,0.00,50.0,100.0,66.67,0.0,0.00,0.00,28.57,...,50.00,0.0,0.00,0.00,0.00,0.00,100.00,100.00,100.0,0.00
12,40.28,0.0,0.00,0.0,75.0,66.67,0.0,0.00,0.00,57.14,...,0.00,0.0,0.00,0.00,0.00,16.67,0.00,66.67,100.0,100.00
13,16.67,100.0,0.00,50.0,100.0,100.00,25.0,0.00,0.00,14.29,...,0.00,0.0,0.00,9.09,0.00,0.00,33.33,100.00,100.0,83.33
14,7.41,0.0,0.00,0.0,75.0,33.33,0.0,0.00,0.00,28.57,...,0.00,0.0,0.00,0.00,33.33,0.00,33.33,33.33,0.0,100.00
15,3.70,0.0,0.00,0.0,75.0,66.67,0.0,33.33,0.00,57.14,...,12.50,0.0,0.00,0.00,0.00,0.00,0.00,0.00,100.0,100.00
16,7.41,0.0,0.00,0.0,100.0,77.78,0.0,0.00,0.00,0.00,...,0.00,0.0,0.00,0.00,0.00,0.00,66.67,0.00,0.0,100.00
18,12.96,0.0,33.33,0.0,75.0,50.00,0.0,0.00,0.00,71.43,...,100.00,40.0,0.00,0.00,0.00,0.00,0.00,0.00,0.0,100.00
19,16.67,40.0,0.00,0.0,100.0,66.67,25.0,0.00,0.00,71.43,...,0.00,0.0,0.00,0.00,0.00,16.67,0.00,0.00,100.0,33.33
20,5.56,0.0,0.00,0.0,75.0,16.67,0.0,0.00,0.00,28.57,...,25.00,0.0,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.00
21,16.67,100.0,0.00,0.0,100.0,66.67,25.0,0.00,33.33,100.00,...,0.00,0.0,0.00,0.00,0.00,0.00,0.00,66.67,100.0,83.33
22,16.67,80.0,0.00,50.0,100.0,66.67,25.0,0.00,0.00,100.00,...,0.00,0.0,0.00,0.00,33.33,0.00,0.00,0.00,100.0,100.00
23,12.96,0.0,0.00,0.0,75.0,16.67,0.0,0.00,0.00,57.14,...,0.00,0.0,0.00,0.00,0.00,0.00,33.33,0.00,100.0,0.00
24,0.00,20.0,0.00,0.0,75.0,50.00,0.0,0.00,0.00,57.14,...,50.00,80.0,0.00,1.14,0.00,0.00,66.67,0.00,100.0,100.00
25,5.56,0.0,0.00,0.0,50.0,33.33,0.0,0.00,0.00,0.00,...,16.67,0.0,0.00,0.00,0.00,0.00,66.67,0.00,0.0,0.00

## MQ: Medium-quality species-level clusters (contamination < 10% and completeness > 50%)

In [15]:
mq_df = reps_df.query("Contamination < 10 and Completeness > 50")
display(mq_df.iloc[:, :25])
compute_print_stats(mq_df)

,MAG,Domain,Phylum,Class,Order,Family,Genus,Species,Cluster members,Completeness,...,GC (%),L50,L90,Largest contig,N50,N90,Total length,Total length (>= 0 bp),Total length (>= 1000 bp),auN
0,SRR24759603_binette_bin1,Bacteria,Pseudomonadota,Gammaproteobacteria,Enterobacterales,Enterobacteriaceae,Providencia,Providencia alcalifaciens,4,100.0,...,41.84,6.0,13.0,506402.0,261870.0,132919.0,3861557.0,3861557.0,3861557.0,283861.3
1,SRR24759615_binette_bin1,Bacteria,Pseudomonadota,Gammaproteobacteria,Enterobacterales,Enterobacteriaceae,Proteus,Proteus mirabilis,15,100.0,...,38.73,23.0,71.0,127849.0,49487.0,17631.0,3476427.0,3476427.0,3476427.0,55623.8
2,SRR24759600_binette_bin6,Bacteria,Pseudomonadota,Gammaproteobacteria,Pseudomonadales,Pseudomonadaceae,Entomomonas,Entomomonas moraniae,1,100.0,...,38.07,4.0,14.0,513259.0,285762.0,46381.0,3426966.0,3426966.0,3426966.0,302215.1
3,SRR24759606_binette_bin1,Bacteria,Pseudomonadota,Gammaproteobacteria,Enterobacterales,Enterobacteriaceae,Providencia,Providencia hangzhouensis,1,100.0,...,40.12,6.0,14.0,645620.0,301940.0,124058.0,4504648.0,4504648.0,4504648.0,332957.4
4,SRR24759606_binette_bin2,Bacteria,Pseudomonadota,Gammaproteobacteria,Pseudomonadales,Pseudomonadaceae,Entomomonas,Entomomonas sp040391985,7,100.0,...,35.79,5.0,15.0,430480.0,271820.0,76097.0,3260803.0,3260803.0,3260803.0,249663.5
5,SRR24759603_binette_bin2,Bacteria,Pseudomonadota,Gammaproteobacteria,Pseudomonadales,Pseudomonadaceae,Entomomonas,unclassified,4,100.0,...,39.81,7.0,17.0,347229.0,188039.0,57275.0,3041630.0,3041630.0,3041630.0,181627.2
6,SRR24759597_binette_bin1,Bacteria,Pseudomonadota,Gammaproteobacteria,Enterobacterales,Enterobacteriaceae,Frischella,Frischella perrara,21,100.0,...,34.00,16.0,55.0,151911.0,33844.0,9767.0,2142574.0,2142574.0,2142574.0,54116.7
7,SRR24759600_binette_bin3,Bacteria,Bacillota,Clostridia,Tissierellales,Tepidimicrobiaceae,Schnuerera,Schnuerera sp021655095,3,100.0,...,31.40,37.0,121.0,105510.0,23593.0,7535.0,2758665.0,2758665.0,2758665.0,28461.7
8,SRR24759606_binette_bin3,Bacteria,Bacillota,Bacilli,Lactobacillales,Lactobacillaceae,Apilactobacillus,Apilactobacillus kunkeei_C,21,100.0,...,37.14,22.0,73.0,89870.0,23540.0,5687.0,1535311.0,1535311.0,1535311.0,27390.6
9,SRR24759610_binette_bin1,Bacteria,Pseudomonadota,Gammaproteobacteria,Enterobacterales,Enterobacteriaceae,Klebsiella,Klebsiella oxytoca,11,99.9,...,55.49,30.0,88.0,299962.0,57121.0,19335.0,5483319.0,5483319.0,5483319.0,77894.5
10,SRR24759600_binette_bin1,Bacteria,Bacteroidota,Bacteroidia,Flavobacteriales,Weeksellaceae,Apibacter,Apibacter sp945280365,10,99.9,...,29.57,8.0,22.0,248517.0,118501.0,36540.0,2426353.0,2426353.0,2426353.0,118271.5
11,SRR24759612_binette_bin1,Bacteria,Bacillota,Bacilli,Bacillales_D,Amphibacillaceae,Virgibacillus,Virgibacillus proomii_B,1,99.9,...,35.93,31.0,92.0,139103.0,48725.0,16425.0,4501605.0,4501605.0,4501605.0,54982.6
12,SRR24759600_binette_bin2,Bacteria,Pseudomonadota,Alphaproteobacteria,Rhizobiales,Rhizobiaceae,Bartonella_A,unclassified,11,99.8,...,45.33,6.0,27.0,422661.0,123140.0,23753.0,2669964.0,2669964.0,2669964.0,170918.6
13,SRR24759605_binette_bin3,Bacteria,Pseudomonadota,Gammaproteobacteria,Enterobacterales_A,Enterobacteriaceae_A,Arsenophonus,Arsenophonus apicola,2,99.7,...,37.05,8.0,22.0,332169.0,131653.0,35649.0,2880954.0,2880954.0,2880954.0,140130.9
14,SRR24759599_binette_bin3,Bacteria,Bacillota,Bacilli,Lactobacillales,Lactobacillaceae,Bombilactobacillus,Bombilactobacillus mellis,11,99.7,...,36.68,25.0,96.0,90331.0,15683.0,4860.0,1547252.0,1547252.0,1547252.0,24068.1
15,SRR24759604_binette_bin3,Bacteria,Actinomycetota,Actinomycetes,Actinomycetales,Bifidobacteriaceae,Bombiscardovia,Bombiscardovia coryneforme,31,99.4,...,60.58,31.0,102.0,53855.0,19129.0,4106.0,1744940.0,1744940.0,1744940.0,20888.0
16,SRR24759610_binette_bin2,Bacteria,Bacillota,Bacilli,Lactobacillales,Enterococcaceae,Enterococcus,Enterococcus faecalis,13,99.3,...,37.79,51.0,148.0,65421.0,17057.0,5699.0,2553191.0,2553191.0,2553191.0,19726.5
17,SRR24759613_binette_bin6,Bacteria,Pseudomonadota,Alphaproteobacteria,Rhizobiales,Rhizobiaceae,Bartonella_A,Bartonella_A sp945285915,25,99.3,...,41.87,104.0,372.0,37304.0,8635.0,2158.0,2870822.0,2870822.0,2870822.0,10002.2
18,SRR24759613_binette_bin1,Bacteria,Bacillota,Clostridia,Lachnospirales,Lachnospiraceae,Novisyntrophococcus,Novisyntrophococcus liquoris,12,98.7,...,42.19,16.0,48.0,198984.0,72494.0,20727.0,3509914.0,3509914.0,3509914.0,82087.1
19,SRR24759614_binette_bin5,Bacteria,Pseudomonadota,Gammaproteobacteria,Burkholderiales,Neisseriaceae,Snodgrassella,Snodgrassella alvi,27,98.4,...,41.35,74.0,240.0,31438.0,9473.0,2838.0,2328803.0,2328803.0,2328803.0,11655.2
20,SRR24759613_binette_bin2,Bacteria,Bacillota,Bacilli,Lactobacillales,Lactobacillaceae,Fructobacillus,Fructobacillus fructosus,21,98.0,...,45.24,4.0,9.0,213978.0,132427.0,70986.0,1262975.0,1262975.0,1262975.0,142417.6
21,SRR24759598_binette_bin3,Bacteria,Pseudomonadota,Gammaproteobacteria,Enterobacterales,Enterobacteriaceae,Serratia,Serratia ureilytica,1,97.9,...,60.10,129.0,385.0,57740.0,11813.0,3791.0,4692206.0,4692206.0,4692206.0,13687.8
22,SRR24759603_binette_bin6,Bacteria,Pseudomonadota,Gammaproteobacteria,Pseudomonadales,Pseudomonadaceae,Entomomonas,Entomomonas sp945283395,6,95.0,...,35.62,132.0,397.0,28875.0,5984.0,2088.0,2407146.0,2407146.0,2407146.0,6914.7
23,SRR24759604_binette_bin8,Bacteria,Bacillota,Bacilli,Lactobacillales,Lactobacillaceae,Apilactobacillus,Apilactobacillus kunkeei,18,94.2,...,36.14,57.0,199.0,37225.0,7070.0,2335.0,1442450.0,1442450.0,1442450.0,9618.5
24,SRR24759614_binette_bin6,Bacteria,Bacillota,Clostridia,Lachnospirales,Lachnospiraceae,Mobilisporobacter,unclassified,2,93.1,...,36.45,97.0,309.0,68220.0,10441.0,3468.0,3269048.0,3269048.0,3269048.0,12996.5
25,SRR24759610_binette_bin5,Bacteria,Bacillota,Bacilli,Lactobacillales,Lactobacillaceae,Lactobacillus,Lactobacillus helsingborgensis,18,91.4,...,36.75,11.0,35.0,188910.0,50376.0,14906.0,1675459.0,1675459.0,1675459.0,62244.1
26,SRR24759604_binette_bin6,Bacteria,Pseudomonadota,Alphaproteobacteria,Rhizobiales,Rhizobiaceae,Bartonella_A,Bartonella_A choladocola,21,89.6,...,45.75,28.0,89.0,90327.0,18336.0,5510.0,1747015.0,1747015.0,1747015.0,24676.4
27,SRR24759604_binette_bin9,Bacteria,Pseudomonadota,Gammaproteobacteria,Burkholderiales,Neisseriaceae,Snodgrassella,Snodgrassella alvi_G,10,89.1,...,39.29,120.0,312.0,15838.0,4430.0,2041.0,1497026.0,1497026.0,1497026.0,4944.2
28,SRR24759609_binette_bin3,Bacteria,Pseudomonadota,Gammaproteobacteria,Enterobacterales,Enterobacteriaceae,Gilliamella,Gilliamella sp945271295,6,87.5,...,34.50,15.0,45.0,142048.0,49786.0,22238.0,2557107.0,2557107.0,2557107.0,64658.8
29,SRR24759610_binette_bin9,Bacteria,Bacillota,Bacilli,Lactobacillales,Lactobacillaceae,Lactobacillus,Lactobacillus kimbladii,2,87.0,...,35.74,21.0,62.0,71110.0,27919.0,10511.0,1844851.0,1844851.0,1844851.0,32511.8
30,SRR24759598_binette_bin7,Bacteria,Bacillota,Bacilli,Lactobacillales,Lactobacillaceae,Apilactobacillus,Apilactobacillus apinorum,9,83.7,...,34.38,20.0,74.0,64643.0,17754.0,3971.0,1301578.0,1301578.0,1301578.0,23944.9
31,SRR24759612_binette_bin5,Bacteria,Bacillota,Bacilli,Lactobacillales,Lactobacillaceae,Lactobacillus,Lactobacillus melliventris,18,83.3,...,35.91,52.0,170.0,38212.0,9730.0,3421.0,1731171.0,1731171.0,1731171.0,12740.8
32,SRR24759604_binette_bin10,Bacteria,Bacillota,Bacilli,Lactobacillales,Lactobacillaceae,Lactobacillus,Lactobacillus apis,25,83.2,...,37.01,64.0,186.0,18633.0,5605.0,1952.0,1100290.0,1100290.0,1100290.0,6574.7
33,SRR24759603_binette_bin13,Bacteria,Pseudomonadota,Gammaproteobacteria,Burkholderiales,Neisseriaceae,Snodgrassella,Snodgrassella alvi,12,82.3,...,41.55,98.0,345.0,25269.0,5710.0,1756.0,1900302.0,1900302.0,1900302.0,7146.6
34,SRR24759611_binette_bin5,Bacteria,Pseudomonadota,Gammaproteobacteria,Enterobacterales,Enterobacteriaceae,Gilliamella,Gilliamella apicola,16,79.9,...,32.66,88.0,274.0,44196.0,9346.0,3266.0,2610659.0,2610659.0,2610659.0,11658.5
35,SRR24759615_binette_bin12,Bacteria,Pseudomonadota,Alphaproteobacteria,Rhizobiales,Rhizobiaceae,Bartonella_A,unclassified,1,77.4,...,44.22,11.0,38.0,172115.0,73462.0,19133.0,2169834.0,2169834.0,2169834.0,72235.2
36,SRR24759615_binette_bin15,Bacteria,Pseudomonadota,Gammaproteobacteria,Enterobacterales,Enterobacteriaceae,Gilliamella,Gilliamella apicola_R,12,77.1,...,35.20,70.0,217.0,53035.0,11137.0,4078.0,2461745.0,2461745.0,2461745.0,13835.6
37,SRR24759609_binette_bin7,Bacteria,Pseudomonadota,Gammaproteobacteria,Enterobacterales,Enterobacteriaceae,Klebsiella,Klebsiella grimontii,1,76.0,...,56.61,551.0,1484.0,11083.0,2448.0,1255.0,4082729.0,4082729.0,4082729.0,2922.0
38,SRR24759600_binette_bin14,Bacteria,Bacillota,Clostridia,Lachnospirales,Lachnospiraceae,Novisyntrophococcus,Novisyntrophococcus fermenticellae,5,73.7,...,43.68,235.0,643.0,15798.0,3104.0,1388.0,2157642.0,2157642.0,2157642.0,3603.4
39,SRR24759602_binette_bin8,Bacteria,Pseudomonadota,Gammaproteobacteria,Enterobacterales,Enterobacteriaceae,Providencia,Providencia rettgeri,2,73.7,...,40.02,206.0,595.0,21127.0,5499.0,2333.0,3527781.0,3527781.0,3527781.0,6617.8
40,SRR24759607_binette_bin3,Bacteria,Pseudomonadota,Gammaproteobacteria,Enterobacterales,Enterobacteriaceae,Gilliamella,Gilliamella apicola_N,9,72.9,...,34.11,71.0,190.0,30802.0,9731.0,4534.0,1975440.0,1975440.0,1975440.0,10841.4
41,SRR24759597_binette_bin7,Bacteria,Pseudomonadota,Gammaproteobacteria,Enterobacterales,Enterobacteriaceae,Morganella,Morganella sibonii,4,72.6,...,51.23,367.0,995.0,10181.0,2646.0,1292.0,2904338.0,2904338.0,2904338.0,3060.8
42,SRR24759603_binette_bin17,Bacteria,Pseudomonadota,Gammaproteobacteria,Enterobacterales,Enterobacteriaceae,Gilliamella,Gilliamella sp946480175,5,72.2,...,35.15,49.0,163.0,57471.0,12017.0,2930.0,1864772.0,1864772.0,1864772.0,15098.4
43,SRR24759604_binette_bin12,Bacteria,Bacillota,Clostridia,Tissierellales,Tissierellaceae,CABMKH01,CABMKH01 sp040797625,4,70.4,...,32.49,261.0,726.0,24883.0,2720.0,1328.0,2236802.0,2236802.0,2236802.0,3645.1
44,SRR24759608_binette_bin13,Bacteria,Pseudomonadota,Gammaproteobacteria,Enterobacterales,Enterobacteriaceae,Gilliamella,Gilliamella apis_A,10,68.5,...,34.21,111.0,313.0,21717.0,5274.0,2605.0,1875763.0,1875763.0,1875763.0,6659.0
45,SRR24759601_binette_bin7,Bacteria,Pseudomonadota,Gammaproteobacteria,Enterobacterales,Enterobacteriaceae,Gilliamella,Gilliamella apis,4,65.3,...,34.19,128.0,404.0,14598.0,3452.0,1356.0,1497732.0,1497732.0,1497732.0,4526.6
46,SRR24759616_binette_bin12,Bacteria,Bacillota,Clostridia,Lachnospirales,Lachnospiraceae,Mobilisporobacter,unclassified,1,64.9,...,34.07,361.0,951.0,8056.0,2127.0,1171.0,2321963.0,2321963.0,2321963.0,2541.7
47,SRR24759608_binette_bin15,Bacteria,Bacillota,Bacilli,Lactobacillales,Lactobacillaceae,Lactobacillus,Lactobacillus panisapium,1,64.4,...,38.48,155.0,437.0,11248.0,3058.0,1339.0,1431279.0,1431279.0,1431279.0,3554.9
48,SRR24759600_binette_bin24,Bacteria,Pseudomonadota,Gammaproteobacteria,Enterobacterales,Enterobacteriaceae,Providencia,unclassified,1,62.2,...,42.39,356.0,892.0,14963.0,3068.0,1518.0,3086716.0,3086716.0,3086716.0,3496.4
49,SRR24759604_binette_bin21,Bacteria,Actinomycetota,Actinomycetes,Actinomycetales,Bifidobacteriaceae,Bombiscardovia,unclassified,1,61.3,...,62.48,327.0,777.0,8616.0,1464.0,1071.0,1401669.0,1401669.0,1401669.0,1863.4
50,SRR24759600_binette_bin25,Bacteria,Bacillota,Bacilli,Lactobacillales,Lactobacillaceae,Lactobacillus,unclassified,1,57.2,...,36.03,72.0,182.0,18081.0,5577.0,3282.0,1188960.0,1188960.0,1188960.0,6688.4
51,SRR24759609_binette_bin15,Bacteria,Bacillota,Bacilli,Lactobacillales,Lactobacillaceae,Lactobacillus,Lactobacillus juensis,1,52.7,...,36.27,98.0,325.0,26053.0,3310.0,1224.0,1115267.0,1115267.0,1115267.0,4866.1
52,SRR24759600_binette_bin26,Bacteria,Pseudomonadota,Gammaproteobacteria,Enterobacterales,Enterobacteriaceae,Providencia,unclassified,1,52.2,...,43.95,93.0,209.0,3908.0,1574.0,1098.0,380499.0,380499.0,380499.0,1700.7
53,SRR24759616_binette_bin16,Bacteria,Pseudomonadota,Alphaproteobacteria,Rhizobiales,Rhizobiaceae,Bartonella_A,unclassified,1,52.0,...,45.36,127.0,303.0,12328.0,3803.0,2754.0,1404230.0,1404230.0,1404230.0,4625.3
54,SRR24759607_binette_bin9,Bacteria,Pseudomonadota,Alphaproteobacteria,Rhizobiales,Rhizobiaceae,Bartonella_A,Bartonella_A apis,21,51.9,...,45.53,35.0,107.0,34814.0,10340.0,4496.0,1273561.0,1273561.0,1273561.0,13967.9

Total number: 55.0
Cluster members: 9.13 ± 8.31, Median: 6.00, IQR: 1.50-14.00, Range: 1.00-31.00
Contamination: 2.55 ± 2.71, Median: 1.62, IQR: 0.52-3.34, Range: 0.03-9.55
Completeness: 84.51 ± 15.99, Median: 89.10, IQR: 72.75-99.70, Range: 51.90-100.00
Total length: 2.40 ± 1.05, Median: 2.24, IQR: 1.54-2.97, Range: 0.38-5.48

In [16]:
print(f"Total number of MAGs: {mq_df['Cluster members'].sum()}")
print(f"Percentage with completeness > 90%: {mq_df.query("Completeness > 90").shape[0] / mq_df.shape[0] * 100}")

Total number of MAGs: 502
Percentage with completeness > 90%: 47.27272727272727

In [17]:
print("Species-level clusters with contamination >= 10% and completeness > 50%:")
tmp_df = reps_df.query("Contamination >= 10 and Completeness > 50")
display(tmp_df)
print(f"Contamination: {tmp_df['Contamination'].iloc[0]}")

Species-level clusters with contamination >= 10% and completeness > 50%:

Empty DataFrame
Columns: [MAG, Domain, Phylum, Class, Order, Family, Genus, Species, Cluster members, Completeness, Contamination, # N's per 100 kbp, # contigs, # contigs (>= 0 bp), # contigs (>= 1000 bp), GC (%), L50, L90, Largest contig, N50, N90, Total length, Total length (>= 0 bp), Total length (>= 1000 bp), auN, bakta_CDSs, bakta_CRISPR arrays, bakta_gaps, bakta_hypotheticals, bakta_ncRNA regions, bakta_ncRNAs, bakta_oriCs, bakta_oriTs, bakta_oriVs, bakta_pseudogenes, bakta_rRNAs, bakta_sORFs, bakta_signal peptides, bakta_tRNAs, bakta_tmRNAs, Strain heterogeneity, # markers, # marker sets, coverm_mean_coverage, kegg_3-Hydroxypropionate bi-cycle, kegg_ADP-L-glycero-D-manno-heptose biosynthesis, kegg_Acetyl-CoA pathway, CO2 => acetyl-CoA, kegg_Acylglycerol degradation, kegg_Adenine ribonucleotide biosynthesis, IMP => ADP,ATP, kegg_Adenine ribonucleotide degradation, AMP => Urate, kegg_Aerobactin biosynthesis, lysine => aerobactin, kegg_Anammox, nitrite + ammonia => nitrogen, kegg_Anthranilate degradation, anthranilate => catechol, kegg_Arginine biosynthesis, glutamate => acetylcitrulline => arginine, kegg_Arginine biosynthesis, ornithine => arginine, kegg_Arginine succinyltransferase pathway, arginine => glutamate, kegg_Ascorbate biosynthesis, animals, glucose-1P => ascorbate, kegg_Ascorbate biosynthesis, plants, fructose-6P => ascorbate, kegg_Ascorbate degradation, ascorbate => D-xylulose-5P, kegg_Assimilatory nitrate reduction, nitrate => ammonia, kegg_Assimilatory sulfate reduction, plants, sulfate => H2S, kegg_Assimilatory sulfate reduction, sulfate => H2S, kegg_Aurachin biosynthesis, anthranilate => aurachin A, kegg_Bacillus anthracis pathogenicity signature, anthrax toxin, kegg_Bacillus anthracis pathogenicity signature, polyglutamic acid capsule biosynthesis, kegg_Bacilysin biosynthesis, prephenate => bacilysin, kegg_Benzene degradation, benzene => catechol, kegg_Benzoate degradation, benzoate => catechol / methylbenzoate => methylcatechol, kegg_Benzoate degradation, cyclohexanecarboxylic acid =>pimeloyl-CoA, kegg_Benzoyl-CoA degradation, benzoyl-CoA => 3-hydroxypimeloyl-CoA, kegg_Betacyanin biosynthesis, L-tyrosine => amaranthin, kegg_Betaine biosynthesis, choline => betaine, kegg_Betaine degradation, bacteria, betaine => pyruvate, kegg_Betaine metabolism, animals, betaine => glycine, kegg_Biotin biosynthesis, BioI pathway, long-chain-acyl-ACP => pimeloyl-ACP => biotin, kegg_Biotin biosynthesis, BioU pathway, pimeloyl-ACP/CoA => biotin, kegg_Biotin biosynthesis, BioW pathway, pimelate => pimeloyl-CoA => biotin, kegg_Biotin biosynthesis, pimeloyl-ACP/CoA => biotin, kegg_Biphenyl degradation, biphenyl => 2-oxopent-4-enoate + benzoate, kegg_C1-unit interconversion, eukaryotes, kegg_C1-unit interconversion, prokaryotes, kegg_C10-C20 isoprenoid biosynthesis, archaea, kegg_C10-C20 isoprenoid biosynthesis, bacteria, kegg_C10-C20 isoprenoid biosynthesis, non-plant eukaryotes, kegg_C10-C20 isoprenoid biosynthesis, plants, kegg_C4-dicarboxylic acid cycle, NAD - malic enzyme type, kegg_C4-dicarboxylic acid cycle, NADP - malic enzyme type, kegg_C4-dicarboxylic acid cycle, phosphoenolpyruvate carboxykinase type, kegg_C5 isoprenoid biosynthesis, mevalonate pathway, kegg_C5 isoprenoid biosynthesis, mevalonate pathway, archaea, kegg_C5 isoprenoid biosynthesis, non-mevalonate pathway, kegg_CAM (Crassulacean acid metabolism), dark, kegg_CAM (Crassulacean acid metabolism), light, kegg_CMP-KDO biosynthesis, kegg_CMP-Neu5Ac biosynthesis, kegg_Carbapenem resistance, kegg_Catechol meta-cleavage, catechol => acetyl-CoA / 4-methylcatechol => propanoyl-CoA, kegg_Catechol ortho-cleavage, catechol => 3-oxoadipate, kegg_Cationic antimicrobial peptide (CAMP) resistance, VraFG transporter, kegg_Cationic antimicrobial peptide (CAMP) resistance, dltABCD operon, ...]
Index: []

[0 rows x 363 columns]

IndexError: single positional indexer is out-of-bounds

### Taxonomy

In [ ]:
compute_taxo_classification_summary(mq_df)

,Unclassified clusters,Classified clusters,Unclassified clusters %,Classified clusters %
Domain,0,55,0.0,100.0
Phylum,0,55,0.0,100.0
Class,0,55,0.0,100.0
Order,0,55,0.0,100.0
Family,0,55,0.0,100.0
Genus,0,55,0.0,100.0
Species,10,45,18.18,81.82

In [ ]:
mq_taxo_levels = get_all_taxo_levels(mq_df)

Level: Domain

          Cluster  Cluster %  Total MAG count
Domain
Bacteria     55.0      100.0            502.0
TOTAL        55.0      100.0            502.0

Level: Phylum

                Cluster   Cluster %  Total MAG count
Phylum
Pseudomonadota     32.0   58.181818            273.0
Bacillota          20.0   36.363636            187.0
Actinomycetota      2.0    3.636364             32.0
Bacteroidota        1.0    1.818182             10.0
TOTAL              55.0  100.000000            502.0

Level: Class

                     Cluster   Cluster %  Total MAG count
Class
Gammaproteobacteria     26.0   47.272727            193.0
Bacilli                 14.0   25.454545            160.0
Alphaproteobacteria      6.0   10.909091             80.0
Actinomycetes            2.0    3.636364             32.0
Clostridia               6.0   10.909091             27.0
Bacteroidia              1.0    1.818182             10.0
TOTAL                   55.0  100.000000            502.0

Level: Order

                    Cluster   Cluster %  Total MAG count
Order
Lactobacillales        13.0   23.636364            159.0
Enterobacterales       18.0   32.727273            124.0
Rhizobiales             6.0   10.909091             80.0
Burkholderiales         3.0    5.454545             49.0
Actinomycetales         2.0    3.636364             32.0
Lachnospirales          4.0    7.272727             20.0
Pseudomonadales         4.0    7.272727             18.0
Flavobacteriales        1.0    1.818182             10.0
Tissierellales          2.0    3.636364              7.0
Enterobacterales_A      1.0    1.818182              2.0
Bacillales_D            1.0    1.818182              1.0
TOTAL                  55.0  100.000000            502.0

Level: Family

                      Cluster   Cluster %  Total MAG count
Family
Lactobacillaceae         12.0   21.818182            146.0
Enterobacteriaceae       18.0   32.727273            124.0
Rhizobiaceae              6.0   10.909091             80.0
Neisseriaceae             3.0    5.454545             49.0
Bifidobacteriaceae        2.0    3.636364             32.0
Lachnospiraceae           4.0    7.272727             20.0
Pseudomonadaceae          4.0    7.272727             18.0
Enterococcaceae           1.0    1.818182             13.0
Weeksellaceae             1.0    1.818182             10.0
Tissierellaceae           1.0    1.818182              4.0
Tepidimicrobiaceae        1.0    1.818182              3.0
Enterobacteriaceae_A      1.0    1.818182              2.0
Amphibacillaceae          1.0    1.818182              1.0
TOTAL                    55.0  100.000000            502.0

Level: Genus

                     Cluster   Cluster %  Total MAG count
Genus
Bartonella_A             6.0   10.909091             80.0
Lactobacillus            7.0   12.727273             66.0
Gilliamella              7.0   12.727273             62.0
Snodgrassella            3.0    5.454545             49.0
Apilactobacillus         3.0    5.454545             48.0
Bombiscardovia           2.0    3.636364             32.0
Frischella               1.0    1.818182             21.0
Fructobacillus           1.0    1.818182             21.0
Entomomonas              4.0    7.272727             18.0
Novisyntrophococcus      2.0    3.636364             17.0
Proteus                  1.0    1.818182             15.0
Enterococcus             1.0    1.818182             13.0
Klebsiella               2.0    3.636364             12.0
Bombilactobacillus       1.0    1.818182             11.0
Apibacter                1.0    1.818182             10.0
Providencia              5.0    9.090909              9.0
CABMKH01                 1.0    1.818182              4.0
Morganella               1.0    1.818182              4.0
Schnuerera               1.0    1.818182              3.0
Mobilisporobacter        2.0    3.636364              3.0
Arsenophonus             1.0    1.818182              2.0
Serratia                 1.0    1.818182              1.0
Virgibacillus            1.0    1.818182              1.0
TOTAL                   55.0  100.000000            502.0

Level: Species

                                    Cluster   Cluster %  Total MAG count
Species
Snodgrassella alvi                      2.0    3.636364             39.0
Bombiscardovia coryneforme              1.0    1.818182             31.0
Bartonella_A sp945285915                1.0    1.818182             25.0
Lactobacillus apis                      1.0    1.818182             25.0
unclassified                           10.0   18.181818             24.0
Apilactobacillus kunkeei_C              1.0    1.818182             21.0
Fructobacillus fructosus                1.0    1.818182             21.0
Frischella perrara                      1.0    1.818182             21.0
Bartonella_A apis                       1.0    1.818182             21.0
Bartonella_A choladocola                1.0    1.818182             21.0
Apilactobacillus kunkeei                1.0    1.818182             18.0
Lactobacillus helsingborgensis          1.0    1.818182             18.0
Lactobacillus melliventris              1.0    1.818182             18.0
Gilliamella apicola                     1.0    1.818182             16.0
Proteus mirabilis                       1.0    1.818182             15.0
Enterococcus faecalis                   1.0    1.818182             13.0
Novisyntrophococcus liquoris            1.0    1.818182             12.0
Gilliamella apicola_R                   1.0    1.818182             12.0
Bombilactobacillus mellis               1.0    1.818182             11.0
Klebsiella oxytoca                      1.0    1.818182             11.0
Gilliamella apis_A                      1.0    1.818182             10.0
Apibacter sp945280365                   1.0    1.818182             10.0
Snodgrassella alvi_G                    1.0    1.818182             10.0
Gilliamella apicola_N                   1.0    1.818182              9.0
Apilactobacillus apinorum               1.0    1.818182              9.0
Entomomonas sp040391985                 1.0    1.818182              7.0
Gilliamella sp945271295                 1.0    1.818182              6.0
Entomomonas sp945283395                 1.0    1.818182              6.0
Gilliamella sp946480175                 1.0    1.818182              5.0
Novisyntrophococcus fermenticellae      1.0    1.818182              5.0
Gilliamella apis                        1.0    1.818182              4.0
Morganella sibonii                      1.0    1.818182              4.0
CABMKH01 sp040797625                    1.0    1.818182              4.0
Providencia alcalifaciens               1.0    1.818182              4.0
Schnuerera sp021655095                  1.0    1.818182              3.0
Providencia rettgeri                    1.0    1.818182              2.0
Lactobacillus kimbladii                 1.0    1.818182              2.0
Arsenophonus apicola                    1.0    1.818182              2.0
Providencia hangzhouensis               1.0    1.818182              1.0
Entomomonas moraniae                    1.0    1.818182              1.0
Lactobacillus panisapium                1.0    1.818182              1.0
Lactobacillus juensis                   1.0    1.818182              1.0
Serratia ureilytica                     1.0    1.818182              1.0
Virgibacillus proomii_B                 1.0    1.818182              1.0
Klebsiella grimontii                    1.0    1.818182              1.0
TOTAL                                  55.0  100.000000            502.0

### Relative abundance

In [ ]:
coverage_df.sum(axis = 0)

Genome         SRR24759596_binette_bin14SRR24759596_binette_b...
SRR24759596                                           100.000022
SRR24759597                                            99.999999
SRR24759598                                           100.000002
SRR24759599                                           100.000021
SRR24759600                                            99.999989
SRR24759601                                            99.999986
SRR24759602                                            99.999976
SRR24759603                                            99.999993
SRR24759604                                           100.000004
SRR24759605                                            99.999969
SRR24759606                                           100.000002
SRR24759607                                            99.999939
SRR24759608                                            99.999994
SRR24759609                                            99.999994
SRR24759610                                           100.000016
SRR24759611                                            99.999995
SRR24759612                                            99.999991
SRR24759613                                           100.000037
SRR24759614                                           100.000019
SRR24759615                                            99.999999
SRR24759616                                            99.999984
dtype: object

In [ ]:
mq_relative_abund_df = get_relative_abund_taxo_levels(mq_df, coverage_df)

Unmapped reads: 94.72 ± 0.74, Median: 94.64, IQR: 94.51-95.21, Range: 93.16-96.14
Mapped reads: 5.28 ± 0.74, Median: 5.36, IQR: 4.79-5.49, Range: 3.86-6.84

Level: Family

,count,mean,std,min,25%,50%,75%,max
Family,,,,,,,,
Rhizobiaceae,21.0,39.933185,8.488771,23.692706,36.629487,38.634787,45.882505,54.384166
Enterobacteriaceae,21.0,19.281281,7.938614,10.553313,12.767441,17.328938,22.154953,39.679560
Lactobacillaceae,21.0,18.567806,6.189108,9.888856,13.634893,18.095523,24.269254,29.412377
Neisseriaceae,21.0,9.300887,3.774104,3.788924,6.737237,8.056038,11.309013,16.920375
Bifidobacteriaceae,21.0,6.571252,1.919659,3.031209,5.224637,6.664261,7.593636,10.280471
Pseudomonadaceae,21.0,2.564322,4.532568,0.000000,0.304664,0.471974,1.634241,18.536682
Enterobacteriaceae_A,21.0,1.137010,4.718352,0.000000,0.000000,0.072763,0.112759,21.714889
Lachnospiraceae,21.0,1.081796,0.811391,0.113138,0.542661,0.822172,1.409544,2.718123
Enterococcaceae,21.0,0.593728,0.375211,0.000000,0.287381,0.662040,0.904267,1.099946
Weeksellaceae,21.0,0.527905,0.547140,0.000000,0.075586,0.222540,0.919982,1.733917
Tissierellaceae,21.0,0.179743,0.193978,0.000000,0.000000,0.152377,0.276370,0.692253
Amphibacillaceae,21.0,0.134138,0.595431,0.000000,0.000000,0.000000,0.000000,2.732181
Tepidimicrobiaceae,21.0,0.126947,0.319116,0.000000,0.000000,0.000000,0.000000,1.106159

Level: Genus

,count,mean,std,min,25%,50%,75%,max
Genus,,,,,,,,
Bartonella_A,21.0,39.933185,8.488771,23.692706,36.629487,38.634787,45.882505,54.384166
Snodgrassella,21.0,9.300887,3.774104,3.788924,6.737237,8.056038,11.309013,16.920375
Lactobacillus,21.0,8.686815,4.312191,3.357225,5.678182,7.808403,11.643675,20.012491
Gilliamella,21.0,8.624825,3.677315,3.777546,5.403355,8.192521,10.102849,16.657112
Apilactobacillus,21.0,7.663114,3.505732,2.899166,5.010373,7.626493,9.526544,15.443960
Bombiscardovia,21.0,6.571252,1.919659,3.031209,5.224637,6.664261,7.593636,10.280471
Frischella,21.0,4.904499,2.817486,0.678462,2.626736,5.219337,6.066495,10.078687
Proteus,21.0,3.778612,4.789999,0.000000,0.286406,2.690407,5.193470,20.732175
Entomomonas,21.0,2.564322,4.532568,0.000000,0.304664,0.471974,1.634241,18.536682
Fructobacillus,21.0,1.686747,0.799478,0.675592,0.945681,1.488228,2.265807,3.391559
Arsenophonus,21.0,1.137010,4.718352,0.000000,0.000000,0.072763,0.112759,21.714889
Novisyntrophococcus,21.0,0.937156,0.736608,0.113138,0.481727,0.736965,0.997982,2.718123
Klebsiella,21.0,0.852812,1.204792,0.000000,0.180319,0.738938,1.009105,5.564201
Providencia,21.0,0.822587,1.151621,0.000000,0.000000,0.287849,1.465136,4.227730
Enterococcus,21.0,0.593728,0.375211,0.000000,0.287381,0.662040,0.904267,1.099946
Bombilactobacillus,21.0,0.531130,0.364134,0.066736,0.262953,0.391312,0.800356,1.410896
Apibacter,21.0,0.527905,0.547140,0.000000,0.075586,0.222540,0.919982,1.733917
Morganella,21.0,0.228446,0.300915,0.000000,0.053604,0.136231,0.299079,1.380860
CABMKH01,21.0,0.179743,0.193978,0.000000,0.000000,0.152377,0.276370,0.692253
Mobilisporobacter,21.0,0.144640,0.254955,0.000000,0.000000,0.065402,0.131315,1.034913
Virgibacillus,21.0,0.134138,0.595431,0.000000,0.000000,0.000000,0.000000,2.732181
Schnuerera,21.0,0.126947,0.319116,0.000000,0.000000,0.000000,0.000000,1.106159
Serratia,21.0,0.069499,0.244756,0.000000,0.000000,0.000000,0.000000,1.116289

Level: Species

,count,mean,std,min,25%,50%,75%,max
Species,,,,,,,,
Bartonella_A apis,21.0,18.105650,5.827651,7.284061,13.620204,18.639473,22.013584,28.074819
unclassified,21.0,16.024845,4.108555,8.777573,13.323157,15.634861,19.846587,21.699546
Snodgrassella alvi,21.0,8.867582,3.844630,3.174792,6.416765,7.996016,11.145363,16.448275
Bombiscardovia coryneforme,21.0,5.326927,1.832209,2.412764,4.199604,5.518682,6.408748,9.221914
Bartonella_A choladocola,21.0,5.250051,3.358266,0.672405,2.424867,5.188492,7.967951,12.671047
Frischella perrara,21.0,4.904499,2.817486,0.678462,2.626736,5.219337,6.066495,10.078687
Apilactobacillus kunkeei_C,21.0,4.562437,2.329265,1.299992,3.106854,3.590075,5.892711,10.087480
Lactobacillus apis,21.0,4.329794,1.850723,1.931973,2.871670,3.836876,5.796339,8.093410
Bartonella_A sp945285915,21.0,3.941935,1.566374,1.511453,2.970491,3.739962,4.962113,7.708951
Proteus mirabilis,21.0,3.778612,4.789999,0.000000,0.286406,2.690407,5.193470,20.732175
Apilactobacillus kunkeei,21.0,2.620187,1.344376,1.257868,1.512840,2.247770,3.109673,6.743996
Gilliamella apis_A,21.0,2.186720,1.998418,0.446680,0.962024,1.210123,2.301238,7.390704
Gilliamella apis,21.0,1.880692,0.960537,0.632743,1.260417,1.710567,2.268179,4.225934
Fructobacillus fructosus,21.0,1.686747,0.799478,0.675592,0.945681,1.488228,2.265807,3.391559
Lactobacillus melliventris,21.0,1.407348,1.404296,0.223415,0.474876,1.069769,1.631128,6.596615
Lactobacillus helsingborgensis,21.0,1.258040,1.072503,0.301096,0.521220,0.737520,1.819580,4.467521
Gilliamella apicola,21.0,1.159509,0.458060,0.382806,0.718368,1.215284,1.434801,1.978096
Arsenophonus apicola,21.0,1.137010,4.718352,0.000000,0.000000,0.072763,0.112759,21.714889
Gilliamella sp945271295,21.0,1.109058,1.694330,0.000000,0.057200,0.186002,2.131001,5.556247
Gilliamella apicola_N,21.0,1.044438,0.940301,0.281354,0.496871,0.796134,1.257490,4.613014
Entomomonas sp040391985,21.0,0.936121,2.353878,0.000000,0.000000,0.043703,0.318694,10.113584
Klebsiella oxytoca,21.0,0.812137,1.212932,0.000000,0.127513,0.726157,1.009105,5.564201
Novisyntrophococcus liquoris,21.0,0.712669,0.647049,0.113138,0.305995,0.523141,0.803480,2.536002
Gilliamella apicola_R,21.0,0.679977,0.543444,0.097797,0.342587,0.509882,0.890070,2.571849
Enterococcus faecalis,21.0,0.593728,0.375211,0.000000,0.287381,0.662040,0.904267,1.099946
Gilliamella sp946480175,21.0,0.564432,0.796333,0.151938,0.220917,0.241988,0.570892,3.754893
Bombilactobacillus mellis,21.0,0.531130,0.364134,0.066736,0.262953,0.391312,0.800356,1.410896
Apibacter sp945280365,21.0,0.527905,0.547140,0.000000,0.075586,0.222540,0.919982,1.733917
Lactobacillus kimbladii,21.0,0.526851,0.501263,0.072761,0.215362,0.393024,0.639227,2.251322
Apilactobacillus apinorum,21.0,0.480490,0.573464,0.000000,0.077453,0.247925,0.520464,2.178975
Entomomonas moraniae,21.0,0.444840,1.767031,0.000000,0.000000,0.041266,0.114107,8.150488
Snodgrassella alvi_G,21.0,0.433305,0.279731,0.060022,0.225247,0.350422,0.560296,1.047456
Providencia alcalifaciens,21.0,0.304373,0.658190,0.000000,0.000000,0.043897,0.217606,2.836778
Lactobacillus juensis,21.0,0.276064,0.345806,0.048077,0.122142,0.149232,0.288985,1.594631
Entomomonas sp945283395,21.0,0.251386,0.314673,0.000000,0.000000,0.179441,0.263482,1.080535
Morganella sibonii,21.0,0.228446,0.300915,0.000000,0.053604,0.136231,0.299079,1.380860
Novisyntrophococcus fermenticellae,21.0,0.224488,0.260429,0.000000,0.066765,0.146477,0.298898,1.002474
CABMKH01 sp040797625,21.0,0.179743,0.193978,0.000000,0.000000,0.152377,0.276370,0.692253
Providencia rettgeri,21.0,0.162537,0.431520,0.000000,0.000000,0.000000,0.032463,1.717919
Providencia hangzhouensis,21.0,0.148466,0.517650,0.000000,0.000000,0.000000,0.025835,2.369364
Virgibacillus proomii_B,21.0,0.134138,0.595431,0.000000,0.000000,0.000000,0.000000,2.732181
Schnuerera sp021655095,21.0,0.126947,0.319116,0.000000,0.000000,0.000000,0.000000,1.106159
Serratia ureilytica,21.0,0.069499,0.244756,0.000000,0.000000,0.000000,0.000000,1.116289
Klebsiella grimontii,21.0,0.040675,0.155836,0.000000,0.000000,0.000000,0.000000,0.713549
Lactobacillus panisapium,21.0,0.027573,0.126354,0.000000,0.000000,0.000000,0.000000,0.579028

In [ ]:
run_to_replicate = metadata_df.set_index("Run accession")["Replicate"].to_dict()
mq_relative_abund_df = mq_relative_abund_df.rename(
    columns={
        column: run_to_replicate[column]
        for column in mq_relative_abund_df.columns
        if column.startswith("SRR") and column in run_to_replicate
    }
)

mq_relative_abund_df =mq_relative_abund_df[[*sample_order]]
mq_relative_abund_df.head()

#### Relative abundance of control data

In [ ]:
control_species_abund_df = mq_relative_abund_df[["C1", "C2", "C3"]]
control_species_abund_df.T.describe().T.sort_values(by="mean", ascending=False)

In [ ]:
control_species_abund_df.xs("Bartonella_A", level=1, axis=0, drop_level=False).sum(axis=0).describe()

#### Relative abundance of all experimental conditions

In [ ]:
print("Proteus mirabilis")
print("Control samples:")
control_species_abund_df = mq_relative_abund_df[["C1", "C2", "C3"]]
display(control_species_abund_df.T.describe().T.sort_values(by="mean", ascending=False).xs("Proteus mirabilis", level=2, axis=0, drop_level=False))
print("Infected samples:")
infected_species_abund_df = mq_relative_abund_df[["N1", "N2", "N3"]]
display(infected_species_abund_df.T.describe().T.sort_values(by="mean", ascending=False).xs("Proteus mirabilis", level=2, axis=0, drop_level=False))

In [ ]:
arsenophonus_abund_df = mq_relative_abund_df.xs("Arsenophonus apicola", level=2, axis=0, drop_level=False).T
print(f"Abundance for Arsenophonus apicola in TP2: {arsenophonus_abund_df.loc['TP2'].values[0]}")
print("Abundance for Arsenophonus apicola without TP2 sample: ")
arsenophonus_abund_df.drop(["TP2"]).describe().T

In [ ]:
family_colors = {
    "Rhizobiaceae": "sandybrown",  # Bartonellaceae
    "Neisseriaceae": "violet",
    "Enterobacteriaceae": "dodgerblue",  # Orbaceae
    "Lactobacillaceae": "red",
    "Leuconostocaceae": "orange",
    "Bifidobacteriaceae": "limegreen",
    # not in the original paper
    "Pseudomonadaceae": "cyan",
    "Lachnospiraceae": "lightyellow",
    "Weeksellaceae": "brown",
    "Enterococcaceae": "lightcoral",
    "Tepidimicrobiaceae": "lightgreen",
    "Amphibacillaceae": "lightblue",
}

def make_family_shades(base_color, n):
    if n <= 1:
        return [mcolors.to_hex(base_color)]
    base_rgb = np.array(mcolors.to_rgb(base_color))
    white = np.array([1.0, 1.0, 1.0])
    factors = np.linspace(0.0, 0.5, n)
    return [mcolors.to_hex(base_rgb * (1 - f) + white * f) for f in factors]

def make_color_gradient(start_color, end_color, n):
    if n <= 1:
        return [mcolors.to_hex(start_color)]
    start_rgb = np.array(mcolors.to_rgb(start_color))
    end_rgb = np.array(mcolors.to_rgb(end_color))
    factors = np.linspace(0.0, 1.0, n)
    return [mcolors.to_hex(start_rgb * (1 - f) + end_rgb * f) for f in factors]

family_order = list(family_colors.keys())
family_rank = {family: rank for rank, family in enumerate(family_order)}

# Reorder species rows so stacked bars follow the requested family order
index_df = mq_relative_abund_df.index.to_frame(index=False)
index_df["sort_rank"] = index_df["Family"].map(family_rank).fillna(len(family_order)).astype(int)
index_df = index_df.sort_values(["sort_rank", "Family", "Genus", "Species"], kind="stable")
ordered_index = pd.MultiIndex.from_frame(index_df[["Family", "Genus", "Species"]])
species_abund_df_ordered = mq_relative_abund_df.loc[ordered_index]

# Default colors: same family hue, different shade within family
default_color_map = {}
for family_name, group in index_df.groupby("Family", sort=False):
    base_color = family_colors.get(family_name, "gray")
    shades = make_family_shades(base_color, len(group))
    for (_, row), shade in zip(group.iterrows(), shades):
        default_color_map[(row["Family"], row["Genus"], row["Species"])] = shade

# Special overrides requested by user
providencia_count = index_df["Genus"].astype(str).str.lower().str.startswith("providencia").sum()
providencia_shades = iter(make_color_gradient("#c4a484", "#654321", providencia_count))

species_colors = []
for _, row in index_df.iterrows():
    family_name = row["Family"]
    genus_name = str(row["Genus"]).strip().lower()
    species_name = str(row["Species"]).strip().lower()
    key = (row["Family"], row["Genus"], row["Species"])
    if genus_name.startswith("arsenophonus") and species_name == "apicola":
        color = "black"
    elif genus_name.startswith("proteus"):
        color = "#c4a484"  # light brown
    elif genus_name.startswith("providencia"):
        color = next(providencia_shades)
    else:
        color = default_color_map.get(key, family_colors.get(family_name, "gray"))
    species_colors.append(color)

sample_matrix = mq_relative_abund_df.select_dtypes(include=[np.number]).T
scaled_sample_matrix = StandardScaler().fit_transform(sample_matrix)
pca = PCA(n_components=2)
sample_scores = pca.fit_transform(scaled_sample_matrix)
species_loadings = pca.components_.T * np.sqrt(pca.explained_variance_)

sample_scores_df = pd.DataFrame(sample_scores, index=sample_matrix.index, columns=["PC1", "PC2"])
sample_scores_df["Category"] = (
    sample_scores_df.index.to_series()
    .str.extract(r"^(NT|NP|TP|C|T|P|N)", expand=False)
    .fillna("Other")
)

category_palette = {
    "C": "#000000",
    "T": "#7b2cbf",
    "P": "#c77dff",
    "N": "#ff69b4",
    "NT": "#00bcd4",
    "NP": "#2e8b57",
    "TP": "#d4af37",
    "Other": "#6c757d",
}

species_contribution = np.linalg.norm(species_loadings, axis=1)
contribution_norm = plt.Normalize(species_contribution.min(), species_contribution.max())
arrow_cmap = LinearSegmentedColormap.from_list("cyan_orange", ["#00bcd4", "#ff8c00"])
arrow_colors = arrow_cmap(contribution_norm(species_contribution))

top_species_idx = np.argsort(species_contribution)[-20:]
score_limit = np.abs(sample_scores_df[["PC1", "PC2"]].to_numpy()).max()
loading_limit = np.abs(species_loadings[top_species_idx]).max()
arrow_scale = 1.0 if loading_limit == 0 else (score_limit / loading_limit) * 0.8

fig, (ax_a, ax_b) = plt.subplots(2, 1, figsize=(16, 18), gridspec_kw={"height_ratios": [1.2, 1]})

# (A) Relative abundance stacked bars
species_abund_df_ordered.T.plot(
    kind="bar",
    stacked=True,
    ax=ax_a,
    color=species_colors,
    width=0.85,
    legend=False,
)
ax_a.set_ylabel("Relative abundance (%)")
ax_a.set_ylim(0, 100)
ax_a.tick_params(axis="x", rotation=45)
present_families = [family for family in family_order if family in set(index_df["Family"])]
legend_handles = [
    Patch(facecolor=family_colors.get(family, "gray"), label=family)
    for family in present_families
]
right_margin_x = 1.05
ax_a.legend(handles=legend_handles, title="Family", bbox_to_anchor=(right_margin_x-0.01, 1), loc="upper left")
ax_a.text(-0.05, 1.04, "(A)", transform=ax_a.transAxes, fontsize=25, fontweight="bold")

# (B) PCA biplot
for category, frame in sample_scores_df.groupby("Category", sort=False):
    ax_b.scatter(
        frame["PC1"],
        frame["PC2"],
        s=90,
        color=category_palette.get(category, category_palette["Other"]),
        label=category,
        alpha=0.9,
    )
    for sample_name, row in frame.iterrows():
        ax_b.text(row["PC1"], row["PC2"], sample_name, fontsize=9, ha="left", va="bottom")

for idx in top_species_idx:
    species_name = mq_relative_abund_df.index[idx][2]
    x_loading = species_loadings[idx, 0] * arrow_scale
    y_loading = species_loadings[idx, 1] * arrow_scale
    ax_b.arrow(
        0,
        0,
        x_loading,
        y_loading,
        color=arrow_colors[idx],
        alpha=0.85,
        width=0.002,
        head_width=0.08,
        length_includes_head=True,
    )
    ax_b.text(x_loading * 1.05, y_loading * 1.05, species_name, color=arrow_colors[idx], fontsize=8)

explained_variance = pca.explained_variance_ratio_ * 100
ax_b.axhline(0, color="lightgray", linewidth=1)
ax_b.axvline(0, color="lightgray", linewidth=1)
ax_b.set_xlabel(f"PC1 ({explained_variance[0]:.1f}% variance)")
ax_b.set_ylabel(f"PC2 ({explained_variance[1]:.1f}% variance)")
ax_b.legend(title="Conditions")
ax_b.text(-0.05, 1.04, "(B)", transform=ax_b.transAxes, fontsize=25, fontweight="bold")

sm = plt.cm.ScalarMappable(cmap=arrow_cmap, norm=contribution_norm)
sm.set_array([])
cax_b = ax_b.inset_axes([right_margin_x, 0.0, 0.035, 1.0])
fig.colorbar(sm, cax=cax_b, label="Species contribution magnitude")

plt.tight_layout()
png_fp = result_dp / "mq_combined_relative_abundance_pca.png"
fig.savefig(png_fp, dpi=300, bbox_inches="tight")
print(f"Saved combined figure to: {png_fp}")
plt.show()

sample_scores_df

In [ ]:
sample_scores_df

### Functions

In [ ]:
print_stats(get_bakta_annot_df(mq_df).describe())

In [ ]:
mq_kegg_module_df = get_kegg_path_df(mq_df)

In [ ]:
# Count how many KEGG pathways reach a given completeness threshold for each MAG
thresholds = [50, 75, 100]
kegg_path_counts_df = pd.DataFrame(index=mq_kegg_module_df.index)

for threshold in thresholds:
    kegg_path_counts_df[f"Modules with completeness >= {threshold}%"] = (mq_kegg_module_df >= threshold).sum(axis=1)

kegg_path_counts_df = kegg_path_counts_df.sort_values(by="Modules with completeness >= 50%", ascending=False)
kegg_path_counts_df.describe()

In [ ]:
# Count in how many MAGs a KEGG pathway reaches a given completeness threshold
kegg_pathway_mag_counts_df = pd.DataFrame(index=mq_kegg_module_df.columns)

for threshold in thresholds:
    kegg_pathway_mag_counts_df[f"MAGs with completeness >= {threshold}%"] = (mq_kegg_module_df >= threshold).sum(axis=0)

kegg_pathway_mag_counts_df = kegg_pathway_mag_counts_df.sort_values(by="MAGs with completeness >= 50%", ascending=False)
kegg_pathway_mag_counts_df

In [ ]:
print(f"Number of pathways with completeness < 50% in all MAG: {((mq_kegg_module_df < 50).all(axis=0)).sum()}")
print(f"Number of pathways with completeness < 75% in all MAG: {((mq_kegg_module_df < 75).all(axis=0)).sum()}")
print(f"Number of pathways with completeness >= 50 % in all MAG: {((mq_kegg_module_df >= 50).all(axis=0)).sum()}")
print(f"Number of pathways with completeness >= 75 % in all MAG: {((mq_kegg_module_df >= 75).all(axis=0)).sum()}")

In [ ]:
kegg_pathway_mag_counts_df.index[kegg_pathway_mag_counts_df.iloc[:, 0].eq(32)].tolist()

### LQ: Low-quality species-level clusters (contamination < 10% and completeness < 50%)

In [ ]:
lq_df = reps_df.query("Contamination < 10 and Completeness < 50")
compute_print_stats(lq_df)

Total number: 683.0
Cluster members: 1.33 ± 1.28, Median: 1.00, IQR: 1.00-1.00, Range: 1.00-15.00
Contamination: 1.02 ± 1.78, Median: 0.28, IQR: 0.05-0.95, Range: 0.00-9.97
Completeness: 12.57 ± 7.99, Median: 10.00, IQR: 7.45-14.30, Range: 2.20-44.90
Total length: 0.42 ± 0.29, Median: 0.32, IQR: 0.23-0.50, Range: 0.05-2.85

## Relative abundance with all MAGs

In [ ]:
abund_df = get_relative_abund_taxo_levels(reps_df, coverage_df)

Unmapped reads: 3.92 ± 1.48, Median: 3.55, IQR: 2.65-4.53, Range: 2.27-7.33
Mapped reads: 96.08 ± 1.48, Median: 96.45, IQR: 95.47-97.35, Range: 92.67-97.73

Level: Family

,count,mean,std,min,25%,50%,75%,max
Family,,,,,,,,
unclassified,21.0,68.993060,0.801637,67.706100,68.482677,68.946322,69.572617,70.726123
Rhizobiaceae,21.0,24.205092,2.026092,19.747549,23.040722,24.629234,25.469066,26.860894
Enterobacteriaceae,21.0,2.692827,1.176457,1.097040,1.825380,2.439653,3.470866,5.084927
Lactobacillaceae,21.0,2.064469,0.780524,0.890313,1.458346,2.120805,2.434941,3.729408
Bifidobacteriaceae,21.0,1.091617,0.299352,0.452932,0.952677,1.126188,1.360408,1.461976
Neisseriaceae,21.0,0.513153,0.231566,0.209821,0.340670,0.441487,0.711693,1.112831
Pseudomonadaceae,21.0,0.193388,0.342908,0.000000,0.022060,0.036614,0.118224,1.396678
Lachnospiraceae,21.0,0.070611,0.054358,0.007141,0.033704,0.053271,0.102711,0.218110
Enterobacteriaceae_A,21.0,0.063034,0.264562,0.000000,0.000000,0.003611,0.008009,1.217241
Enterococcaceae,21.0,0.032572,0.021306,0.000000,0.016177,0.040995,0.048427,0.072342
Weeksellaceae,21.0,0.031021,0.034452,0.000000,0.003942,0.012736,0.057818,0.125707
Tissierellaceae,21.0,0.021291,0.012190,0.008024,0.011018,0.019125,0.027555,0.049728
Cellulomonadaceae,21.0,0.009587,0.005270,0.002576,0.007308,0.008932,0.009962,0.028811
Tepidimicrobiaceae,21.0,0.008588,0.022463,0.000000,0.000000,0.000000,0.000000,0.080195
Amphibacillaceae,21.0,0.007589,0.028099,0.000000,0.000000,0.000000,0.000000,0.128342
Dysgonomonadaceae,21.0,0.002099,0.008935,0.000000,0.000000,0.000000,0.000000,0.041040

Level: Genus

,count,mean,std,min,25%,50%,75%,max
Genus,,,,,,,,
unclassified,21.0,68.993060,0.801637,67.706100,68.482677,68.946322,69.572617,70.726123
Bartonella_A,21.0,24.205092,2.026092,19.747549,23.040722,24.629234,25.469066,26.860894
Gilliamella,21.0,1.994538,0.872074,0.835127,1.412542,1.793432,2.502388,4.069494
Lactobacillus,21.0,1.338778,0.632049,0.531999,0.836011,1.252768,1.774963,2.798629
Bombiscardovia,21.0,1.091617,0.299352,0.452932,0.952677,1.126188,1.360408,1.461976
Apilactobacillus,21.0,0.577380,0.288948,0.152891,0.371949,0.500931,0.735104,1.334063
Snodgrassella,21.0,0.513153,0.231566,0.209821,0.340670,0.441487,0.711693,1.112831
Proteus,21.0,0.310989,0.401974,0.000000,0.022710,0.242758,0.421694,1.753457
Frischella,21.0,0.265496,0.162995,0.042824,0.160645,0.233868,0.341489,0.694835
Entomomonas,21.0,0.193388,0.342908,0.000000,0.022060,0.036614,0.118224,1.396678
Fructobacillus,21.0,0.091777,0.041511,0.033256,0.052370,0.080785,0.135172,0.157871
Arsenophonus,21.0,0.063034,0.264562,0.000000,0.000000,0.003611,0.008009,1.217241
Novisyntrophococcus,21.0,0.062464,0.050105,0.007141,0.033704,0.053271,0.067895,0.212300
Klebsiella,21.0,0.049023,0.078079,0.000000,0.009140,0.034493,0.058618,0.365950
Providencia,21.0,0.047388,0.064743,0.000000,0.000000,0.015305,0.106220,0.234121
Enterococcus,21.0,0.032572,0.021306,0.000000,0.016177,0.040995,0.048427,0.072342
Apibacter,21.0,0.031021,0.034452,0.000000,0.003942,0.012736,0.057818,0.125707
Xylocopilactobacillus,21.0,0.028579,0.014611,0.013113,0.016772,0.026919,0.035891,0.064381
Bombilactobacillus,21.0,0.027955,0.016502,0.003242,0.014740,0.025900,0.043164,0.056232
Morganella,21.0,0.020965,0.025338,0.000000,0.006660,0.013785,0.030475,0.114148
Tissierella,21.0,0.011155,0.005237,0.006271,0.008309,0.009384,0.011739,0.030732
CABMKH01,21.0,0.010136,0.010986,0.000000,0.000000,0.007134,0.015816,0.033634
Cellulosimicrobium,21.0,0.009587,0.005270,0.002576,0.007308,0.008932,0.009962,0.028811
Schnuerera,21.0,0.008588,0.022463,0.000000,0.000000,0.000000,0.000000,0.080195
Mobilisporobacter,21.0,0.008147,0.014365,0.000000,0.000000,0.004742,0.007156,0.058256
Virgibacillus,21.0,0.006370,0.027961,0.000000,0.000000,0.000000,0.000000,0.128342
Serratia,21.0,0.004428,0.016062,0.000000,0.000000,0.000000,0.000000,0.073417
Dysgonomonas,21.0,0.002099,0.008935,0.000000,0.000000,0.000000,0.000000,0.041040
Oceanobacillus,21.0,0.001219,0.004553,0.000000,0.000000,0.000000,0.000000,0.020483

Level: Species

,count,mean,std,min,25%,50%,75%,max
Species,,,,,,,,
unclassified,21.0,91.916245,1.036553,89.644915,91.630552,92.005193,92.761333,93.570145
Bartonella_A apis,21.0,1.614020,0.380430,0.916821,1.420962,1.545840,1.858835,2.424263
Bartonella_A apihabitans,21.0,0.757591,0.164954,0.429560,0.661898,0.724800,0.876130,1.117705
Bartonella_A sp945285915,21.0,0.712275,0.262820,0.293487,0.517156,0.660128,0.934395,1.189027
Bartonella_A sp016102285,21.0,0.544981,0.145434,0.379138,0.436054,0.503687,0.600050,1.015631
Snodgrassella alvi,21.0,0.488549,0.232452,0.175812,0.320837,0.390595,0.693398,1.081781
Gilliamella apis_A,21.0,0.441183,0.361986,0.097319,0.221143,0.262618,0.474482,1.304318
Apilactobacillus kunkeei_C,21.0,0.372514,0.194887,0.082626,0.252187,0.332862,0.467288,0.917879
Proteus mirabilis,21.0,0.310989,0.401974,0.000000,0.022710,0.242758,0.421694,1.753457
Bombiscardovia coryneforme,21.0,0.294044,0.111407,0.118965,0.197273,0.269667,0.370741,0.514443
Bartonella_A choladocola,21.0,0.293407,0.193320,0.037468,0.138771,0.255403,0.442508,0.688848
Frischella perrara,21.0,0.265496,0.162995,0.042824,0.160645,0.233868,0.341489,0.694835
Lactobacillus apis,21.0,0.241465,0.119629,0.088871,0.152164,0.243551,0.285925,0.571456
Gilliamella apis,21.0,0.232433,0.107162,0.070770,0.143549,0.236696,0.287922,0.408696
Apilactobacillus kunkeei,21.0,0.145684,0.080071,0.061992,0.084300,0.125123,0.147833,0.337620
Gilliamella apicola,21.0,0.125002,0.057321,0.041317,0.076025,0.125974,0.161839,0.251843
Gilliamella apicola_N,21.0,0.103559,0.084616,0.025482,0.044954,0.097333,0.128554,0.395126
Bartonella_A sp946478235,21.0,0.095621,0.050076,0.040078,0.063968,0.082707,0.113940,0.266057
Fructobacillus fructosus,21.0,0.091777,0.041511,0.033256,0.052370,0.080785,0.135172,0.157871
Lactobacillus melliventris,21.0,0.074711,0.069184,0.012372,0.028392,0.053829,0.084773,0.309871
Bartonella_A sp946479275,21.0,0.070229,0.052634,0.024165,0.033517,0.052991,0.078649,0.212391
Lactobacillus helsingborgensis,21.0,0.065173,0.050428,0.018285,0.030641,0.040842,0.104462,0.209859
Bombiscardovia mellis,21.0,0.064663,0.026419,0.016504,0.050896,0.059301,0.080658,0.122603
Gilliamella sp945271295,21.0,0.063785,0.103502,0.000000,0.002816,0.010957,0.091387,0.365427
Arsenophonus apicola,21.0,0.063034,0.264562,0.000000,0.000000,0.003611,0.008009,1.217241
Entomomonas sp040391985,21.0,0.058586,0.163575,0.000000,0.000000,0.002450,0.020116,0.733220
Klebsiella oxytoca,21.0,0.047205,0.078526,0.000000,0.006195,0.029451,0.057749,0.365950
Novisyntrophococcus liquoris,21.0,0.038449,0.031620,0.005467,0.018036,0.027893,0.048791,0.114280
Gilliamella apicola_R,21.0,0.038257,0.031143,0.004896,0.017734,0.031060,0.050305,0.143311
Enterococcus faecalis,21.0,0.032572,0.021306,0.000000,0.016177,0.040995,0.048427,0.072342
Entomomonas moraniae,21.0,0.031194,0.128299,0.000000,0.000000,0.002200,0.006751,0.590899
Gilliamella sp946480175,21.0,0.031184,0.044148,0.006516,0.012650,0.013876,0.033649,0.207937
Apibacter sp945280365,21.0,0.031021,0.034452,0.000000,0.003942,0.012736,0.057818,0.125707
Bombilactobacillus mellis,21.0,0.027955,0.016502,0.003242,0.014740,0.025900,0.043164,0.056232
Lactobacillus kimbladii,21.0,0.027912,0.025331,0.003535,0.012532,0.017816,0.034462,0.113283
Apilactobacillus apinorum,21.0,0.027236,0.032129,0.000000,0.004289,0.014188,0.037733,0.118458
Snodgrassella alvi_G,21.0,0.024604,0.016418,0.002574,0.012565,0.020184,0.034009,0.057920
Providencia alcalifaciens,21.0,0.017986,0.037404,0.000000,0.000000,0.002461,0.015002,0.157094
Entomomonas sp945283395,21.0,0.014795,0.019528,0.000000,0.000000,0.011081,0.014149,0.074493
Lactobacillus juensis,21.0,0.014378,0.015634,0.002336,0.006774,0.008068,0.014225,0.068385
Morganella sibonii,21.0,0.013576,0.020398,0.000000,0.002639,0.007512,0.014817,0.095198
Novisyntrophococcus fermenticellae,21.0,0.013335,0.017522,0.000000,0.003359,0.007259,0.016655,0.069112
Xylocopilactobacillus sp945273735,21.0,0.010320,0.008376,0.000000,0.005086,0.007312,0.014732,0.033461
CABMKH01 sp040797625,21.0,0.010136,0.010986,0.000000,0.000000,0.007134,0.015816,0.033634
Providencia rettgeri,21.0,0.009166,0.024493,0.000000,0.000000,0.000000,0.001820,0.098313
Schnuerera sp021655095,21.0,0.008588,0.022463,0.000000,0.000000,0.000000,0.000000,0.080195
Providencia hangzhouensis,21.0,0.007539,0.025558,0.000000,0.000000,0.000000,0.001431,0.116632
Virgibacillus proomii_B,21.0,0.006370,0.027961,0.000000,0.000000,0.000000,0.000000,0.128342
Serratia ureilytica,21.0,0.004428,0.016062,0.000000,0.000000,0.000000,0.000000,0.073417
Klebsiella grimontii,21.0,0.001817,0.006710,0.000000,0.000000,0.000000,0.000000,0.030600
Lactobacillus panisapium,21.0,0.001740,0.007975,0.000000,0.000000,0.000000,0.000000,0.036548
Oceanobacillus sp032085455,21.0,0.001219,0.004553,0.000000,0.000000,0.000000,0.000000,0.020483

In [ ]:
run_to_replicate = metadata_df.set_index("Run accession")["Replicate"].to_dict()
abund_df = abund_df.rename(
    columns={
        column: run_to_replicate[column]
        for column in abund_df.columns
        if column.startswith("SRR") and column in run_to_replicate
    }
)

abund_df =abund_df[[*sample_order]]
abund_df.head()

### Relative abundance of control data

In [ ]:
control_species_abund_df = abund_df[["C1", "C2", "C3"]]
control_species_abund_df.T.describe().T.sort_values(by="mean", ascending=False)

In [ ]:
control_species_abund_df.xs("Bartonella_A", level=1, axis=0, drop_level=False).sum(axis=0).describe()

### Relative abundance of all experimental conditions

In [ ]:
control_species_abund_df = abund_df[["C1", "C2", "C3"]]
display(control_species_abund_df.T.describe().T.sort_values(by="mean", ascending=False))

infected_species_abund_df = abund_df[["N1", "N2", "N3"]]
display(infected_species_abund_df.T.describe().T.sort_values(by="mean", ascending=False))

In [ ]:
for sample in abund_df.columns:
    print(f"Sample: {sample}")
    top_species = abund_df[sample].nlargest(5)
    display(top_species)

In [ ]:
arsenophonus_abund_df = abund_df.xs("Arsenophonus apicola", level=2, axis=0, drop_level=False).T
print(f"Abundance for Arsenophonus apicola in TP2: {arsenophonus_abund_df.loc['TP2'].values[0]}")
print("Abundance for Arsenophonus apicola without TP2 sample: ")
arsenophonus_abund_df.drop(["TP2"]).describe().T

In [ ]:
# Reorder species rows so stacked bars follow the requested family order
index_df = abund_df.index.to_frame(index=False)
index_df["sort_rank"] = index_df["Family"].map(family_rank).fillna(len(family_order)).astype(int)
index_df = index_df.sort_values(["sort_rank", "Family", "Genus", "Species"], kind="stable")
ordered_index = pd.MultiIndex.from_frame(index_df[["Family", "Genus", "Species"]])
species_abund_df_ordered = abund_df.loc[ordered_index]

# Default colors: same family hue, different shade within family
default_color_map = {}
for family_name, group in index_df.groupby("Family", sort=False):
    base_color = family_colors.get(family_name, "gray")
    shades = make_family_shades(base_color, len(group))
    for (_, row), shade in zip(group.iterrows(), shades):
        default_color_map[(row["Family"], row["Genus"], row["Species"])] = shade

# Special overrides requested by user
providencia_count = index_df["Genus"].astype(str).str.lower().str.startswith("providencia").sum()
providencia_shades = iter(make_color_gradient("#c4a484", "#654321", providencia_count))

species_colors = []
for _, row in index_df.iterrows():
    family_name = row["Family"]
    genus_name = str(row["Genus"]).strip().lower()
    species_name = str(row["Species"]).strip().lower()
    key = (row["Family"], row["Genus"], row["Species"])
    if genus_name.startswith("arsenophonus") and species_name == "apicola":
        color = "black"
    elif genus_name.startswith("proteus"):
        color = "#c4a484"  # light brown
    elif genus_name.startswith("providencia"):
        color = next(providencia_shades)
    else:
        color = default_color_map.get(key, family_colors.get(family_name, "gray"))
    species_colors.append(color)

fig, ax = plt.subplots(figsize=(16, 8))
species_abund_df_ordered.T.plot(
    kind="bar",
    stacked=True,
    ax=ax,
    color=species_colors,
    width=0.85,
    legend=False,
 )

ax.set_ylabel("Relative abundance (%)")
ax.set_ylim(0, 100)
ax.tick_params(axis="x", rotation=45)

present_families = [family for family in family_order if family in set(index_df["Family"])]
legend_handles = [
    Patch(facecolor=family_colors.get(family, "gray"), label=family)
    for family in present_families
]
ax.legend(handles=legend_handles, title="Family", bbox_to_anchor=(1.02, 1), loc="upper left")

plt.tight_layout()
png_fp = result_dp / "taxonomy_relative_abundance_biplot.png"
fig.savefig(png_fp, dpi=300, bbox_inches="tight")
plt.show()

### PCA

In [ ]:
sample_matrix = abund_df.select_dtypes(include=[np.number]).T

scaled_sample_matrix = StandardScaler().fit_transform(sample_matrix)
pca = PCA(n_components=2)
sample_scores = pca.fit_transform(scaled_sample_matrix)
species_loadings = pca.components_.T * np.sqrt(pca.explained_variance_)

sample_scores_df = pd.DataFrame(sample_scores, index=sample_matrix.index, columns=["PC1", "PC2"])
sample_scores_df["Category"] = (
    sample_scores_df.index.to_series()
    .str.extract(r"^(NT|NP|TP|C|T|P|N)", expand=False)
    .fillna("Other")
)

species_contribution = np.linalg.norm(species_loadings, axis=1)
contribution_norm = plt.Normalize(species_contribution.min(), species_contribution.max())
arrow_cmap = LinearSegmentedColormap.from_list("cyan_orange", ["#00bcd4", "#ff8c00"])
arrow_colors = arrow_cmap(contribution_norm(species_contribution))

top_species_idx = np.argsort(species_contribution)[-20:]
score_limit = np.abs(sample_scores_df[["PC1", "PC2"]].to_numpy()).max()
loading_limit = np.abs(species_loadings[top_species_idx]).max()
arrow_scale = 1.0 if loading_limit == 0 else (score_limit / loading_limit) * 0.8

fig, ax = plt.subplots(figsize=(12, 10))

for category, frame in sample_scores_df.groupby("Category", sort=False):
    ax.scatter(
        frame["PC1"],
        frame["PC2"],
        s=90,
        color=category_palette.get(category, category_palette["Other"]),
        label=category,
        alpha=0.9,
    )
    for sample_name, row in frame.iterrows():
        ax.text(row["PC1"], row["PC2"], sample_name, fontsize=9, ha="left", va="bottom")

for idx in top_species_idx:
    species_name = abund_df.index[idx][2]
    x_loading = species_loadings[idx, 0] * arrow_scale
    y_loading = species_loadings[idx, 1] * arrow_scale
    ax.arrow(
        0,
        0,
        x_loading,
        y_loading,
        color=arrow_colors[idx],
        alpha=0.85,
        width=0.002,
        head_width=0.08,
        length_includes_head=True,
    )
    ax.text(x_loading * 1.05, y_loading * 1.05, species_name, color=arrow_colors[idx], fontsize=8)

explained_variance = pca.explained_variance_ratio_ * 100
ax.axhline(0, color="lightgray", linewidth=1)
ax.axvline(0, color="lightgray", linewidth=1)
ax.set_xlabel(f"PC1 ({explained_variance[0]:.1f}% variance)")
ax.set_ylabel(f"PC2 ({explained_variance[1]:.1f}% variance)")
ax.legend(title="Conditions")

sm = plt.cm.ScalarMappable(cmap=arrow_cmap, norm=contribution_norm)
sm.set_array([])
fig.colorbar(sm, ax=ax, label="Species contribution magnitude")

plt.tight_layout()
png_fp = result_dp / "taxonomy_pca_biplot.png"
fig.savefig(png_fp, dpi=300, bbox_inches="tight")
print(f"Saved PCA biplot to: {png_fp}")
plt.show()

sample_scores_df

## Comparison of MAGs taxonomy with original study

In [ ]:
count = df_expert[
    df_expert["Origin"].astype(str).str.contains("Built MAG", na=False)
    & (df_expert["Differences between NCBI and GTDB taxonomies"] == "Yes")].shape[0]
print(f"Number of MAGs with differences between NCBI and GTDB taxonomies: {count}")

### Statistics for MAGs origin

In [ ]:
origin_df = df_expert["Origin"].value_counts(dropna=False).to_frame("count")
origin_df

### Species identified by MAGs

#### Concordant = corresponding to species listed in the paper

In [ ]:
concordant_mags = df_expert.query("Origin == 'Built MAG, Species listed in the paper' and Species.notna()")
concordant_mags

In [ ]:
concordant_mags[["Completeness", "Contamination", "Genome Size"]].describe()

#### Non concordant = NOT corresponding to species listed in the paper

In [ ]:
non_concordant_mags = df_expert.query("Origin == 'Built MAG' and Species.notna()")
non_concordant_mags

In [ ]:
non_concordant_mags[["Completeness", "Contamination", "Genome Size"]].describe()

#### Comparison of completess and contamination between concordant and non-concordant species

In [ ]:
metrics = ["Completeness", "Contamination"]
group_order = ["Concordant MAGs", "Non-concordant MAGs"]

plot_frames = []
for group_name, frame in [
    ("Concordant MAGs", concordant_mags),
    ("Non-concordant MAGs", non_concordant_mags),
]:
    subset = frame[metrics].copy()
    for metric in metrics:
        subset[metric] = pd.to_numeric(subset[metric], errors="coerce")
    subset["Group"] = group_name
    plot_frames.append(subset)

plot_df = pd.concat(plot_frames, ignore_index=True)

palette = {
    "Concordant MAGs": "#2a9d8f",
    "Non-concordant MAGs": "#e76f51",
}

fig, axes = plt.subplots(1, 2, figsize=(12, 5))

for ax, metric in zip(axes, metrics):
    sns.violinplot(
        data=plot_df,
        x="Group",
        y=metric,
        hue="Group",
        order=group_order,
        hue_order=group_order,
        palette=palette,
        cut=0,
        inner="box",
        legend=False,
        ax=ax,
    )
    sns.stripplot(
        data=plot_df,
        x="Group",
        y=metric,
        order=group_order,
        color="black",
        alpha=0.6,
        size=4,
        ax=ax,
    )
    ax.set_xlabel("")
    ax.set_title(metric)
    ax.tick_params(axis="x", rotation=12)

plt.tight_layout()
plt.show()