# Explore the aeromicrobiome use case

In [1]:
from pathlib import Path
import sys

import pandas as pd
import numpy as np

sys.path.insert(0, str((Path.cwd() / "bin").resolve()))
sys.path.insert(0, str(Path.cwd().resolve()))

from helpers import (
    load_dfs,
    compute_print_stats,
    explore_species_level_clusters_all,
    compute_taxo_classification_summary,
    get_all_taxo_levels,
    get_bakta_annot_df,
    get_kegg_path_df,
    get_relative_abund_taxo_levels,
    print_stats,
    read_bakta_gff_file,
    extract_gff_attributes,
)

In [2]:
data_dp = Path("../data/use-cases/cloud-microbiome/")
data_dp.exists()

data_dp_2 = Path("../data/cloud-use-case/")
data_dp_2.exists()

result_dp = Path("../results/cloud-use-case/")
result_dp.exists()

rep_fn = "reps_cloud.tsv"

metadata_df, reps_df, coverage_df = load_dfs(data_dp_2, result_dp, rep_fn)

In [3]:
metadata_df

,run_accession,Sample ID,Condition,Sampling date,Season,Sampling start,Sampling end,Sampling duration (h),Geographic origin of the air mass,Boundary layer height (min–max [average]) (m a.s.l.),Boundary layer height min (m a.s.l.),Boundary layer height max (m a.s.l.),Boundary layer height average (m a.s.l.),Position of the sampling site relative to the boundary layer,Temperature (°C),Relative humidity (%),Wind speed (m s−1),Liquid water content (LWC) (g m−3),sample_title
0,ERR9966616,20200707AIR,Clear atmosphere,07/07/2020,Summer,09:00,15:30,6.5,Northwest,1268–1834 [1626],1268,1834,1626,In,11.1,61,3.6,NaN,20200707AIR
1,ERR9966617,20200708AIR,Clear atmosphere,08/07/2020,Summer,08:35,14:40,6.1,Northwest,623–1675 [1253],623,1675,1253,In,14.2,53,3.1,NaN,20200708AIR
2,ERR9966618,20200709AIR,Clear atmosphere,09/07/2020,Summer,08:35,14:35,6.0,North,651–2377 [1487],651,2377,1487,In,20.3,48,3.4,NaN,20200709AIR
3,ERR9966619,20200922AIR,Clear atmosphere,22/09/2020,Autumn,08:51,14:46,5.9,West,665–1334 [972],665,1334,972,Out,12.4,78,1.0,NaN,20200922AIR
4,ERR9966620,20201118AIR,Clear atmosphere,18/11/2020,Autumn,09:00,14:50,5.8,West,680–1142 [870],680,1142,870,Out,14.1,41,6.4,NaN,20201118AIR
5,ERR9966621,20191002CLOUD,Cloud,02/10/2019,Autumn,14:47,17:10,2.4,Northwest,1422–1505 [1465],1422,1505,1465,In,6.5,100,3.0,NaN,20191002CLOUD
6,ERR9966622,20191022CLOUD,Cloud,22/10/2019,Autumn,10:06,16:30,6.4,South,698–957 [813],698,957,813,Out,5.7,100,8.7,NaN,20191022CLOUD
7,ERR9966623,20200311CLOUD,Cloud,11/03/2020,Winter,08:55,13:00,4.1,West,964–1145 [1060],964,1145,1060,Out,5.0,100,7.4,NaN,20200311CLOUD
8,ERR9966624,20200717CLOUD,Cloud,17/07/2020,Summer,11:45,15:00,3.3,Northwest,1271–1437 [1343],1271,1437,1343,Out,10.1,100,1.6,0.08,20200717CLOUD
9,ERR9966625,20201016CLOUD,Cloud,16/10/2020,Autumn,08:50,13:30,4.7,Norteast,917–1034 [958],917,1034,958,Out,1.1,100,1.8,0.35,20201016CLOUD
10,ERR9966626,20201028CLOUD,Cloud,28/10/2020,Autumn,09:13,15:15,6.0,West,1026–1529 [1269],1026,1529,1269,Out,5.2,100,11.0,0.23,20201028CLOUD
11,ERR9966627,20201103CLOUD,Cloud,03/11/2020,Autumn,11:00,14:30,3.5,West,1126–1593 [1390],1126,1593,1390,In,2.2,100,8.7,0.06,20201103CLOUD
12,ERR9966628,20201110CLOUD,Cloud,10/11/2020,Autumn,11:02,14:10,3.1,Southwest,691–1276 [1016],691,1276,1016,Out,5.9,100,2.5,0.07,20201110CLOUD
13,ERR9966629,20201119CLOUD,Cloud,19/11/2020,Autumn,08:54,11:47,2.8,West,1207–1234 [1215],1207,1234,1215,Out,0.3,100,7.7,0.11,20201119CLOUD

In [4]:
# WARNING: high percentage of unmapped
print("Percentage of unmapped reads for coverage")
print_stats(coverage_df.query("Genome == 'unmapped'").drop(columns="Genome").T.describe())

Percentage of unmapped reads for coverage
215: 80.44 ± 4.97, Median: 81.00, IQR: 78.08-82.86, Range: 70.48-87.84

# Quality

In [5]:
read_numbers = {
    "ERR9966616": 46.5,
    "ERR9966617": 29.6,
    "ERR9966618": 43.7,
    "ERR9966619": 41.6,
    "ERR9966620": 39.5,
    "ERR9966621": 63.8,
    "ERR9966622": 249.9,
    "ERR9966623": 58.2,
    "ERR9966624": 42.7,
    "ERR9966625": 95.8,
    "ERR9966626": 65.0,
    "ERR9966627": 54.3,
    "ERR9966628": 59.8,
    "ERR9966629": 76.6,
}
read_numbers_df = pd.DataFrame.from_dict(read_numbers, orient="index", columns=["Read numbers (M)"])
print_stats(read_numbers_df.describe())

Read numbers (M): 69.07 ± 54.75, Median: 56.25, IQR: 42.95-64.70, Range: 29.60-249.90

In [6]:
print(f"Total number of MAGs: {reps_df['Cluster members'].sum()}")
print(f"Total number of species-level clusters: {reps_df.shape[0]}")

Total number of MAGs: 230
Total number of species-level clusters: 215

In [7]:
explore_species_level_clusters_all(reps_df)

Species-level clusters with no contamination threshold
Total number: 215.0
Cluster members: 1.07 ± 0.46, Median: 1.00, IQR: 1.00-1.00, Range: 1.00-6.00
Contamination: 2.92 ± 5.33, Median: 0.01, IQR: 0.00-4.50, Range: 0.00-26.55
Completeness: 16.06 ± 20.09, Median: 6.40, IQR: 3.05-19.50, Range: 1.70-100.00
Total length: 1.89 ± 7.83, Median: 0.24, IQR: 0.09-1.11, Range: 0.05-99.18

Species-level clusters with contamination < 5%
Total number: 163.0
Cluster members: 1.04 ± 0.40, Median: 1.00, IQR: 1.00-1.00, Range: 1.00-6.00
Contamination: 0.26 ± 0.86, Median: 0.00, IQR: 0.00-0.03, Range: 0.00-4.75
Completeness: 6.74 ± 9.38, Median: 4.30, IQR: 2.65-6.50, Range: 1.70-96.10
Total length: 0.56 ± 3.42, Median: 0.13, IQR: 0.07-0.35, Range: 0.05-43.50

Species-level clusters with contamination < 10%
Total number: 186.0
Cluster members: 1.07 ± 0.49, Median: 1.00, IQR: 1.00-1.00, Range: 1.00-6.00
Contamination: 1.12 ± 2.50, Median: 0.00, IQR: 0.00-0.12, Range: 0.00-9.69
Completeness: 10.53 ± 14.29, Median: 5.20, IQR: 2.70-9.88, Range: 1.70-96.10
Total length: 0.92 ± 3.87, Median: 0.17, IQR: 0.08-0.65, Range: 0.05-43.50

# Clusters given Bowers et al / MIMAG classification

## HQ: High-quality species-level clusters (contamination < 5% and completeness > 90%)

In [8]:
hq_df = reps_df.query("Contamination < 5 and Completeness > 90")
hq_df.iloc[:,:25]

,MAG,Domain,Phylum,Class,Order,Family,Genus,Species,Cluster members,Completeness,...,GC (%),L50,L90,Largest contig,N50,N90,Total length,Total length (>= 0 bp),Total length (>= 1000 bp),auN
1,ERR9966625_bin_1350,Bacteria,Pseudomonadota,Alphaproteobacteria,Acetobacterales,Acetobacteraceae,CAHJXG01,unclassified,1,96.1,...,64.08,551.0,1311.0,25008.0,3239.0,2517.0,5413774.0,5413774.0,5413774.0,4447.3

In [9]:
compute_print_stats(hq_df)

Total number: 1.0
Cluster members: 1.00 ± nan, Median: 1.00, IQR: 1.00-1.00, Range: 1.00-1.00
Contamination: 3.94 ± nan, Median: 3.94, IQR: 3.94-3.94, Range: 3.94-3.94
Completeness: 96.10 ± nan, Median: 96.10, IQR: 96.10-96.10, Range: 96.10-96.10
Total length: 5.41 ± nan, Median: 5.41, IQR: 5.41-5.41, Range: 5.41-5.41

In [10]:
print(f"Total number of MAGs: {hq_df['Cluster members'].sum()}")

Total number of MAGs: 1

### Taxonomy

In [11]:
compute_taxo_classification_summary(hq_df)

,Unclassified clusters,Classified clusters,Unclassified clusters %,Classified clusters %
Domain,0,1,0.0,100.0
Phylum,0,1,0.0,100.0
Class,0,1,0.0,100.0
Order,0,1,0.0,100.0
Family,0,1,0.0,100.0
Genus,0,1,0.0,100.0
Species,1,0,100.0,0.0

In [12]:
hq_taxo_levels = get_all_taxo_levels(hq_df)

Level: Domain

          Cluster  Cluster %  Total MAG count
Domain
Bacteria      1.0      100.0              1.0
TOTAL         1.0      100.0              1.0

Level: Phylum

                Cluster  Cluster %  Total MAG count
Phylum
Pseudomonadota      1.0      100.0              1.0
TOTAL               1.0      100.0              1.0

Level: Class

                     Cluster  Cluster %  Total MAG count
Class
Alphaproteobacteria      1.0      100.0              1.0
TOTAL                    1.0      100.0              1.0

Level: Order

                 Cluster  Cluster %  Total MAG count
Order
Acetobacterales      1.0      100.0              1.0
TOTAL                1.0      100.0              1.0

Level: Family

                  Cluster  Cluster %  Total MAG count
Family
Acetobacteraceae      1.0      100.0              1.0
TOTAL                 1.0      100.0              1.0

Level: Genus

          Cluster  Cluster %  Total MAG count
Genus
CAHJXG01      1.0      100.0              1.0
TOTAL         1.0      100.0              1.0

Level: Species

              Cluster  Cluster %  Total MAG count
Species
unclassified      1.0      100.0              1.0
TOTAL             1.0      100.0              1.0

### Relative abundance

In [13]:
hq_relative_abund_df = get_relative_abund_taxo_levels(hq_df, coverage_df)

Unmapped reads: 99.98 ± 0.03, Median: 99.99, IQR: 99.97-99.99, Range: 99.89-100.00
Mapped reads: 0.02 ± 0.03, Median: 0.01, IQR: 0.01-0.03, Range: 0.00-0.11

Level: Family

                  count       mean        std  min    25%    50%    75%    max
Family
Acetobacteraceae   14.0  92.857143  26.726124  0.0  100.0  100.0  100.0  100.0

Level: Genus

          count       mean        std  min    25%    50%    75%    max
Genus
CAHJXG01   14.0  92.857143  26.726124  0.0  100.0  100.0  100.0  100.0

Level: Species

              count       mean        std  min    25%    50%    75%    max
Species
unclassified   14.0  92.857143  26.726124  0.0  100.0  100.0  100.0  100.0

### Functions

In [14]:
print_stats(get_bakta_annot_df(hq_df).describe())

CDSs: 5189.00 ± nan, Median: 5189.00, IQR: 5189.00-5189.00, Range: 5189.00-5189.00
CRISPR arrays: 0.00 ± nan, Median: 0.00, IQR: 0.00-0.00, Range: 0.00-0.00
gaps: 0.00 ± nan, Median: 0.00, IQR: 0.00-0.00, Range: 0.00-0.00
hypotheticals: 3242.00 ± nan, Median: 3242.00, IQR: 3242.00-3242.00, Range: 3242.00-3242.00
ncRNA regions: 7.00 ± nan, Median: 7.00, IQR: 7.00-7.00, Range: 7.00-7.00
ncRNAs: 4.00 ± nan, Median: 4.00, IQR: 4.00-4.00, Range: 4.00-4.00
oriCs: 0.00 ± nan, Median: 0.00, IQR: 0.00-0.00, Range: 0.00-0.00
oriTs: 0.00 ± nan, Median: 0.00, IQR: 0.00-0.00, Range: 0.00-0.00
oriVs: 0.00 ± nan, Median: 0.00, IQR: 0.00-0.00, Range: 0.00-0.00
pseudogenes: 7.00 ± nan, Median: 7.00, IQR: 7.00-7.00, Range: 7.00-7.00
rRNAs: 0.00 ± nan, Median: 0.00, IQR: 0.00-0.00, Range: 0.00-0.00
sORFs: 2.00 ± nan, Median: 2.00, IQR: 2.00-2.00, Range: 2.00-2.00
signal peptides: 0.00 ± nan, Median: 0.00, IQR: 0.00-0.00, Range: 0.00-0.00
tRNAs: 47.00 ± nan, Median: 47.00, IQR: 47.00-47.00, Range: 47.00-47.00
tmRNAs: 1.00 ± nan, Median: 1.00, IQR: 1.00-1.00, Range: 1.00-1.00

In [15]:
get_kegg_path_df(hq_df)

Before removing rows and columns with only zeros:
Clusters: 1
KEGG modules: 341

After removing rows and columns with only zeros:
Clusters: 1
KEGG modules: 230

KEGG modules: 230.00 ± nan, Median: 230.00, IQR: 230.00-230.00, Range: 230.00-230.00

,3-Hydroxypropionate bi-cycle,ADP-L-glycero-D-manno-heptose biosynthesis,"Adenine ribonucleotide biosynthesis, IMP => ADP,ATP","Adenine ribonucleotide degradation, AMP => Urate",Anoxygenic photosystem II,"Arginine biosynthesis, glutamate => acetylcitrulline => arginine","Arginine biosynthesis, ornithine => arginine","Ascorbate biosynthesis, animals, glucose-1P => ascorbate","Ascorbate biosynthesis, plants, fructose-6P => ascorbate","Assimilatory nitrate reduction, nitrate => ammonia",...,"Undecaprenylphosphate alpha-L-Ara4N biosynthesis, UDP-GlcA => undecaprenyl phosphate alpha-L-Ara4N",Urea cycle,"V-type ATPase, eukaryotes","Valine/isoleucine biosynthesis, pyruvate => valine / 2-oxobutanoate => isoleucine","Xanthomonas spp. pathogenicity signature, T3SS and effectors","beta-Carotene biosynthesis, GGAP => beta-carotene",beta-Oxidation,"beta-Oxidation, acyl-CoA synthesis","beta-Oxidation, peroxisome, VLCFA",dTDP-L-rhamnose biosynthesis
1,29.17,60.0,100.0,100.0,100.0,57.14,100.0,42.86,12.5,100.0,...,25.0,80.0,7.69,100.0,2.27,16.67,100.0,100.0,33.33,83.33

## MQ: Medium-quality species-level clusters (contamination < 10% and completeness > 50%)

In [16]:
mq_df = reps_df.query("Contamination < 10 and Completeness > 50")
mq_df.set_index("MAG", inplace=True)
mq_df.iloc[:, :25]

,Domain,Phylum,Class,Order,Family,Genus,Species,Cluster members,Completeness,Contamination,...,L50,L90,Largest contig,N50,N90,Total length,Total length (>= 0 bp),Total length (>= 1000 bp),auN,bakta_CDSs
MAG,,,,,,,,,,,,,,,,,,,,,
ERR9966625_bin_1350,Bacteria,Pseudomonadota,Alphaproteobacteria,Acetobacterales,Acetobacteraceae,CAHJXG01,unclassified,1,96.1,3.94,...,551.0,1311.0,25008.0,3239.0,2517.0,5413774.0,5413774.0,5413774.0,4447.3,5189
ERR9966629_bin_2487,Bacteria,unclassified,unclassified,unclassified,unclassified,unclassified,unclassified,4,59.7,8.55,...,167.0,469.0,18123.0,4397.0,2068.0,2282670.0,2282670.0,2282670.0,5428.6,2097
ERR9966624_bin_1915,Archaea,unclassified,unclassified,unclassified,unclassified,unclassified,unclassified,1,59.5,8.70,...,922.0,1826.0,3564.0,1247.0,1047.0,2579262.0,2579262.0,2579262.0,1269.8,4344
ERR9966620_bin_1091,Bacteria,unclassified,unclassified,unclassified,unclassified,unclassified,unclassified,1,57.1,8.82,...,755.0,1605.0,5119.0,1450.0,1136.0,2744751.0,2744751.0,2744751.0,1585.9,4949
ERR9966627_bin_841,unclassified,unclassified,unclassified,unclassified,unclassified,unclassified,unclassified,1,56.7,7.14,...,114.0,355.0,18136.0,3542.0,1631.0,1301435.0,1301435.0,1301435.0,4491.9,1433
ERR9966629_bin_15813,unclassified,unclassified,unclassified,unclassified,unclassified,unclassified,unclassified,1,56.1,6.45,...,132.0,377.0,19901.0,4227.0,1991.0,1765345.0,1765345.0,1765345.0,5283.9,1722
ERR9966620_bin_1469,Bacteria,Pseudomonadota,Alphaproteobacteria,Acetobacterales,Acetobacteraceae,CAHJXG01,unclassified,6,55.9,3.73,...,5870.0,18191.0,27845.0,1894.0,1114.0,43499712.0,43499712.0,43499712.0,3020.6,73538
ERR9966628_bin_3376,unclassified,unclassified,unclassified,unclassified,unclassified,unclassified,unclassified,1,55.2,9.69,...,244.0,455.0,3417.0,3118.0,2892.0,1583889.0,1583889.0,1583889.0,3114.3,2726

In [17]:
compute_print_stats(mq_df)

Total number: 8.0
Cluster members: 2.00 ± 1.93, Median: 1.00, IQR: 1.00-1.75, Range: 1.00-6.00
Contamination: 7.13 ± 2.27, Median: 7.85, IQR: 5.82-8.73, Range: 3.73-9.69
Completeness: 62.04 ± 13.86, Median: 56.90, IQR: 56.05-59.55, Range: 55.20-96.10
Total length: 7.65 ± 14.54, Median: 2.43, IQR: 1.72-3.41, Range: 1.30-43.50

In [18]:
print(f"Total number of MAGs: {mq_df['Cluster members'].sum()}")

Total number of MAGs: 16

### Taxonomy

In [19]:
compute_taxo_classification_summary(mq_df)

,Unclassified clusters,Classified clusters,Unclassified clusters %,Classified clusters %
Domain,3,5,37.5,62.5
Phylum,6,2,75.0,25.0
Class,6,2,75.0,25.0
Order,6,2,75.0,25.0
Family,6,2,75.0,25.0
Genus,6,2,75.0,25.0
Species,8,0,100.0,0.0

In [20]:
mq_taxo_levels = get_all_taxo_levels(mq_df)

Level: Domain

              Cluster  Cluster %  Total MAG count
Domain
Bacteria          4.0       50.0             12.0
unclassified      3.0       37.5              3.0
Archaea           1.0       12.5              1.0
TOTAL             8.0      100.0             16.0

Level: Phylum

                Cluster  Cluster %  Total MAG count
Phylum
unclassified        6.0       75.0              9.0
Pseudomonadota      2.0       25.0              7.0
TOTAL               8.0      100.0             16.0

Level: Class

                     Cluster  Cluster %  Total MAG count
Class
unclassified             6.0       75.0              9.0
Alphaproteobacteria      2.0       25.0              7.0
TOTAL                    8.0      100.0             16.0

Level: Order

                 Cluster  Cluster %  Total MAG count
Order
unclassified         6.0       75.0              9.0
Acetobacterales      2.0       25.0              7.0
TOTAL                8.0      100.0             16.0

Level: Family

                  Cluster  Cluster %  Total MAG count
Family
unclassified          6.0       75.0              9.0
Acetobacteraceae      2.0       25.0              7.0
TOTAL                 8.0      100.0             16.0

Level: Genus

              Cluster  Cluster %  Total MAG count
Genus
unclassified      6.0       75.0              9.0
CAHJXG01          2.0       25.0              7.0
TOTAL             8.0      100.0             16.0

Level: Species

              Cluster  Cluster %  Total MAG count
Species
unclassified      8.0      100.0             16.0
TOTAL             8.0      100.0             16.0

### Relative abundance

In [21]:
mq_relative_abund_df = get_relative_abund_taxo_levels(mq_df, coverage_df)

Unmapped reads: 99.36 ± 0.40, Median: 99.24, IQR: 99.12-99.56, Range: 98.83-100.00
Mapped reads: 0.64 ± 0.40, Median: 0.76, IQR: 0.44-0.88, Range: 0.00-1.17

Level: Family

,count,mean,std,min,25%,50%,75%,max
Family,,,,,,,,
unclassified,14.0,68.223169,37.455606,0.0,76.105590,85.218047,88.416510,97.79188
Acetobacteraceae,14.0,24.633974,32.674469,0.0,9.467131,12.756283,20.737445,100.00000

Level: Genus

,count,mean,std,min,25%,50%,75%,max
Genus,,,,,,,,
unclassified,14.0,68.223169,37.455606,0.0,76.105590,85.218047,88.416510,97.79188
CAHJXG01,14.0,24.633974,32.674469,0.0,9.467131,12.756283,20.737445,100.00000

Level: Species

              count       mean        std  min    25%    50%    75%    max
Species
unclassified   14.0  92.857143  26.726124  0.0  100.0  100.0  100.0  100.0

In [22]:
index = pd.MultiIndex.from_frame(metadata_df[["run_accession", "Condition", "Season", "Geographic origin of the air mass"]])
mq_relative_abund_df_bis = mq_relative_abund_df.T.set_index(index)
#display(mq_relative_abund_df) to check order of rows
mq_relative_abund_df_bis

,,,Family,Acetobacteraceae,unclassified
,,,Genus,CAHJXG01,unclassified
,,,Species,unclassified,unclassified
run_accession,Condition,Season,Geographic origin of the air mass,,
ERR9966616,Clear atmosphere,Summer,Northwest,100.000000,0.000000
ERR9966617,Clear atmosphere,Summer,Northwest,NaN,NaN
ERR9966618,Clear atmosphere,Summer,North,100.000000,0.000000
ERR9966619,Clear atmosphere,Autumn,West,2.208120,97.791880
ERR9966620,Clear atmosphere,Autumn,West,21.624311,78.375689
ERR9966621,Cloud,Autumn,Northwest,16.529524,83.470476
ERR9966622,Cloud,Autumn,South,18.076845,81.923155
ERR9966623,Cloud,Winter,West,11.437973,88.562027
ERR9966624,Cloud,Summer,Northwest,4.004964,95.995036
ERR9966625,Cloud,Autumn,Norteast,24.651110,75.348890
ERR9966626,Cloud,Autumn,West,13.034381,86.965619
ERR9966627,Cloud,Autumn,West,12.020041,87.979959
ERR9966628,Cloud,Autumn,Southwest,12.478184,87.521816
ERR9966629,Cloud,Autumn,West,8.810184,91.189816

### Functions

In [23]:
mq_bakta_annot = get_bakta_annot_df(mq_df)
mq_bakta_annot

,CDSs,CRISPR arrays,gaps,hypotheticals,ncRNA regions,ncRNAs,oriCs,oriTs,oriVs,pseudogenes,rRNAs,sORFs,signal peptides,tRNAs,tmRNAs
MAG,,,,,,,,,,,,,,,
ERR9966625_bin_1350,5189,0,0,3242,7,4,0,0,0,7,0,2,0,47,1
ERR9966629_bin_2487,2097,0,0,2079,0,0,0,0,0,1,16,0,0,37,0
ERR9966624_bin_1915,4344,0,0,4342,0,0,0,0,0,0,0,0,0,14,0
ERR9966620_bin_1091,4949,0,0,4945,0,0,0,0,0,0,0,0,0,12,0
ERR9966627_bin_841,1433,1,0,1429,0,0,0,0,0,0,8,0,0,13,0
ERR9966629_bin_15813,1722,0,0,1713,0,1,1,1,0,1,13,0,0,19,0
ERR9966620_bin_1469,73538,0,0,72226,5,2,0,0,0,21,21,1,0,226,0
ERR9966628_bin_3376,2726,0,0,2724,0,0,0,0,0,0,0,0,0,5,0

In [24]:
print_stats(mq_bakta_annot.describe())

CDSs: 11999.75 ± 24908.46, Median: 3535.00, IQR: 2003.25-5009.00, Range: 1433.00-73538.00
CRISPR arrays: 0.12 ± 0.35, Median: 0.00, IQR: 0.00-0.00, Range: 0.00-1.00
gaps: 0.00 ± 0.00, Median: 0.00, IQR: 0.00-0.00, Range: 0.00-0.00
hypotheticals: 11587.50 ± 24532.69, Median: 2983.00, IQR: 1987.50-4492.75, Range: 1429.00-72226.00
ncRNA regions: 1.50 ± 2.83, Median: 0.00, IQR: 0.00-1.25, Range: 0.00-7.00
ncRNAs: 0.88 ± 1.46, Median: 0.00, IQR: 0.00-1.25, Range: 0.00-4.00
oriCs: 0.12 ± 0.35, Median: 0.00, IQR: 0.00-0.00, Range: 0.00-1.00
oriTs: 0.12 ± 0.35, Median: 0.00, IQR: 0.00-0.00, Range: 0.00-1.00
oriVs: 0.00 ± 0.00, Median: 0.00, IQR: 0.00-0.00, Range: 0.00-0.00
pseudogenes: 3.75 ± 7.36, Median: 0.50, IQR: 0.00-2.50, Range: 0.00-21.00
rRNAs: 7.25 ± 8.53, Median: 4.00, IQR: 0.00-13.75, Range: 0.00-21.00
sORFs: 0.38 ± 0.74, Median: 0.00, IQR: 0.00-0.25, Range: 0.00-2.00
signal peptides: 0.00 ± 0.00, Median: 0.00, IQR: 0.00-0.00, Range: 0.00-0.00
tRNAs: 46.62 ± 73.83, Median: 16.50, IQR: 12.75-39.50, Range: 5.00-226.00
tmRNAs: 0.12 ± 0.35, Median: 0.00, IQR: 0.00-0.00, Range: 0.00-1.00

In [25]:
mq_kegg_df = get_kegg_path_df(mq_df)

Before removing rows and columns with only zeros:
Clusters: 8
KEGG modules: 341

After removing rows and columns with only zeros:
Clusters: 8
KEGG modules: 290

KEGG modules: 91.88 ± 104.41, Median: 54.50, IQR: 12.50-125.75, Range: 8.00-275.00

In [26]:
non_zero_per_row = (mq_kegg_df != 0).sum(axis=1)
non_zero_per_row

MAG
ERR9966625_bin_1350     230
ERR9966629_bin_2487      14
ERR9966624_bin_1915      91
ERR9966620_bin_1091      74
ERR9966627_bin_841        8
ERR9966629_bin_15813      8
ERR9966620_bin_1469     275
ERR9966628_bin_3376      35
dtype: int64

## LQ: Low-quality species-level clusters (contamination < 10% and completeness < 50%)

In [27]:
lq_df = reps_df.query("Contamination < 10 and Completeness < 50")
compute_print_stats(lq_df)

Total number: 178.0
Cluster members: 1.03 ± 0.25, Median: 1.00, IQR: 1.00-1.00, Range: 1.00-4.00
Contamination: 0.85 ± 2.16, Median: 0.00, IQR: 0.00-0.09, Range: 0.00-9.57
Completeness: 8.21 ± 8.98, Median: 4.80, IQR: 2.70-8.45, Range: 1.70-42.50
Total length: 0.62 ± 2.27, Median: 0.15, IQR: 0.08-0.58, Range: 0.05-28.08

### Taxonomy

In [28]:
compute_taxo_classification_summary(lq_df)

,Unclassified clusters,Classified clusters,Unclassified clusters %,Classified clusters %
Domain,137,41,76.97,23.03
Phylum,176,2,98.88,1.12
Class,176,2,98.88,1.12
Order,176,2,98.88,1.12
Family,176,2,98.88,1.12
Genus,176,2,98.88,1.12
Species,176,2,98.88,1.12

In [29]:
lq_taxo_levels = get_all_taxo_levels(lq_df)

Level: Domain

              Cluster   Cluster %  Total MAG count
Domain
unclassified    137.0   76.966292            138.0
Bacteria         23.0   12.921348             23.0
Archaea          18.0   10.112360             22.0
TOTAL           178.0  100.000000            183.0

Level: Phylum

                Cluster   Cluster %  Total MAG count
Phylum
unclassified      176.0   98.876404            181.0
Actinomycetota      1.0    0.561798              1.0
Pseudomonadota      1.0    0.561798              1.0
TOTAL             178.0  100.000000            183.0

Level: Class

                     Cluster   Cluster %  Total MAG count
Class
unclassified           176.0   98.876404            181.0
Actinomycetes            1.0    0.561798              1.0
Alphaproteobacteria      1.0    0.561798              1.0
TOTAL                  178.0  100.000000            183.0

Level: Order

                 Cluster   Cluster %  Total MAG count
Order
unclassified       176.0   98.876404            181.0
Acetobacterales      1.0    0.561798              1.0
Mycobacteriales      1.0    0.561798              1.0
TOTAL              178.0  100.000000            183.0

Level: Family

                  Cluster   Cluster %  Total MAG count
Family
unclassified        176.0   98.876404            181.0
Acetobacteraceae      1.0    0.561798              1.0
Mycobacteriaceae      1.0    0.561798              1.0
TOTAL               178.0  100.000000            183.0

Level: Genus

               Cluster   Cluster %  Total MAG count
Genus
unclassified     176.0   98.876404            181.0
Mycobacterium      1.0    0.561798              1.0
Roseomonas         1.0    0.561798              1.0
TOTAL            178.0  100.000000            183.0

Level: Species

                           Cluster   Cluster %  Total MAG count
Species
unclassified                 176.0   98.876404            181.0
Mycobacterium sp002013775      1.0    0.561798              1.0
Roseomonas mucosa              1.0    0.561798              1.0
TOTAL                        178.0  100.000000            183.0

### Relative abundance

In [30]:
lq_relative_abund_df = get_relative_abund_taxo_levels(lq_df, coverage_df)

Unmapped reads: 82.51 ± 4.33, Median: 83.03, IQR: 80.26-84.45, Range: 73.70-89.15
Mapped reads: 17.49 ± 4.33, Median: 16.97, IQR: 15.55-19.74, Range: 10.85-26.30

Level: Family

,count,mean,std,min,25%,50%,75%,max
Family,,,,,,,,
unclassified,14.0,99.953125,0.113666,99.645077,100.0,100.0,100.0,100.000000
Acetobacteraceae,14.0,0.027760,0.094592,0.000000,0.0,0.0,0.0,0.354923
Mycobacteriaceae,14.0,0.019115,0.071521,0.000000,0.0,0.0,0.0,0.267609

Level: Genus

,count,mean,std,min,25%,50%,75%,max
Genus,,,,,,,,
unclassified,14.0,99.953125,0.113666,99.645077,100.0,100.0,100.0,100.000000
Roseomonas,14.0,0.027760,0.094592,0.000000,0.0,0.0,0.0,0.354923
Mycobacterium,14.0,0.019115,0.071521,0.000000,0.0,0.0,0.0,0.267609

Level: Species

,count,mean,std,min,25%,50%,75%,max
Species,,,,,,,,
unclassified,14.0,99.953125,0.113666,99.645077,100.0,100.0,100.0,100.000000
Roseomonas mucosa,14.0,0.027760,0.094592,0.000000,0.0,0.0,0.0,0.354923
Mycobacterium sp002013775,14.0,0.019115,0.071521,0.000000,0.0,0.0,0.0,0.267609

### Functions

In [31]:
print_stats(get_bakta_annot_df(lq_df).describe())

CDSs: 920.07 ± 3699.33, Median: 166.50, IQR: 67.00-866.00, Range: 2.00-46384.00
CRISPR arrays: 0.01 ± 0.11, Median: 0.00, IQR: 0.00-0.00, Range: 0.00-1.00
gaps: 0.00 ± 0.00, Median: 0.00, IQR: 0.00-0.00, Range: 0.00-0.00
hypotheticals: 902.20 ± 3664.99, Median: 159.00, IQR: 64.50-791.25, Range: 2.00-45905.00
ncRNA regions: 0.10 ± 0.71, Median: 0.00, IQR: 0.00-0.00, Range: 0.00-6.00
ncRNAs: 0.07 ± 0.56, Median: 0.00, IQR: 0.00-0.00, Range: 0.00-6.00
oriCs: 0.00 ± 0.00, Median: 0.00, IQR: 0.00-0.00, Range: 0.00-0.00
oriTs: 0.00 ± 0.00, Median: 0.00, IQR: 0.00-0.00, Range: 0.00-0.00
oriVs: 0.00 ± 0.00, Median: 0.00, IQR: 0.00-0.00, Range: 0.00-0.00
pseudogenes: 0.67 ± 2.58, Median: 0.00, IQR: 0.00-0.00, Range: 0.00-26.00
rRNAs: 0.57 ± 1.97, Median: 0.00, IQR: 0.00-0.00, Range: 0.00-16.00
sORFs: 0.03 ± 0.22, Median: 0.00, IQR: 0.00-0.00, Range: 0.00-2.00
signal peptides: 0.00 ± 0.00, Median: 0.00, IQR: 0.00-0.00, Range: 0.00-0.00
tRNAs: 3.93 ± 9.13, Median: 0.50, IQR: 0.00-3.75, Range: 0.00-80.00
tmRNAs: 0.00 ± 0.00, Median: 0.00, IQR: 0.00-0.00, Range: 0.00-0.00

In [32]:
get_kegg_path_df(lq_df)

Before removing rows and columns with only zeros:
Clusters: 178
KEGG modules: 341

After removing rows and columns with only zeros:
Clusters: 146
KEGG modules: 309

KEGG modules: 19.88 ± 33.44, Median: 7.50, IQR: 3.00-21.00, Range: 1.00-238.00

,3-Hydroxypropionate bi-cycle,ADP-L-glycero-D-manno-heptose biosynthesis,"Abscisic acid biosynthesis, beta-carotene => abscisic acid",Acylglycerol degradation,"Adenine ribonucleotide biosynthesis, IMP => ADP,ATP","Adenine ribonucleotide degradation, AMP => Urate","Aflatoxin biosynthesis, malonyl-CoA => aflatoxin B1",Anoxygenic photosystem II,"Arginine biosynthesis, glutamate => acetylcitrulline => arginine","Arginine biosynthesis, ornithine => arginine",...,"V-type ATPase, eukaryotes","V/A-type ATPase, prokaryotes","Valine/isoleucine biosynthesis, pyruvate => valine / 2-oxobutanoate => isoleucine","Violacein biosynthesis, tryptophan => violacein","beta-Carotene biosynthesis, GGAP => beta-carotene",beta-Oxidation,"beta-Oxidation, acyl-CoA synthesis","beta-Oxidation, peroxisome, VLCFA","beta-Oxidation, peroxisome, tri/dihydroxycholestanoyl-CoA => choloyl/chenodeoxycholoyl-CoA",dTDP-L-rhamnose biosynthesis
29,1.39,0.0,0.0,50.0,25.0,16.67,0.00,0.0,14.29,33.33,...,7.69,0.0,37.5,0.0,0.0,66.67,100.0,66.67,0.00,0.00
30,0.00,0.0,0.0,50.0,0.0,16.67,14.29,0.0,0.00,33.33,...,0.00,0.0,25.0,0.0,0.0,0.00,0.0,0.00,0.00,0.00
31,5.56,0.0,0.0,0.0,50.0,0.00,0.00,0.0,0.00,0.00,...,15.38,0.0,50.0,0.0,0.0,0.00,0.0,0.00,0.00,0.00
32,13.89,0.0,0.0,100.0,75.0,100.00,14.29,0.0,28.57,100.00,...,30.77,0.0,100.0,0.0,0.0,83.33,100.0,66.67,33.33,50.00
34,0.00,0.0,0.0,50.0,25.0,0.00,0.00,0.0,0.00,33.33,...,15.38,0.0,50.0,0.0,0.0,16.67,100.0,0.00,0.00,16.67
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
210,0.00,0.0,0.0,0.0,0.0,0.00,0.00,0.0,0.00,0.00,...,0.00,0.0,25.0,0.0,0.0,0.00,0.0,0.00,0.00,0.00
211,0.00,0.0,0.0,0.0,0.0,0.00,0.00,0.0,0.00,0.00,...,0.00,0.0,0.0,0.0,0.0,0.00,0.0,0.00,0.00,0.00
212,0.00,0.0,0.0,0.0,0.0,0.00,0.00,0.0,0.00,0.00,...,0.00,0.0,0.0,0.0,0.0,0.00,0.0,0.00,0.00,0.00
213,0.00,0.0,0.0,0.0,0.0,0.00,0.00,0.0,0.00,0.00,...,7.69,0.0,0.0,0.0,0.0,0.00,0.0,0.00,0.00,0.00
214,0.00,0.0,0.0,0.0,0.0,0.00,0.00,0.0,0.00,0.00,...,0.00,0.0,0.0,0.0,0.0,33.33,0.0,0.00,0.00,0.00

# CAHJXG01 genus

## Quality

In [33]:
pseudo_mq_df = mq_df.query("Phylum == 'Pseudomonadota'").iloc[:, 7:24]
display(pseudo_mq_df)

,Cluster members,Completeness,Contamination,# N's per 100 kbp,# contigs,# contigs (>= 0 bp),# contigs (>= 1000 bp),GC (%),L50,L90,Largest contig,N50,N90,Total length,Total length (>= 0 bp),Total length (>= 1000 bp),auN
MAG,,,,,,,,,,,,,,,,,
ERR9966625_bin_1350,1,96.1,3.94,0.0,1583.0,1583.0,1583.0,64.08,551.0,1311.0,25008.0,3239.0,2517.0,5413774.0,5413774.0,5413774.0,4447.3
ERR9966620_bin_1469,6,55.9,3.73,0.0,22321.0,22321.0,22321.0,51.61,5870.0,18191.0,27845.0,1894.0,1114.0,43499712.0,43499712.0,43499712.0,3020.6

In [34]:
print("Ratio:")
round(pseudo_mq_df.iloc[1,] / pseudo_mq_df.iloc[0,], 2)

Ratio:

Cluster members               6.00
Completeness                  0.58
Contamination                 0.95
# N's per 100 kbp              NaN
# contigs                    14.10
# contigs (>= 0 bp)          14.10
# contigs (>= 1000 bp)       14.10
GC (%)                        0.81
L50                          10.65
L90                          13.88
Largest contig                1.11
N50                           0.58
N90                           0.44
Total length                  8.04
Total length (>= 0 bp)        8.04
Total length (>= 1000 bp)     8.04
auN                           0.68
dtype: float64

## Relative abundance

In [35]:
print_stats(mq_relative_abund_df_bis.xs("Cloud", level="Condition").loc[:,"Acetobacteraceae"].describe())

('CAHJXG01', 'unclassified'): 13.45 ± 5.86, Median: 12.48, IQR: 11.44-16.53, Range: 4.00-24.65

## Genome and functional annotations

In [36]:
pseudo_mq_bakta_annot = mq_bakta_annot.loc[["ERR9966625_bin_1350", "ERR9966620_bin_1469"],:]
display(pseudo_mq_bakta_annot)

,CDSs,CRISPR arrays,gaps,hypotheticals,ncRNA regions,ncRNAs,oriCs,oriTs,oriVs,pseudogenes,rRNAs,sORFs,signal peptides,tRNAs,tmRNAs
MAG,,,,,,,,,,,,,,,
ERR9966625_bin_1350,5189,0,0,3242,7,4,0,0,0,7,0,2,0,47,1
ERR9966620_bin_1469,73538,0,0,72226,5,2,0,0,0,21,21,1,0,226,0

In [37]:
print("Ratio:")
round(pseudo_mq_bakta_annot.iloc[1,] / pseudo_mq_bakta_annot.iloc[0,], 2)

Ratio:

CDSs               14.17
CRISPR arrays        NaN
gaps                 NaN
hypotheticals      22.28
ncRNA regions       0.71
ncRNAs              0.50
oriCs                NaN
oriTs                NaN
oriVs                NaN
pseudogenes         3.00
rRNAs                inf
sORFs               0.50
signal peptides      NaN
tRNAs               4.81
tmRNAs              0.00
dtype: float64

## MAGs inside the cluster with big genome

In [38]:
checkm2_fp = data_dp_2 / "checkm2"/ "ERR9966620_bin_1469.tsv"
checkm2_df = pd.read_csv(checkm2_fp, sep="\t")
checkm2_df["Genome_Size"] = checkm2_df["Genome_Size"] / 1000000
checkm2_df

,Name,Completeness,Contamination,Completeness_Model_Used,Translation_Table_Used,Coding_Density,Contig_N50,Average_Gene_Length,Genome_Size,GC_Content,Total_Coding_Sequences,Total_Contigs,Max_Contig_Length,Additional_Notes
0,ERR9966620_bin_1469,55.92,3.73,Gradient Boost (General Model),4,0.836,1894,160.607437,43.499712,0.52,76752,22321,27845,Low confidence prediction - substantial (44%) ...
1,ERR9966621_bin_11907,73.44,21.33,Gradient Boost (General Model),4,0.817,1973,152.681666,77.758492,0.51,141270,41275,43054,Low confidence prediction - substantial (26%) ...
2,ERR9966625_bin_1192,74.89,12.26,Gradient Boost (General Model),4,0.789,2295,141.626277,100.689536,0.49,190740,48137,50108,Low confidence prediction - substantial (25%) ...
3,ERR9966627_bin_1747,40.20,15.72,Gradient Boost (General Model),4,0.827,9282,156.890482,37.844392,0.51,68135,4399,71270,Low confidence prediction - substantial (59%) ...
4,ERR9966628_bin_19896,54.70,10.21,Gradient Boost (General Model),4,0.832,4315,158.165958,74.576100,0.52,133600,22771,55726,Low confidence prediction - substantial (45%) ...
5,ERR9966629_bin_12261,34.65,15.11,Gradient Boost (General Model),4,0.837,7852,147.470767,8.970469,0.50,17446,1261,36983,Low confidence prediction - substantial (59%) ...

In [39]:
print_stats(checkm2_df.describe())

Completeness: 55.63 ± 16.54, Median: 55.31, IQR: 43.83-69.06, Range: 34.65-74.89
Contamination: 13.06 ± 5.92, Median: 13.68, IQR: 10.72-15.57, Range: 3.73-21.33
Translation_Table_Used: 4.00 ± 0.00, Median: 4.00, IQR: 4.00-4.00, Range: 4.00-4.00
Coding_Density: 0.82 ± 0.02, Median: 0.83, IQR: 0.82-0.83, Range: 0.79-0.84
Contig_N50: 4601.83 ± 3228.45, Median: 3305.00, IQR: 2053.50-6967.75, Range: 1894.00-9282.00
Average_Gene_Length: 152.91 ± 7.21, Median: 154.79, IQR: 148.77-157.85, Range: 141.63-160.61
Genome_Size: 57.22 ± 33.18, Median: 59.04, IQR: 39.26-76.96, Range: 8.97-100.69
GC_Content: 0.51 ± 0.01, Median: 0.51, IQR: 0.50-0.52, Range: 0.49-0.52
Total_Coding_Sequences: 104657.17 ± 62139.84, Median: 105176.00, IQR: 70289.25-139352.50, Range: 17446.00-190740.00
Total_Contigs: 23360.67 ± 18889.99, Median: 22546.00, IQR: 8879.50-36649.00, Range: 1261.00-48137.00
Max_Contig_Length: 47497.67 ± 15206.41, Median: 46581.00, IQR: 38500.75-54321.50, Range: 27845.00-71270.00

# Unclassified cluster

In [40]:
unclassified_mq_df = mq_df.query("Phylum == 'unclassified'")
unclassified_mq_df.iloc[:, np.r_[0:1,7:24]]

,Domain,Cluster members,Completeness,Contamination,# N's per 100 kbp,# contigs,# contigs (>= 0 bp),# contigs (>= 1000 bp),GC (%),L50,L90,Largest contig,N50,N90,Total length,Total length (>= 0 bp),Total length (>= 1000 bp),auN
MAG,,,,,,,,,,,,,,,,,,
ERR9966629_bin_2487,Bacteria,4,59.7,8.55,0.0,604.0,604.0,604.0,46.26,167.0,469.0,18123.0,4397.0,2068.0,2282670.0,2282670.0,2282670.0,5428.6
ERR9966624_bin_1915,Archaea,1,59.5,8.70,0.0,2077.0,2077.0,2077.0,59.92,922.0,1826.0,3564.0,1247.0,1047.0,2579262.0,2579262.0,2579262.0,1269.8
ERR9966620_bin_1091,Bacteria,1,57.1,8.82,0.0,1860.0,1860.0,1860.0,48.00,755.0,1605.0,5119.0,1450.0,1136.0,2744751.0,2744751.0,2744751.0,1585.9
ERR9966627_bin_841,unclassified,1,56.7,7.14,0.0,449.0,449.0,449.0,44.53,114.0,355.0,18136.0,3542.0,1631.0,1301435.0,1301435.0,1301435.0,4491.9
ERR9966629_bin_15813,unclassified,1,56.1,6.45,0.0,488.0,488.0,488.0,53.21,132.0,377.0,19901.0,4227.0,1991.0,1765345.0,1765345.0,1765345.0,5283.9
ERR9966628_bin_3376,unclassified,1,55.2,9.69,0.0,510.0,510.0,510.0,49.80,244.0,455.0,3417.0,3118.0,2892.0,1583889.0,1583889.0,1583889.0,3114.3

In [41]:
compute_print_stats(unclassified_mq_df)

Total number: 6.0
Cluster members: 1.50 ± 1.22, Median: 1.00, IQR: 1.00-1.00, Range: 1.00-4.00
Contamination: 8.22 ± 1.20, Median: 8.62, IQR: 7.49-8.79, Range: 6.45-9.69
Completeness: 57.38 ± 1.83, Median: 56.90, IQR: 56.25-58.90, Range: 55.20-59.70
Total length: 2.04 ± 0.58, Median: 2.02, IQR: 1.63-2.51, Range: 1.30-2.74

In [42]:
mq_df.query("Domain == 'Archaea'").iloc[:, np.r_[0:1,7:24]]

,Domain,Cluster members,Completeness,Contamination,# N's per 100 kbp,# contigs,# contigs (>= 0 bp),# contigs (>= 1000 bp),GC (%),L50,L90,Largest contig,N50,N90,Total length,Total length (>= 0 bp),Total length (>= 1000 bp),auN
MAG,,,,,,,,,,,,,,,,,,
ERR9966624_bin_1915,Archaea,1,59.5,8.7,0.0,2077.0,2077.0,2077.0,59.92,922.0,1826.0,3564.0,1247.0,1047.0,2579262.0,2579262.0,2579262.0,1269.8

In [43]:
unclassified_cov_df = unclassified_mq_df.copy()
unclassified_cov_df.reset_index(inplace=True)
unclassified_cov_df = unclassified_cov_df.iloc[:, :2]
unclassified_cov_df
unclassified_cov_df = unclassified_cov_df.merge(
    coverage_df,
    left_on="MAG",
    right_on="Genome",
    how="left",
)
unclassified_cov_df = unclassified_cov_df.set_index(pd.MultiIndex.from_frame(unclassified_cov_df[["Genome", "Domain"]]))
unclassified_cov_df = unclassified_cov_df.drop(columns=["MAG", "Domain", "Genome"], errors="ignore") 
#metadata_df.loc[list(unclassified_cov_df[["MAG"]]), ["run_accession", "Condition", "Season", "Geographic origin of the air mass"]]
index_df = metadata_df.loc[:, ["run_accession", "Condition", "Season", "Geographic origin of the air mass"]]
unclassified_cov_df = unclassified_cov_df.T.set_index(pd.MultiIndex.from_frame(index_df))
unclassified_cov_df = unclassified_cov_df.T
unclassified_cov_df

,run_accession,ERR9966616,ERR9966617,ERR9966618,ERR9966619,ERR9966620,ERR9966621,ERR9966622,ERR9966623,ERR9966624,ERR9966625,ERR9966626,ERR9966627,ERR9966628,ERR9966629
,Condition,Clear atmosphere,Clear atmosphere,Clear atmosphere,Clear atmosphere,Clear atmosphere,Cloud,Cloud,Cloud,Cloud,Cloud,Cloud,Cloud,Cloud,Cloud
,Season,Summer,Summer,Summer,Autumn,Autumn,Autumn,Autumn,Winter,Summer,Autumn,Autumn,Autumn,Autumn,Autumn
,Geographic origin of the air mass,Northwest,Northwest,North,West,West,Northwest,South,West,Northwest,Norteast,West,West,Southwest,West
Genome,Domain,,,,,,,,,,,,,,
ERR9966629_bin_2487,Bacteria,0.0,0.0,0.0,0.999377,0.162276,0.090060,0.194641,0.190573,0.427815,0.139764,0.211608,0.248482,0.227564,0.179798
ERR9966624_bin_1915,Archaea,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.006909,0.141591,0.007542,0.010140,0.003731,0.012917,0.004110
ERR9966620_bin_1091,Bacteria,0.0,0.0,0.0,0.013337,0.096801,0.027124,0.062711,0.061606,0.013065,0.028496,0.054291,0.066056,0.063007,0.028732
ERR9966627_bin_841,unclassified,0.0,0.0,0.0,0.015128,0.099212,0.044074,0.137813,0.121271,0.044127,0.131286,0.153663,0.255773,0.170292,0.068910
ERR9966629_bin_15813,unclassified,0.0,0.0,0.0,0.070726,0.187867,0.106024,0.181454,0.431071,0.091190,0.160155,0.203860,0.246747,0.239829,0.227951
ERR9966628_bin_3376,unclassified,0.0,0.0,0.0,0.042128,0.044248,0.056758,0.056832,0.146604,0.042469,0.042301,0.065441,0.066087,0.076630,0.027206

In [44]:
print(f"Samples in which Archaea cluster is present: {(unclassified_cov_df.xs('Archaea', level='Domain') != 0).sum(axis=1).iloc[0]}")

Samples in which Archaea cluster is present: 7

## Functions

In [45]:
unclassified_mq_bakta_annot = get_bakta_annot_df(unclassified_mq_df)
unclassified_mq_bakta_annot

,CDSs,CRISPR arrays,gaps,hypotheticals,ncRNA regions,ncRNAs,oriCs,oriTs,oriVs,pseudogenes,rRNAs,sORFs,signal peptides,tRNAs,tmRNAs
MAG,,,,,,,,,,,,,,,
ERR9966629_bin_2487,2097,0,0,2079,0,0,0,0,0,1,16,0,0,37,0
ERR9966624_bin_1915,4344,0,0,4342,0,0,0,0,0,0,0,0,0,14,0
ERR9966620_bin_1091,4949,0,0,4945,0,0,0,0,0,0,0,0,0,12,0
ERR9966627_bin_841,1433,1,0,1429,0,0,0,0,0,0,8,0,0,13,0
ERR9966629_bin_15813,1722,0,0,1713,0,1,1,1,0,1,13,0,0,19,0
ERR9966628_bin_3376,2726,0,0,2724,0,0,0,0,0,0,0,0,0,5,0

In [46]:
print_stats(unclassified_mq_bakta_annot.describe())

CDSs: 2878.50 ± 1448.84, Median: 2411.50, IQR: 1815.75-3939.50, Range: 1433.00-4949.00
CRISPR arrays: 0.17 ± 0.41, Median: 0.00, IQR: 0.00-0.00, Range: 0.00-1.00
gaps: 0.00 ± 0.00, Median: 0.00, IQR: 0.00-0.00, Range: 0.00-0.00
hypotheticals: 2872.00 ± 1451.52, Median: 2401.50, IQR: 1804.50-3937.50, Range: 1429.00-4945.00
ncRNA regions: 0.00 ± 0.00, Median: 0.00, IQR: 0.00-0.00, Range: 0.00-0.00
ncRNAs: 0.17 ± 0.41, Median: 0.00, IQR: 0.00-0.00, Range: 0.00-1.00
oriCs: 0.17 ± 0.41, Median: 0.00, IQR: 0.00-0.00, Range: 0.00-1.00
oriTs: 0.17 ± 0.41, Median: 0.00, IQR: 0.00-0.00, Range: 0.00-1.00
oriVs: 0.00 ± 0.00, Median: 0.00, IQR: 0.00-0.00, Range: 0.00-0.00
pseudogenes: 0.33 ± 0.52, Median: 0.00, IQR: 0.00-0.75, Range: 0.00-1.00
rRNAs: 6.17 ± 7.22, Median: 4.00, IQR: 0.00-11.75, Range: 0.00-16.00
sORFs: 0.00 ± 0.00, Median: 0.00, IQR: 0.00-0.00, Range: 0.00-0.00
signal peptides: 0.00 ± 0.00, Median: 0.00, IQR: 0.00-0.00, Range: 0.00-0.00
tRNAs: 16.67 ± 10.93, Median: 13.50, IQR: 12.25-17.75, Range: 5.00-37.00
tmRNAs: 0.00 ± 0.00, Median: 0.00, IQR: 0.00-0.00, Range: 0.00-0.00

In [47]:
unclassified_mq_kegg_df = get_kegg_path_df(unclassified_mq_df)

Before removing rows and columns with only zeros:
Clusters: 6
KEGG modules: 341

After removing rows and columns with only zeros:
Clusters: 6
KEGG modules: 138

KEGG modules: 38.33 ± 36.03, Median: 24.50, IQR: 9.50-64.25, Range: 8.00-91.00

## Samples with rRNAs

In [48]:
mags_with_rRNAs = unclassified_mq_bakta_annot.query("rRNAs != 0").index.to_list()
mags_with_rRNAs

['ERR9966629_bin_2487', 'ERR9966627_bin_841', 'ERR9966629_bin_15813']

In [49]:
rRNAs_dfs = pd.DataFrame()
rRNAs_product_df = pd.DataFrame(index=mags_with_rRNAs)

for mag in mags_with_rRNAs:
    rrna_df = (
        read_bakta_gff_file(mag, data_dp_2)
        .query("type == 'rRNA'")
        .copy()
    )

    attrs_df = extract_gff_attributes(rrna_df)

    # Split Dbxref values like "ID:VALUE,ID2:VALUE2" into separate columns.
    dbxref_series = attrs_df.get("Dbxref", pd.Series("", index=attrs_df.index)).fillna("").astype(str)
    parsed_dbxref = dbxref_series.apply(
        lambda dbxref: {
            db_id.strip(): db_value.strip()
            for item in dbxref.split(",")
            if ":" in item
            for db_id, db_value in [item.split(":", 1)]
        }
    )
    dbxref_df = pd.json_normalize(parsed_dbxref)

    rrna_df = pd.concat([rrna_df, attrs_df, dbxref_df], axis=1)
    rrna_df["MAG"] = mag
    rRNAs_dfs = pd.concat([rRNAs_dfs, rrna_df], ignore_index=True)

    print(mag)
    print(f"Number of rRNAs: {rrna_df.shape[0]}")

    value_counts = rrna_df[["product"]].value_counts()
    display(value_counts)

    # Build a MAG x rRNA-product matrix with dynamic columns.
    for product, count in value_counts.items():
        rRNAs_product_df.loc[mag, product] = count

rRNAs_product_df = rRNAs_product_df.fillna(0).astype(int)
rRNAs_product_df

ERR9966629_bin_2487
Number of rRNAs: 16

product
5S ribosomal RNA     13
16S ribosomal RNA     2
23S ribosomal RNA     1
Name: count, dtype: int64

ERR9966627_bin_841
Number of rRNAs: 8

product
5S ribosomal RNA               5
16S ribosomal RNA              2
(partial) 23S ribosomal RNA    1
Name: count, dtype: int64

ERR9966629_bin_15813
Number of rRNAs: 13

product
5S ribosomal RNA                    6
(partial) 16S ribosomal RNA         5
(3' truncated) 23S ribosomal RNA    1
(3' truncated) 16S ribosomal RNA    1
Name: count, dtype: int64

,5S ribosomal RNA,16S ribosomal RNA,23S ribosomal RNA,(partial) 23S ribosomal RNA,(partial) 16S ribosomal RNA,(3' truncated) 23S ribosomal RNA,(3' truncated) 16S ribosomal RNA
ERR9966629_bin_2487,13,2,1,0,0,0,0
ERR9966627_bin_841,5,2,0,1,0,0,0
ERR9966629_bin_15813,6,0,0,0,5,1,1

In [50]:
rRNAs_dfs.groupby(["MAG","RFAM"]).count()

                              seqid  source  type  start  end  score  strand  \
MAG                  RFAM
ERR9966627_bin_841   RF00001      5       5     5      5    5      5       5
                     RF00177      2       2     2      2    2      2       2
                     RF02541      1       1     1      1    1      1       1
ERR9966629_bin_15813 RF00001      6       6     6      6    6      6       6
                     RF00177      6       6     6      6    6      6       6
                     RF02541      1       1     1      1    1      1       1
ERR9966629_bin_2487  RF00001     13      13    13     13   13     13      13
                     RF00177      2       2     2      2    2      2       2
                     RF02541      1       1     1      1    1      1       1

                              phase  attributes  ID  Name  locus_tag  gene  \
MAG                  RFAM
ERR9966627_bin_841   RF00001      5           5   5     5          5     5
                     RF00177      2           2   2     2          2     2
                     RF02541      1           1   1     1          1     1
ERR9966629_bin_15813 RF00001      6           6   6     6          6     6
                     RF00177      6           6   6     6          6     6
                     RF02541      1           1   1     1          1     1
ERR9966629_bin_2487  RF00001     13          13  13    13         13    13
                     RF00177      2           2   2     2          2     2
                     RF02541      1           1   1     1          1     1

                              product  Dbxref  GO  KEGG  SO
MAG                  RFAM
ERR9966627_bin_841   RF00001        5       5   5     5   5
                     RF00177        2       2   2     2   2
                     RF02541        1       1   1     1   1
ERR9966629_bin_15813 RF00001        6       6   6     6   6
                     RF00177        6       6   6     6   6
                     RF02541        1       1   1     1   1
ERR9966629_bin_2487  RF00001       13      13  13    13  13
                     RF00177        2       2   2     2   2
                     RF02541        1       1   1     1   1

In [51]:
print_stats(rRNAs_product_df.describe())

5S ribosomal RNA: 8.00 ± 4.36, Median: 6.00, IQR: 5.50-9.50, Range: 5.00-13.00
16S ribosomal RNA: 1.33 ± 1.15, Median: 2.00, IQR: 1.00-2.00, Range: 0.00-2.00
23S ribosomal RNA: 0.33 ± 0.58, Median: 0.00, IQR: 0.00-0.50, Range: 0.00-1.00
(partial) 23S ribosomal RNA: 0.33 ± 0.58, Median: 0.00, IQR: 0.00-0.50, Range: 0.00-1.00
(partial) 16S ribosomal RNA: 1.67 ± 2.89, Median: 0.00, IQR: 0.00-2.50, Range: 0.00-5.00
(3' truncated) 23S ribosomal RNA: 0.33 ± 0.58, Median: 0.00, IQR: 0.00-0.50, Range: 0.00-1.00
(3' truncated) 16S ribosomal RNA: 0.33 ± 0.58, Median: 0.00, IQR: 0.00-0.50, Range: 0.00-1.00

In [52]:
bed_dp = result_dp / "rrna_16S_18S_per_mag"
bed_dp.mkdir(parents=True, exist_ok=True)

for mag, rrna_df in rRNAs_dfs.groupby("MAG"):
    if "product" not in rrna_df.columns:
        continue

    mask = rrna_df["product"].fillna("").str.contains(r"(?:16S|18S)", case=False, regex=True)
    export_df = rrna_df.loc[mask, ["seqid", "start", "end", "strand"]].copy()

    bed_df = pd.DataFrame(
        {
            "chrom": export_df["seqid"],
            # BED uses 0-based starts and half-open intervals.
            "chromStart": pd.to_numeric(export_df["start"], errors="coerce").fillna(1).astype(int).sub(1).clip(lower=0),
            "chromEnd": pd.to_numeric(export_df["end"], errors="coerce").fillna(0).astype(int),
            "name": [f"{mag}_rRNA_{i + 1}" for i in range(export_df.shape[0])],
            "score": 0,
            "strand": export_df["strand"].fillna("."),
        }
    )

    bed_fp = bed_dp / f"{mag}.bed"
    bed_df.to_csv(bed_fp, sep="\t", index=False, header=False)
    print(f"{mag}: {bed_df.shape[0]} BED rows written to {bed_fp}")

sorted([p.name for p in bed_dp.glob("*.bed")])

ERR9966627_bin_841: 2 BED rows written to ../results/cloud-use-case/rrna_16S_18S_per_mag/ERR9966627_bin_841.bed
ERR9966629_bin_15813: 6 BED rows written to ../results/cloud-use-case/rrna_16S_18S_per_mag/ERR9966629_bin_15813.bed
ERR9966629_bin_2487: 2 BED rows written to ../results/cloud-use-case/rrna_16S_18S_per_mag/ERR9966629_bin_2487.bed

['ERR9966627_bin_841.bed',
 'ERR9966629_bin_15813.bed',
 'ERR9966629_bin_2487.bed']

### Without rRNAs

In [53]:
mags_without_rRNAs = unclassified_mq_bakta_annot.query("rRNAs == 0").index.to_list()
mags_without_rRNAs

['ERR9966624_bin_1915', 'ERR9966620_bin_1091', 'ERR9966628_bin_3376']

In [54]:
ERR9966628_bin_3376_tRNA_df = read_bakta_gff_file("ERR9966628_bin_3376", data_dp_2).query("type == 'tRNA'")
extract_gff_attributes(ERR9966628_bin_3376_tRNA_df)

,ID,Name,locus_tag,product,Dbxref,gene,anti_codon,amino_acid,pseudo
397,DLIJOE_01700,tRNA-Xxx,DLIJOE_01700,tRNA-Xxx,NaN,NaN,NaN,NaN,NaN
869,DLIJOE_03720,tRNA-Ser(aga),DLIJOE_03720,tRNA-Ser(aga),SO:0000269,trnS,aga,Ser,NaN
2119,DLIJOE_08990,tRNA-Pro(tgg),DLIJOE_08990,tRNA-Pro(tgg),SO:0000268,trnP,tgg,Pro,True
2395,DLIJOE_10145,tRNA-Gly(ccc),DLIJOE_10145,tRNA-Gly(ccc),SO:0000260,trnG,ccc,Gly,NaN
2644,DLIJOE_11190,tRNA-Xxx,DLIJOE_11190,tRNA-Xxx,NaN,NaN,NaN,NaN,NaN

# Cluster with completness = 100%

In [55]:
complete_df = reps_df.query("Completeness == 100")
complete_df["Total length"] = complete_df["Total length"]/1000000
complete_df.iloc[:, np.r_[0:1,7:24]]

,MAG,Species,Cluster members,Completeness,Contamination,# N's per 100 kbp,# contigs,# contigs (>= 0 bp),# contigs (>= 1000 bp),GC (%),L50,L90,Largest contig,N50,N90,Total length,Total length (>= 0 bp),Total length (>= 1000 bp)
0,ERR9966624_bin_2765,unclassified,1,100.0,26.55,0.0,1870.0,1870.0,1870.0,53.55,592.0,1502.0,22402.0,6214.0,3705.0,10.83139,10831390.0,10831390.0

In [56]:
get_bakta_annot_df(complete_df)

,CDSs,CRISPR arrays,gaps,hypotheticals,ncRNA regions,ncRNAs,oriCs,oriTs,oriVs,pseudogenes,rRNAs,sORFs,signal peptides,tRNAs,tmRNAs
0,20836,0,0,20823,0,0,0,0,0,4,0,0,0,3,0

In [57]:
get_kegg_path_df(complete_df)

Before removing rows and columns with only zeros:
Clusters: 1
KEGG modules: 341

After removing rows and columns with only zeros:
Clusters: 1
KEGG modules: 169

KEGG modules: 169.00 ± nan, Median: 169.00, IQR: 169.00-169.00, Range: 169.00-169.00

,Acylglycerol degradation,"Adenine ribonucleotide biosynthesis, IMP => ADP,ATP","Adenine ribonucleotide degradation, AMP => Urate","Arginine biosynthesis, glutamate => acetylcitrulline => arginine","Arginine biosynthesis, ornithine => arginine","Ascorbate biosynthesis, animals, glucose-1P => ascorbate","Ascorbate biosynthesis, plants, fructose-6P => ascorbate","Assimilatory nitrate reduction, nitrate => ammonia","Assimilatory sulfate reduction, sulfate => H2S","Betaine biosynthesis, choline => betaine",...,"Tyrosine degradation, tyrosine => homogentisate","UDP-N-acetyl-D-glucosamine biosynthesis, eukaryotes, glucose => UDP-GlcNAc","UDP-N-acetyl-D-glucosamine biosynthesis, prokaryotes, glucose => UDP-GlcNAc","Ubiquinone biosynthesis, eukaryotes, 4-hydroxybenzoate + polyprenyl-PP => ubiquinol","Ubiquinone biosynthesis, prokaryotes, chorismate (+ polyprenyl-PP) => ubiquinol",Urea cycle,"V-type ATPase, eukaryotes","Valine/isoleucine biosynthesis, pyruvate => valine / 2-oxobutanoate => isoleucine",beta-Oxidation,"beta-Oxidation, acyl-CoA synthesis"
0,100.0,50.0,33.33,28.57,100.0,28.57,12.5,50.0,33.33,50.0,...,20.0,50.0,20.0,50.0,22.22,80.0,23.08,62.5,66.67,100.0